- Dockerfile.prow
- Makefile.prow
https://github.com/open-cluster-management/backlog/issues/10144
> Add prow files

- controllers/placementrule/placementrule_controller.go
- controllers/placementrule/serviceaccount.go
- controllers/placementrule/serviceaccount_test.go
https://github.com/open-cluster-management/backlog/issues/10004
> switch to use clusterrole to replace roles in each cluster namespace

- go.mod
- go.sum
https://github.com/open-cluster-management/backlog/issues/9812
> update golang.org/x/text to v0.3.5

- README.md
Ref: https://github.com/open-cluster-management/backlog/issues/10207
> add build and deploy the operator steps.

- README.md
- bundle/manifests/core.observatorium.io_observatoria.yaml
- config/crd/bases/core.observatorium.io_observatoria.yaml
- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- controllers/multiclusterobservability/multiclusterobservability_status.go
- controllers/multiclusterobservability/observatorium.go
- controllers/multiclusterobservability/observatorium_test.go
- deploy/olm-catalog/multicluster-observability-operator/manifests/core.observatorium.io_observatoria.yaml
- deploy/req_crds/core.observatorium.io_observatoria.yaml
- go.mod
- go.sum
- manifests/base/proxy/deployment.yaml
- pkg/config/config.go
https://github.com/open-cluster-management/backlog/issues/8414
> Update thanos to 0.18.0

- controllers/placementrule/manifestwork.go
- controllers/placementrule/obsaddon.go
- controllers/placementrule/placementrule_controller.go
- controllers/placementrule/status.go
https://github.com/open-cluster-management/backlog/issues/10461
> refactoring for obsaddon/manifestwork delete flow

- pkg/config/config.go
https://github.com/open-cluster-management/backlog/issues/8412
> Upgrade grafana to 7.4.2

- Makefile.prow
- README.md
- config/certmanager/certificate.yaml
- config/crd/patches/webhook_in_multiclusterobservabilities.yaml
- config/crd/patches/webhook_in_observabilityaddons.yaml
- config/default/kustomization.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_config_patch.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/prometheus/monitor.yaml
- config/rbac/auth_proxy_role_binding.yaml
- config/rbac/auth_proxy_service.yaml
- config/rbac/kustomization.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/mco_role.yaml
- config/rbac/mco_role_binding.yaml
- config/rbac/service_account.yaml
follow up PR for: https://github.com/open-cluster-management/multicluster-observability-operator/pull/394 
depends on: https://github.com/open-cluster-management/multicluster-observability-operator/pull/400
Ref: https://github.com/open-cluster-management/backlog/issues/10207
> Deploy MCO with new manifests with kustomize

- controllers/multiclusterobservability/observatorium.go
- pkg/config/config.go
fixed https://github.com/open-cluster-management/backlog/issues/10688
> update img to ocm upstream

- controllers/placementrule/manifestwork.go
- controllers/placementrule/placementrule_controller.go
- controllers/placementrule/placementrule_controller_test.go
- controllers/placementrule/serviceaccount.go
- controllers/placementrule/serviceaccount_test.go
1. clean old manifestworks
2. clean old roles: https://github.com/open-cluster-management/backlog/issues/10004
> delete deprecated roles/manifestworks in 2.2

- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- pkg/util/util.go
https://github.com/open-cluster-management/backlog/issues/9124
> Handle resize the storage

- manifests/base/observatorium/cluster_role.yaml
https://github.com/open-cluster-management/backlog/issues/10847
> add permission for observatorium sa for crud of poddisruptionbudgets

- bundle/manifests/core.observatorium.io_observatoria.yaml
- config/crd/bases/core.observatorium.io_observatoria.yaml
- controllers/multiclusterobservability/observatorium.go
- controllers/multiclusterobservability/observatorium_test.go
- go.mod
- go.sum
Upgrade obs to adopt new feature - fetch image from obs cr.
> Upgrade obs to adopt new feature

- bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- bundle/manifests/multicluster-observability-webhook-service_v1_service.yaml
- config/certmanager/certificate.yaml
- config/default/manager_webhook_patch.yaml
- config/webhook/ocp_ssc_in_webhook_service.yaml
ref: open-cluster-management/backlog#10749
> update webhook secret name.

- Makefile.prow
- bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
ref: open-cluster-management/backlog#10749
based on #404
> add deprecated message for v1beta1 version.

- docs/MultiClusterObservability-CRD.md
https://github.com/open-cluster-management/backlog/issues/9124
> update api document

- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/observatorium.go
- controllers/multiclusterobservability/observatorium_test.go
- main.go
https://github.com/open-cluster-management/backlog/issues/8803
> Tackle replicas

- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- controllers/multiclusterobservability/multiclusterobservability_status.go
- controllers/multiclusterobservability/observatorium.go
- controllers/multiclusterobservability/observatorium_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/rendering/renderer.go
- pkg/rendering/renderer_alertmanager.go
- pkg/rendering/renderer_grafana.go
- pkg/util/util.go
- pkg/util/util_test.go
https://github.com/open-cluster-management/backlog/issues/8803
> Support configure replicas for alertmanager/grafana/rbac-query-proxy

- bundle/manifests/multicluster-observability-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- config/rbac/mco_role.yaml
- manifests/base/grafana/ingress.yaml
https://github.com/open-cluster-management/backlog/issues/10925
> upgrade ingress version

- bundle/manifests/multicluster-observability-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- config/rbac/mco_role.yaml
- controllers/placementrule/kubeconfig.go
- controllers/placementrule/kubeconfig_test.go
- pkg/config/config.go
- pkg/config/config_test.go
https://github.com/open-cluster-management/backlog/issues/11120
>  support roks

- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- controllers/multiclusterobservability/multiclusterobservability_status.go
Treat the status is ready when the `readdyReplicas` is equals to `replicas`
> Update CR Ready status condition

- controllers/placementrule/placementrule_controller.go
- controllers/placementrule/status.go
- pkg/util/managedclusteraddon.go
https://github.com/open-cluster-management/backlog/issues/11216
> update status in mca

- bundle/manifests/core.observatorium.io_observatoria.yaml
- config/crd/bases/core.observatorium.io_observatoria.yaml
https://github.com/open-cluster-management/observatorium-operator/pull/21
> Update crds version

- Dockerfile.prow
- README.md
1. update base image to multiarch - https://github.com/open-cluster-management/backlog/issues/11324
2. fix doc for MCO CR apply
> update base image to multiarch and fix doc.

- Dockerfile.prow
Reverts open-cluster-management/multicluster-observability-operator#451
> Revert "fix base image not found issue."

- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/placementrule/placementrule_controller.go
ref: https://github.com/open-cluster-management/backlog/issues/11277
It fixs the issue based on my local testing:
I create three `PlacementRule` resources in other namespaces before I do the testing:
```
NAMESPACE                               NAME                  AGE     REPLICAS
default                                 placementrule-test1   4m35s
kube-system                             placementrule-test2   3m58s
open-cluster-management-observability   observability         10m
open-cluster-management                 placementrule-test3   3m16s
```
Before the fix, you can see watch and reconcile for all these placementrules from MCO logs:
```
2021-04-08T04:48:00.487Z	INFO	controller_placementrule	Reconciling PlacementRule	{"Request.Namespace": "open-cluster-management-observability", …
```
> set up manager and watch resource with new operator-sdk style.

- manifests/base/alertmanager/alertmanager-statefulset.yaml
- pkg/config/config.go
- pkg/rendering/renderer_alertmanager.go
fixed https://github.com/open-cluster-management/backlog/issues/11094
/hold
> update alertmgr img to ocm upstream

- tools/generate-dashboard-configmap-yaml.sh
- tools/setup-grafana-dev.sh
- tools/switch-to-grafana-admin.sh
due to we change grafana deployment name. this breaks our grafana-dev feature. so we need to update the script.
/hold
> update grafana deploy name

- controllers/multiclusterobservability/observatorium.go
- pkg/config/config.go
update observatorium to use quay.io/open-cluster-management image. 
https://github.com/open-cluster-management/backlog/issues/7260
> update observatorium image

- tests/benchmark/setup-metrics-collector.sh
> Update scripts to replace --export

- manifests/base/grafana/deployment.yaml
- tools/setup-grafana-dev.sh
https://github.com/open-cluster-management/backlog/issues/11237
/hold
> update fsGroup value from pod

- controllers/placementrule/manifestwork.go
- controllers/placementrule/placementrule_controller.go
- pkg/certificates/certificates.go
https://github.com/open-cluster-management/backlog/issues/11085
> remove client cert generation for managed cluster

- README.md
ref: https://github.com/open-cluster-management/backlog/issues/11088
> remove certmanager dependency.

- tools/generate-dashboard-configmap-yaml.sh
https://github.com/open-cluster-management/backlog/issues/11743
> delete dashboard uid avoid conflict wit old dashboard

- tools/generate-dashboard-configmap-yaml.sh
- tools/setup-grafana-dev.sh
https://github.com/open-cluster-management/backlog/issues/11381
> delete dashboard uid avoid conflict with old dashboard

- deploy/olm-catalog/multicluster-observability-operator/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- deploy/role.yaml
https://github.com/open-cluster-management/backlog/issues/11739
> Grant permission to serviceaccount

- api/v1beta2/multiclusterobservability_types.go
- bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- controllers/multiclusterobservability/observatorium.go
fixed https://github.com/open-cluster-management/backlog/issues/11628
> Support configure retentionConfig in MCO CR

- bundle/manifests/multicluster-observability-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- config/rbac/mco_role.yaml
- controllers/placementrule/endpoint_metrics_operator.go
- controllers/placementrule/placementrule_controller.go
- controllers/placementrule/role.go
- controllers/placementrule/role_test.go
- manifests/endpoint-observability/operator.yaml
- manifests/endpoint-observability/role.yaml
> remove old lease impl in hub side

- manifests/base/config/metrics_allowlist.yaml
> add new metrics for 4.8, update renames

- manifests/base/config/metrics_allowlist.yaml
> add renamed metric

- manifests/base/observatorium/operator.yaml
> set log level to info

- bundle/manifests/core.observatorium.io_observatoria.yaml
- config/crd/bases/core.observatorium.io_observatoria.yaml
- fix https://github.com/open-cluster-management/backlog/issues/11910
- https://github.com/open-cluster-management/backlog/issues/11860
- https://github.com/open-cluster-management/backlog/issues/11902
- https://github.com/open-cluster-management/backlog/issues/11897
- https://github.com/open-cluster-management/backlog/issues/11895
> update observatorium crd

- controllers/multiclusterobservability/observatorium.go
- pkg/config/config.go
- pkg/rendering/renderer_alertmanager.go
- replace bytes.Compare to reflect.DeepEqual
- fix image replace issue
> fix image replace issue

- manifests/base/config/metrics_allowlist.yaml
> add kube_node_status_capacity metric

- controllers/placementrule/obsaddon.go
- controllers/placementrule/obsaddon_test.go
- controllers/placementrule/placementrule_controller.go
https://github.com/open-cluster-management/backlog/issues/11917
> remove addon's finalizer forcely after delete it 5 minutes later

- main.go
- pkg/certificates/cert_controller.go
- pkg/certificates/certificates.go
https://github.com/open-cluster-management/backlog/issues/11157
support certificate rotation, not include CA rotation, which will be included in another pr
> cert rotation

- tests/e2e/setup.sh
> Have the registration and registration-operator image fixed

- manifests/base/grafana/dash-acm-clusters-overview.yaml
- manifests/base/grafana/dash-acm-optimization-overview.yaml
- manifests/base/grafana/dash-cluster-rsrc-use.yaml
- manifests/base/grafana/dash-k8s-apiserver.yaml
- manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
- manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
- manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
- manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
- manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
- manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
- manifests/base/grafana/dash-k8s-networking-cluster.yaml
- manifests/base/grafana/dash-k8s-networking-namespace-pods.yaml
- manifests/base/grafana/dash-k8s-networking-pod.yaml
- manifests/base/grafana/dash-node-rsrc-use.yaml
Related user story: https://github.com/open-cluster-management/backlog/issues/7367
> update queries with compatable metrics across supported ocp clusters for acm2.3

- bundle/manifests/core.observatorium.io_observatoria.yaml
- config/crd/bases/core.observatorium.io_observatoria.yaml
- controllers/multiclusterobservability/observatorium.go
- go.mod
- go.sum
https://github.com/open-cluster-management/backlog/issues/11991
> Support configuring queryFrontendCache

- tests/benchmark/setup-metrics-collector.sh
> Update simulator to create cert

- pkg/config/config.go
https://github.com/open-cluster-management/backlog/issues/11916
https://github.com/observatorium/thanos-receive-controller/pull/76
> update thanos-receive-controller img due  to upgrade golang to 1.16

- docs/MultiClusterObservability-CRD.md
https://github.com/open-cluster-management/backlog/issues/11915
> remove CleanupInterval

- cicd-scripts/run-e2e-tests.sh
> enable e2e

- manifests/endpoint-observability/role.yaml
https://github.com/open-cluster-management/backlog/issues/11675
> update role for endpoint operator so it can list nodes for mc

- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- controllers/multiclusterobservability/observatorium.go
- controllers/placementrule/placementrule_controller_test.go
- go.mod
- main.go
- pkg/certificates/cert_controller.go
- pkg/certificates/certificates.go
- pkg/certificates/signer.go
> support ca cert rotation

- manifests/base/config/metrics_allowlist.yaml
> remove unnecessary comma in metrics rename rule

- pkg/certificates/approver_test.go
- pkg/certificates/cert_agent_test.go
- pkg/certificates/cert_controller.go
- pkg/certificates/cert_controller_test.go
- pkg/certificates/certificates.go
- pkg/certificates/certificates_test.go
- pkg/certificates/signer.go
- pkg/certificates/signer_test.go
> add unit test for certificates scenarios

- manifests/base/config/metrics_allowlist.yaml
fixed https://github.com/open-cluster-management/backlog/issues/11681
> Filter by job=apiserver

- controllers/placementrule/manifestwork.go
- controllers/placementrule/manifestwork_test.go
- manifests/base/config/metrics_allowlist.yaml
- manifests/base/grafana/dash-acm-clusters-overview.yaml
- manifests/base/grafana/dash-k8s-apiserver.yaml
Ref https://github.com/open-cluster-management/backlog/issues/11950
Signed-off-by: haoqing0110 <qhao@redhat.com>
> add recording rule for apiserver_request_duration_seconds_bucket

- main.go
- pkg/config/config.go
- pkg/util/client.go
fix: open-cluster-management/backlog#12287
> fix webhook namespace.

- pkg/certificates/certificates.go
- pkg/config/config.go
fix: https://github.com/open-cluster-management/backlog/issues/12368
> add mco annotation of cert duration for dev/test

- manifests/base/config/metrics_allowlist.yaml
> add metric and recording rules for etcd rpc

- manifests/base/grafana/dash-k8s-etcd.yaml
- manifests/base/grafana/kustomization.yaml
related issue: [12306](https://github.com/open-cluster-management/backlog/issues/12306)
> add etcd dashboard

- bundle/manifests/core.observatorium.io_observatoria.yaml
- config/crd/bases/core.observatorium.io_observatoria.yaml
- controllers/multiclusterobservability/observatorium.go
- go.mod
- go.sum
fix: open-cluster-management/backlog#12396
> pass pull secret to observatorium res

- pkg/certificates/cert_controller.go
- pkg/certificates/certificates.go
fix the problem in byo scenario
https://github.com/open-cluster-management/backlog/issues/11158
> don't create/renew server cert if failed to get api route url

- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- controllers/multiclusterobservability/multiclusterobservability_status.go
- controllers/multiclusterobservability/observatorium.go
- controllers/multiclusterobservability/observatorium_test.go
- controllers/placementrule/manifestwork_test.go
- manifests/base/proxy/deployment.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/rendering/renderer.go
- pkg/rendering/renderer_alertmanager.go
- we should have a fixed resource name because  the limits on name length
- https://github.com/open-cluster-management/backlog/issues/12476
> fixed resource name

- controllers/placementrule/manifestwork.go
- controllers/placementrule/manifestwork_test.go
https://github.com/open-cluster-management/backlog/issues/12106
> delete metrics from match section

- controllers/placementrule/manifestwork.go
> fix matchlist for deleted metrics

- manifests/endpoint-observability/role.yaml
https://github.com/open-cluster-management/backlog/issues/11675
> add permission for endpoint operator to read ocp infrastructure

- api/v1beta2/multiclusterobservability_types.go
- bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
https://github.com/open-cluster-management/backlog/issues/11871
> update the default value for retention configuration

- manifests/base/grafana/dash-k8s-networking-cluster.yaml
related issue: https://github.com/open-cluster-management/backlog/issues/12404
<kbd>![Screen Shot 2021-05-19 at 6 10 39 PM](https://user-images.githubusercontent.com/10394596/118890949-96a2f300-b8cd-11eb-803d-cac3f33fa937.png)</kbd>
<kbd>![Screen Shot 2021-05-19 at 6 10 49 PM](https://user-images.githubusercontent.com/10394596/118891044-9f93c480-b8cd-11eb-89bc-ce25c3205d76.png)</kbd>
> update cluster-networking dashboard for node level metrics

- README.md
- pkg/config/config.go
- pkg/controller/multiclusterobservability/certificates.go
- pkg/controller/multiclusterobservability/multiclusterobservability_controller_test.go
https://github.com/open-cluster-management/backlog/issues/12708
https://github.com/open-cluster-management/backlog/issues/12713
https://github.com/open-cluster-management/backlog/issues/12732
https://github.com/open-cluster-management/backlog/issues/12734
> update svc name due to fixed name

- README.md
Signed-off-by: Song Song Li ssli@redhat.com
> update md format

- bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- config/rbac/mco_role.yaml
- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- controllers/placementrule/hub_info_secret.go
- controllers/placementrule/hub_info_secret_test.go
- controllers/placementrule/manifestwork_test.go
- controllers/placementrule/placementrule_controller.go
- controllers/placementrule/placementrule_controller_test.go
- main.go
- pkg/config/config.go
ref: https://github.com/open-cluster-management/backlog/issues/12478
> add byo certificate support for alertmanager route.

- manifests/base/config/metrics_allowlist.yaml
> add ALERTS to allowlist

- bundle/manifests/core.observatorium.io_observatoria.yaml
- config/crd/bases/core.observatorium.io_observatoria.yaml
ref: open-cluster-management/backlog#12807
> make thanos field option for backcompatibility.

- manifests/base/grafana/dash-acm-clusters-overview.yaml
Related Issues: 
- https://github.com/open-cluster-management/backlog/issues/12406
- https://github.com/open-cluster-management/backlog/issues/10491
<kbd>![Screen Shot 2021-05-26 at 9 37 37 PM](https://user-images.githubusercontent.com/10394596/119752255-a50f8280-be6a-11eb-8fdf-8eae8d8e265e.png)</kbd>
> replace filesystem panel, change topk cpu usage to bar chart

- pkg/rendering/renderer.go
- pkg/rendering/renderer_alertmanager.go
ref: open-cluster-management/backlog#11621
/assign @morvencao
> Fix code error

- docs/MultiClusterObservability-CRD.md
fixed: https://github.com/open-cluster-management/backlog/issues/12918
> Update CRD doc

- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/observatorium.go
- pkg/deploying/deployer.go
> fix infinite reconcile

- pkg/deploying/deployer.go
https://github.com/open-cluster-management/backlog/issues/13041
> fix problem in service update

- manifests/base/alertmanager/alertmanager-proxy.yaml
- manifests/base/alertmanager/alertmanager-statefulset.yaml
- manifests/base/alertmanager/kustomization.yaml
- pkg/rendering/renderer_alertmanager.go
- pkg/util/util.go
try to resolve the git leak issue found in https://github.com/open-cluster-management/backlog/issues/12516
> update cookie secret for alertmanager proxy.

- pkg/config/config.go
> update thanos image

- manifests/endpoint-observability/operator.yaml
- pkg/config/config.go
- pkg/config/config_test.go
https://github.com/open-cluster-management/backlog/issues/13102
> remove default limits for endpoint-metrics-operator and metrics collector

- controllers/placementrule/hub_info_secret.go
- controllers/placementrule/hub_info_secret_test.go
- pkg/config/config.go
ref: https://github.com/open-cluster-management/endpoint-metrics-operator/pull/99#discussion_r647999218
> update hub-info for new format.

- manifests/base/grafana/dash-acm-clusters-overview.yaml
related issue: https://github.com/open-cluster-management/backlog/issues/13157
<kbd>![Screen Shot 2021-06-09 at 5 17 01 PM](https://user-images.githubusercontent.com/10394596/121430815-920ab100-c946-11eb-82ae-b688950c5198.png)</kbd>
> add etcd panel, update default refresh, add 10m refresh

- docs/MoreAboutPersistentStorage.md
Signed-off-by: Joydeep Banerjee <jbanerje@redhat.com>
Will work off comments entered here by @clyang82 @marcolan018 @dockerymick  in https://github.com/open-cluster-management/multicluster-observability-operator/pull/574
> Adding description about PVs used

- pkg/certificates/certificates.go
https://github.com/open-cluster-management/backlog/issues/11159
> renew the server certificate if existing one has different hosts

- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- controllers/multiclusterobservability/multiclusterobservability_status.go
- controllers/multiclusterobservability/multiclusterobservability_status_test.go
- go.mod
- go.sum
Have a separate goroutine to update the MCO status. it is heavy to update the status by triggering a reconcile.
> Status goroutings

- README.md
- manifests/base/proxy/deployment.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controller/multiclusterobservability/certificates.go
- pkg/controller/multiclusterobservability/multiclusterobservability_controller.go
- pkg/controller/multiclusterobservability/multiclusterobservability_controller_test.go
- pkg/controller/multiclusterobservability/multiclusterobservability_status.go
- pkg/controller/multiclusterobservability/observatorium.go
- pkg/controller/multiclusterobservability/observatorium_test.go
- pkg/rendering/renderer.go
https://github.com/open-cluster-management/backlog/issues/12393
https://github.com/open-cluster-management/backlog/issues/13302
> revert PR #553 related change

- docs/MoreAboutPersistentStorage.md
Signed-off-by: Mikela Jackson mdockery@redhat.com
> Redo of PR

- bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- config/rbac/mco_role.yaml
- pkg/util/clustermanagementaddon.go
fix: https://github.com/open-cluster-management/backlog/issues/13394
> update clustermanagementaddon if it's updated during upgrade

- pkg/util/client.go
Fix https://github.com/open-cluster-management/backlog/issues/13262#issuecomment-861522376
Signed-off-by: haoqing0110 <qhao@redhat.com>
> remove CRD ApiextensionsV1beta1 Client

- controllers/multiclusterobservability/multiclusterobservability_status.go
- controllers/multiclusterobservability/multiclusterobservability_status_test.go
fixed: https://github.com/open-cluster-management/backlog/issues/13507
> Use DeepEqual to replace DeepDerivative

- controllers/multiclusterobservability/grafana.go
- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- manifests/base/proxy/ca-bundle.yaml
- manifests/base/proxy/cluster-role.yaml
- manifests/base/proxy/cookie-secret.yaml
- manifests/base/proxy/deployment.yaml
- manifests/base/proxy/kustomization.yaml
- manifests/base/proxy/service.yaml
- pkg/config/config.go
- pkg/rendering/renderer.go
- pkg/rendering/renderer_proxy.go
- pkg/rendering/templates/templates.go
https://github.com/open-cluster-management/backlog/issues/13410
> expose rbac-query-proxy external api from mgmt-ingress to route

- tools/setup-grafana-dev.sh
We have not included the MCO CR as part of the deploy name anymore. so the MCO CR name can be define to comply with kubernetes name convention.
> Remove MCO CR dependecny

- manifests/base/alertmanager/alert_rules.yaml
- manifests/base/config/metrics_allowlist.yaml
Signed-off-by: xavier dharmaiyan <xavier@redhat.com>
>  removed acm from policyreport metric name

- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- controllers/placementrule/placementrule_controller.go
- main.go
- pkg/certificates/cert_controller.go
https://github.com/open-cluster-management/backlog/issues/13263
> start placement & cert controller only when mco CR available

- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- controllers/multiclusterobservability/multiclusterobservability_status.go
- controllers/multiclusterobservability/observatorium.go
- controllers/multiclusterobservability/observatorium_test.go
- controllers/multiclusterobservability/placementrule.go
- controllers/multiclusterobservability/placementrule_test.go
- controllers/placementrule/placementrule_controller.go
- controllers/placementrule/placementrule_controller_test.go
- pkg/certificates/cert_controller.go
- pkg/certificates/cert_controller_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/rendering/renderer.go
- pkg/rendering/renderer_alertmanager.go
- pkg/rendering/renderer_grafana.go
- pkg/rendering/renderer_proxy.go
ref: https://github.com/open-cluster-management/backlog/issues/13247
> Get operand name from environment if any

- pkg/rendering/renderer_proxy.go
https://github.com/open-cluster-management/backlog/issues/13410
> remove hardcoded rbac proxy image

- pkg/util/managedclusteraddon.go
https://github.com/open-cluster-management/backlog/issues/13647
> update managedclusteraddon if it's updated during upgrade flow

- main.go
https://github.com/open-cluster-management/backlog/issues/13732
> move mch out from the filteredcache

- go.mod
- go.sum
- main.go
ref: open-cluster-management/backlog#13732
> upgrade filtered cache to fix duplicated mch instances.

- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- manifests/base/proxy/deployment.yaml
- pkg/certificates/cert_controller.go
- pkg/certificates/certificates.go
- pkg/certificates/certificates_test.go
- pkg/certificates/signer.go
- pkg/rendering/renderer_proxy.go
https://github.com/open-cluster-management/backlog/issues/13247
> reuse existing name for upgrade flow

- controllers/multiclusterobservability/observatorium.go
- pkg/config/config.go
add the following resource request for memcached-exporter :
```
resources:
requests:
cpu: 5m
memory: 50Mi
```
https://github.com/open-cluster-management/backlog/issues/13704
> add resource request for memcached-exporter

- main.go
- pkg/config/config.go
ref: https://github.com/open-cluster-management/backlog/issues/13263
> wait for manifestwork crd before starting manager.

- Makefile.prow
- api/v1beta1/multiclusterobservability_types.go
- api/v1beta1/observabilityaddon_types.go
- api/v1beta2/multiclusterobservability_types.go
- bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- config/manifests/bases/multicluster-observability-operator.clusterserviceversion.yaml
> update mco operator display name in CSV.

- manifests/base/grafana/dash-acm-clusters-overview.yaml
Addressed review comments for etcd dashboard. there still has room to show more columns to be consistent with others
> Update etcd dashboard

- config/manager/manager.yaml
- manifests/base/alertmanager/alertmanager-statefulset.yaml
- manifests/base/grafana/deployment.yaml
- manifests/base/observatorium/operator.yaml
- manifests/base/proxy/deployment.yaml
- pkg/config/config.go
- pkg/config/config_test.go
https://github.com/open-cluster-management/backlog/issues/13617
> update img to latest version

- bundle/manifests/core.observatorium.io_observatoria.yaml
- config/crd/bases/core.observatorium.io_observatoria.yaml
- controllers/multiclusterobservability/observatorium.go
- go.mod
- go.sum
- pkg/rendering/renderer_alertmanager.go
- pkg/util/util.go
ref: https://github.com/open-cluster-management/backlog/issues/13811
> Support configure proxy for thanos and alertmanager

- tests/pkg/tests/observability_install_test.go
- tests/pkg/tests/observability_reconcile_test.go
- tests/pkg/utils/mco_deploy.go
- tests/pkg/utils/utils.go
Signed-off-by: hchenxa <huichen@redhat.com>
used to fix the issue https://github.com/open-cluster-management/backlog/issues/14099
> use label select to get the deployment and statefulset

- Makefile
- cicd-scripts/setup-e2e-tests.sh
fixed: https://github.com/open-cluster-management/backlog/issues/14157
> Pass images

- tools/setup-grafana-dev.sh
Get storage class from PVC, avoid the special PVC is not exist.
https://github.com/open-cluster-management/backlog/issues/14139
> fix grafana-dev upgrade issue

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
Related Issue: https://github.com/open-cluster-management/backlog/issues/9246
> fix overestimation panel on overview dashboard and add required pod phase metric

- tests/pkg/tests/observability_default_config_test.go
- tests/pkg/tests/observability_reconcile_test.go
- tests/pkg/utils/mco_deploy.go
Signed-off-by: hchenxa <huichen@redhat.com>
> skip the cases when MCO was customized installation

- manifests/base/proxy/deployment.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controller/multiclusterobservability/certificates.go
- pkg/controller/multiclusterobservability/multiclusterobservability_controller.go
- pkg/controller/multiclusterobservability/multiclusterobservability_controller_test.go
- pkg/controller/multiclusterobservability/multiclusterobservability_status.go
- pkg/controller/multiclusterobservability/observatorium.go
- pkg/controller/multiclusterobservability/observatorium_test.go
- pkg/controller/multiclusterobservability/placementrule.go
- pkg/controller/multiclusterobservability/placementrule_test.go
- pkg/controller/placementrule/placementrule_controller.go
- pkg/controller/placementrule/placementrule_controller_test.go
- pkg/rendering/renderer.go
https://github.com/open-cluster-management/backlog/issues/12393
refer to these PRs:
- https://github.com/open-cluster-management/multicluster-observability-operator/pull/605
- https://github.com/open-cluster-management/multicluster-observability-operator/pull/623
> set operand name from environment if any

- tests/pkg/tests/observability-e2e-test_suite_test.go
- tests/pkg/tests/observability_advanced_config_test.go
- tests/pkg/tests/observability_alert_test.go
- tests/pkg/tests/observability_cert_renew_test.go
- tests/pkg/tests/observability_endpoint_preserve_test.go
- tests/pkg/tests/observability_observatorium_preserve_test.go
- tests/pkg/tests/observability_reconcile_test.go
- tests/pkg/tests/observability_retention_test.go
- tests/pkg/utils/mco_deploy.go
- tests/pkg/utils/mco_deployments.go
- tests/pkg/utils/mco_statefulset.go
Signed-off-by: hchenxa <huichen@redhat.com>
> update to use label selector

- bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
ref: https://github.com/open-cluster-management/backlog/issues/14296
> Update csv to add operators.operatorframework.io/internal-objects annotation

- README.md
> empty pr to trigger build

- operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
ref: open-cluster-management/backlog#14296
fix this issue in main branch and release-2.4
> Update csv to add operators.operatorframework.io/internal-objects annotations

- tools/setup-grafana-dev.sh
https://github.com/open-cluster-management/backlog/issues/14139
> fetch pod name via label

- manifests/base/proxy/deployment.yaml
- pkg/config/config.go
- pkg/controller/multiclusterobservability/observatorium.go
https://github.com/open-cluster-management/backlog/issues/14383
> fix observatorium name issue

- Makefile
- README.md
- cicd-scripts/customize-mco.sh
- cicd-scripts/run-e2e-tests.sh
- cicd-scripts/setup-e2e-tests.sh
- examples/minio/kustomization.yaml
- examples/minio/minio-secret.yaml
- tests/pkg/tests/observability_install_test.go
- tests/pkg/tests/observability_uninstall_test.go
- tests/pkg/utils/mco_dashboard.go
- tests/pkg/utils/mco_metric.go
ref: https://github.com/open-cluster-management/backlog/issues/14323
> Adopt ocm-e2e-clusterpool

- operators/endpointmetrics/main.go
- operators/multiclusterobservability/main.go
> enable logging dev mode.

- tests/pkg/tests/observability_addon_test.go
- tests/pkg/tests/observability_advanced_config_test.go
- tests/pkg/utils/mco_deploy.go
Signed-off-by: hchenxa <huichen@redhat.com>
> Ensure the sts or deployment created and add null check for advancedconfig 

- tools/switch-to-grafana-admin.sh
if username contains the number sign '#', we need to replace it with '%23' due to use it in URL parameters
https://github.com/open-cluster-management/backlog/issues/14390
> fix iam name

- cicd-scripts/run-e2e-tests.sh
- collectors/metrics/pkg/metricfamily/whitelist.go
- collectors/metrics/pkg/metricfamily/whitelist_test.go
- collectors/metrics/test/integration/manifests/thanos-api.yaml
- collectors/metrics/test/integration/manifests/thanos-service.yaml
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_resource.go
- tests/pkg/tests/observability-e2e-test_suite_test.go
- tests/pkg/tests/observability_addon_test.go
- tests/pkg/tests/observability_advanced_config_test.go
- tests/pkg/tests/observability_alert_test.go
- tests/pkg/tests/observability_cert_renew_test.go
- tests/pkg/tests/observability_custom_dashboards_test.go
- tests/pkg/tests/observability_default_config_test.go
- tests/pkg/tests/observability_endpoint_preserve_test.go
- tests/pkg/tests/observability_grafana_test.go
- tests/pkg/tests/observability_install_test.go
- tests/pkg/tests/observability_manifestwork_test.go
- tests/pkg/tests/observability_metricslist_test.go
- tests/pkg/tests/observability_observatorium_preserve_test.go
- tests/pkg/tests/observability_reconcile_test.go
- tests/pkg/tests/observability_retention_test.go
- tests/pkg/tests/observability_uninstall_test.go
- tests/pkg/utils/client.go
- tests/pkg/utils/mco_cert_secret.go
- tests/pkg/utils/mco_deploy.go
- tests/pkg/utils/options.go
- tests/pkg/utils/utils.go
https://github.com/open-cluster-management/backlog/issues/13132
> remove sensitive words

- operators/endpointmetrics/Dockerfile
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go
- operators/multiclusterobservability/Dockerfile
- operators/multiclusterobservability/controllers/placementrule/hub_info_secret.go
- operators/multiclusterobservability/controllers/placementrule/hub_info_secret_test.go
- operators/multiclusterobservability/pkg/certificates/certificates.go
- operators/multiclusterobservability/pkg/config/config.go
- operators/multiclusterobservability/pkg/config/config_test.go
- operators/pkg/config/hub_info.go
> move hubInfo to common struct for operators.

- operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-cluster-rsrc-use.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-apiserver.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-etcd.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-networking-cluster.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-node-rsrc-use.yaml
Related issue: https://github.com/open-cluster-management/backlog/issues/14419
> update label refresh option

- collectors/metrics/pkg/simulator/simulator.go
- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/controllers/placementrule/obsaddon.go
- operators/multiclusterobservability/controllers/placementrule/role.go
- operators/multiclusterobservability/pkg/certificates/cert_controller.go
- operators/multiclusterobservability/pkg/certificates/certificates.go
- operators/multiclusterobservability/pkg/config/config.go
- operators/pkg/config/hub_info.go
- tests/pkg/utils/mco_dashboard.go
- tests/pkg/utils/mco_deploy.go
- tests/pkg/utils/mco_deployments.go
- tests/pkg/utils/mco_metric.go
> fix code smell and vulnerabilities

- Makefile
- operators/multiclusterobservability/Dockerfile
- operators/multiclusterobservability/Makefile
This PR fixes:
- build from root directory
- create dedicated ut target for each component
- add missing variable
> fix build and ut from root directory.

- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/multiclusterobservability/pkg/config/config.go
- tests/pkg/utils/mco_dashboard.go
- tests/pkg/utils/mco_metric.go
- remove unused code
- ignore gosec 
> Fix vulnerabilities

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/pkg/config/config.go
ref: https://github.com/open-cluster-management/backlog/issues/14817
> Should not clean image manifests after delete mco cr

- operators/endpointmetrics/main.go
- operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- operators/multiclusterobservability/config/manager/manager.yaml
- operators/multiclusterobservability/main.go
- operators/multiclusterobservability/manifests/endpoint-observability/operator.yaml
- operators/pkg/util/util.go
> Enable pprof

- examples/mco/e2e/v1beta2/observability.yaml
- operators/multiclusterobservability/manifests/base/observatorium/operator.yaml
- operators/multiclusterobservability/manifests/endpoint-observability/operator.yaml
- operators/multiclusterobservability/pkg/config/config.go
- tests/pkg/tests/observability_addon_test.go
- tests/pkg/utils/mco_deploy.go
https://github.com/open-cluster-management/backlog/issues/14901
> update components resource request

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
ref: https://github.com/open-cluster-management/backlog/issues/14817
> make mco wait for mch ready before reconciling and reading image manifests

- docs/setup-ocs-for-object-storage.md
- tests/grafana-dev-test.sh
- tests/pkg/tests/observability_addon_test.go
- tests/pkg/tests/observability_grafana_dev_test.go
https://github.com/open-cluster-management/backlog/issues/14628
> enable some e2e test case

- collectors/metrics/pkg/metricsclient/metricsclient.go
ref: https://github.com/open-cluster-management/backlog/issues/11356
> change MinVersion to tls.VersionTLS13

- proxy/cmd/main.go
- proxy/deploy/deployment.yaml
- proxy/pkg/proxy/tls.go
> merge missing commits from rbac-query-proxy repo

- cicd-scripts/run-e2e-tests.sh
- cicd-scripts/setup-e2e-tests.sh
this PR tries to fix the e2e setup stript.
> fix e2e setup script.

- controllers/multiclusterobservability/multiclusterobservability_controller.go
- controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- controllers/multiclusterobservability/observatorium_test.go
- controllers/placementrule/placementrule_controller.go
cherrypick https://github.com/open-cluster-management/multicluster-observability-operator/pull/688 to release-2.3
> cherrypick 688 to fix image manifest read issue.

- manifests/base/grafana/deployment.yaml
ref: https://github.com/open-cluster-management/backlog/issues/13382
> Pass POD_NAMESPACE in

- collectors/metrics/pkg/metricsclient/metricsclient.go
> Revert "change MinVersion to tls.VersionTLS13"

- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go
- operators/endpointmetrics/manifests/prometheus/kubernetes-monitoring-alertingrules.yaml
- operators/endpointmetrics/manifests/prometheus/kustomization.yaml
- operators/endpointmetrics/manifests/prometheus/prometheus-config.yaml
- operators/endpointmetrics/manifests/prometheus/prometheus-statefulset.yaml
- operators/endpointmetrics/pkg/rendering/renderer.go
- operators/endpointmetrics/pkg/rendering/renderer_test.go
ref: open-cluster-management/backlog#15086
> support alert forward from *KS.

- collectors/metrics/pkg/forwarder/forwarder.go
> add sonar scan exception

- examples/metrics/allowlist/custom-metrics-allowlist.yaml
- tests/pkg/tests/observability_grafana_test.go
- tests/pkg/tests/observability_metrics_test.go
- tests/pkg/utils/mco_managedcluster.go
https://github.com/open-cluster-management/backlog/issues/15085
> e2e for *ks support

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_status.go
fix: https://github.com/open-cluster-management/backlog/issues/15667
> fix stopCheckReady receive signal hang for status update.

- operators/endpointmetrics/manifests/prometheus/prometheus-clusterRole.yaml
- operators/endpointmetrics/manifests/prometheus/prometheus-config.yaml
- operators/multiclusterobservability/manifests/endpoint-observability/role.yaml
https://github.com/open-cluster-management/backlog/issues/15708
> update service discovery for metrics endpoints in kubelet

- operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- operators/multiclusterobservability/config/manager/manager.yaml
> increase the resource limit for mco.

- tools/simulator/metrics-collector/README.md
- tools/simulator/metrics-collector/setup-metrics-collector.sh
> allow simulated metrics-collectors be scheduled to master node.

- go.mod
- go.sum
- operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- operators/multiclusterobservability/config/rbac/mco_role.yaml
- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/main.go
- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
- operators/multiclusterobservability/manifests/base/observatorium/kustomization.yaml
- operators/multiclusterobservability/manifests/base/observatorium/prometheus_role.yaml
- operators/multiclusterobservability/manifests/base/observatorium/prometheus_role_binding.yaml
- operators/multiclusterobservability/pkg/servicemonitor/sm_controller.go
- operators/multiclusterobservability/pkg/servicemonitor/sm_controller_test.go
https://github.com/open-cluster-management/backlog/issues/15775
https://github.com/open-cluster-management/backlog/issues/10668
> support all nonocp platforms & observatorium metrics support

- tests/benchmark/setup-metrics-collector.sh
> remove resources from simulated metrics-collector.

- collectors/metrics/Dockerfile
- go.mod
- go.sum
- loaders/dashboards/Dockerfile
- operators/endpointmetrics/Dockerfile
- operators/multiclusterobservability/Dockerfile
- proxy/Dockerfile
- tests/Dockerfile
https://github.com/open-cluster-management/backlog/issues/15474
>  Update golang to 1.17

- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-apiserver.yaml
Issue: https://github.com/open-cluster-management/backlog/issues/14307
> updated api server latency panel labels

- go.mod
- go.sum
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go
- operators/endpointmetrics/controllers/status/status_controller_test.go
- operators/endpointmetrics/pkg/util/lease.go
- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
- operators/multiclusterobservability/controllers/placementrule/status.go
- operators/multiclusterobservability/controllers/placementrule/status_test.go
- operators/multiclusterobservability/main.go
- operators/multiclusterobservability/pkg/certificates/approver.go
- operators/multiclusterobservability/pkg/certificates/approver_test.go
- operators/multiclusterobservability/pkg/certificates/cert_agent.go
- operators/multiclusterobservability/pkg/certificates/cert_agent_test.go
- operators/multiclusterobservability/pkg/certificates/cert_controller.go
- operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
- operators/multiclusterobservability/pkg/util/clustermanagementaddon_test.go
- operators/multiclusterobservability/pkg/util/managedclusteraddon.go
- operators/multiclusterobservability/pkg/util/managedclusteraddon_test.go
- proxy/cmd/main.go
- proxy/pkg/util/util.go
- tests/pkg/tests/observability_install_test.go
we need to replace the addon-framework pkg and api pkg due to this issue: https://github.com/open-cluster-management/backlog/issues/15912
> Fix addon-framework issue

- operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
fix: https://github.com/open-cluster-management/backlog/issues/16191
> Remove . to make it works in grafana8

- manifests/base/grafana/deployment.yaml
- pkg/config/config.go
ref: https://github.com/open-cluster-management/backlog/issues/16190
> fetch original images from quay.io

- operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
Add description in optimization overview to align with cluster overview
> Add description in optimization overview

- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
- operators/endpointmetrics/manifests/prometheus/prometheus-config.yaml
- operators/endpointmetrics/manifests/prometheus/prometheus-statefulset.yaml
- operators/endpointmetrics/pkg/rendering/renderer.go
- operators/endpointmetrics/pkg/rendering/renderer_test.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
- operators/multiclusterobservability/pkg/config/config.go
- operators/pkg/config/config.go
https://github.com/open-cluster-management/backlog/issues/16110
> in non-ocp, disable useless metrics scrape in prometheus

- operators/multiclusterobservability/pkg/config/config.go
> update memcached img

- operators/multiclusterobservability/pkg/webhook/webhook_controller.go
ref: https://sonarcloud.io/project/issues?branch=release-2.4&id=open-cluster-management_multicluster-observability-operator&open=AXvxu8vmNFMEFuLhDGvg&resolved=false&types=VULNERABILITY
> fix sonar scan issues for webhook controller.

- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server-cluster.yaml
Issues: https://github.com/open-cluster-management/backlog/issues/15909 & https://github.com/open-cluster-management/backlog/issues/16201.
The task for updating the dashboard labels: https://github.com/open-cluster-management/backlog/issues/16212.
Related to PR: https://github.com/open-cluster-management/rhacm-docs/pull/2668.
> updated service-level overview dashboard label and descriptions

- cicd-scripts/run-e2e-tests.sh
- examples/mco/e2e/v1beta1/observability-v1beta1-to-v1beta2-golden.yaml
- go.mod
- go.sum
- operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
- operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
- operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_observabilityaddons.yaml
- operators/multiclusterobservability/config/crd/bases/core.observatorium.io_observatoria.yaml
- operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml
- operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
- operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-cluster-rsrc-use.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-apiserver.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-etcd.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-node-rsrc-use.yaml
- operators/multiclusterobservability/manifests/endpoint-observability/observability.open-cluster-management.io_observabilityaddon_crd.yaml
https://github.com/open-cluster-management/backlog/issues/16108
> update default scrape interval to 5 minutes

- operators/multiclusterobservability/manifests/base/alertmanager/alert_rules.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
ref: https://github.com/open-cluster-management/backlog/issues/15916
> use topk for cpu/memory optimization/utilization panels.

- operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
> fix no data in grafana cluster overview dashboard

- cicd-scripts/setup-e2e-tests.sh
- tests/pkg/tests/observability_addon_test.go
- tests/pkg/tests/observability_install_test.go
- tests/pkg/utils/mco_oba.go
fixed: https://github.com/open-cluster-management/backlog/issues/16007
> Check OBA and managedclusteraddon are ready for all managed clusters before verify metrics etc

- operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
ref: https://github.com/open-cluster-management/backlog/issues/15916
> Combine to use one query per panel

- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
https://github.com/open-cluster-management/backlog/issues/15917
> add ut for custom registry

- operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
ref: https://github.com/open-cluster-management/backlog/issues/16538
> fix row missing for iks in apiserver panel.

- tests/e2e/minio/minio-deployment.yaml
> update minio image used2 in e2e

- operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
ref: https://github.com/open-cluster-management/backlog/issues/16541
> Correct the deepEqual logic

- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
https://github.com/open-cluster-management/backlog/issues/16652
> fix customized registry issue

- tests/pkg/utils/mco_managedcluster.go
https://github.com/open-cluster-management/backlog/issues/16692
> return error when no managedcluster

- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-etcd.yaml
https://github.com/open-cluster-management/backlog/issues/16686
> update label "cluster" to "Cluster" in dashboards for consistent naming

- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
ref: https://github.com/open-cluster-management/backlog/issues/16240
> fix managedcluster resources cleanup for hive provisioned cluster detach.

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/controllers/multiclusterobservability/storageversionmigration.go
- operators/multiclusterobservability/controllers/multiclusterobservability/storageversionmigration_test.go
fixed https://github.com/open-cluster-management/backlog/issues/15798
> clean up mco related resource when uninstall mco cr

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-apiserver.yaml
ref: https://github.com/open-cluster-management/backlog/issues/17656
> Update apiserver_request_duration_seconds recording rules

- tests/pkg/tests/observability-e2e-test_suite_test.go
- tests/pkg/tests/observability_install_test.go
- tests/pkg/tests/observability_route_test.go
- tests/pkg/utils/mco_router_ca.go
Fix https://github.com/open-cluster-management/backlog/issues/17505
Fix https://github.com/open-cluster-management/backlog/issues/17504
> add route api test

- tests/pkg/utils/client.go
- tests/pkg/utils/mco_deployments.go
- tests/pkg/utils/mco_oba.go
Add some log to trace the oba test error: https://app.travis-ci.com/github/open-cluster-management/canary/jobs/545297690#L578
ref: https://github.com/open-cluster-management/backlog/issues/17660
> add log for oba and managedcluster test

- tools/simulator/alert-forward/Dockerfile
- tools/simulator/alert-forward/README.md
- tools/simulator/alert-forward/alerts.json
- tools/simulator/alert-forward/clean-alert-forwarder.sh
- tools/simulator/alert-forward/deployment.yaml
- tools/simulator/alert-forward/main.go
- tools/simulator/alert-forward/setup-alert-forwarder.sh
> enhance the alert-forwarder for simulator.

- tools/simulator/alert-forward/README.md
- tools/simulator/alert-forward/deployment.yaml
fix: https://github.com/open-cluster-management/backlog/issues/17855
> fix git leaks.

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Related Issue: https://github.com/open-cluster-management/backlog/issues/17736
> Updated slo recording rule metric label filter

- docs/MultiClusterObservability-CRD.md
- operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
- operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
fix https://github.com/open-cluster-management/multicluster-observability-operator/issues/637
> fix invalid link

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Related Issue: https://github.com/open-cluster-management/backlog/issues/17736
> [release-2.4] updated slo recording rule metric label filter

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
> fix invalid recording rule.

- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server.yaml
Related issue: https://github.com/open-cluster-management/backlog/issues/17379
> [release-2.4] updated slo dashboard panel labels

- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server.yaml
Related issue: https://github.com/open-cluster-management/backlog/issues/17379
> updated slo dashboard panel labels

- tests/pkg/tests/observability_addon_test.go
- tests/pkg/tests/observability_metrics_test.go
> fix flaky testings in KinD.

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
> fix invalid expression

- operators/multiclusterobservability/controllers/placementrule/customize_img.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
resolve: https://github.com/open-cluster-management/backlog/issues/18143
> fix concurrent map read write.

- tests/pkg/utils/client.go
> use kubecontext for managedcluster

- tools/simulator/metrics-collector/README.md
- tools/simulator/metrics-collector/generate-metrics-data.sh
ref: https://github.com/open-cluster-management/backlog/issues/18241
> small fix for metrics-collector simulator.

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/controllers/placementrule/role.go
ref: https://github.com/open-cluster-management/backlog/issues/18299
> update label for rback resource deletion.

- go.mod
- go.sum
- operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
- operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
- operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/config/crd/bases/core.observatorium.io_observatoria.yaml
- operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
[open-cluster-management/backlog#18022](https://github.com/open-cluster-management/backlog/issues/18022)
> support custom tenant header and write backend

- go.mod
- go.sum
- operators/endpointmetrics/manifests/prometheus/kubernetes-monitoring-alertingrules.yaml
- tests/pkg/tests/observability_alert_test.go
- tests/pkg/utils/mco_managedcluster.go
- tests/pkg/utils/utils.go
> [release-2.4] add e2e case for alert forward from managed clusters.

- tools/simulator/metrics-collector/README.md
- tools/simulator/metrics-collector/generate-metrics-data.sh
ref: open-cluster-management/backlog#13360
> support ocp 3.11 for metrics-collector simulator.

- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-summary-by-node-ocp311.yaml
ref: https://github.com/stolostron/backlog/issues/18962
> fix missing node role in ocp311 dashboard.

- REMEDIATE.md
> trigger build

- README.md
> empty to trigger build

- tests/pkg/tests/observability_addon_test.go
https://github.com/stolostron/backlog/issues/19570
> also check metrics-collector pod status when disable obs

- tests/pkg/tests/observability_addon_test.go
https://github.com/stolostron/backlog/issues/19570
> also check metrics-collector pod status when disable obs(2.4)

- .github/workflows/go-package-update.yml
Related issue: https://github.com/stolostron/backlog/issues/18940
> updated github workflow

- .github/workflows/go-package-update.yml
> fix: updated github workflow

- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- tests/pkg/tests/observability_addon_test.go
- tests/pkg/utils/mco_oba.go
related: [#19015](https://github.com/stolostron/backlog/issues/19015)
> 2.4 - delete obs addon when enableMetrics is set to false

- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- tests/pkg/tests/observability_addon_test.go
- tests/pkg/utils/mco_oba.go
related: [#19015](https://github.com/stolostron/backlog/issues/19015)
> delete obs addon when enableMetrics is set to false

- .github/workflows/go-package-update.yml
> added continue on error to debug gh actions

- controllers/placementrule/placementrule_controller.go
related: [#19634](https://github.com/stolostron/backlog/issues/19634)
> delete managed components when enableMetrics=false bugzilla 203197

- proxy/pkg/util/util.go
https://github.com/stolostron/backlog/issues/19918
> rbac proxy can handle query from POST request

- proxy/pkg/util/util.go
> fix error reported by sonar

- proxy/pkg/util/util.go
https://github.com/stolostron/backlog/issues/19919
cherry-pick for pr https://github.com/stolostron/multicluster-observability-operator/pull/900
> handle query rewrite in POST request

- .github/workflows/go-package-dependencies-update.yml
> Fixed sed action within gh action automation

- tests/format-results.sh
- tests/pkg/tests/observability_addon_test.go
- tests/pkg/tests/observability_alert_test.go
- tests/pkg/tests/observability_certrenew_test.go
- tests/pkg/tests/observability_config_test.go
- tests/pkg/tests/observability_dashboard_test.go
- tests/pkg/tests/observability_endpoint_preserve_test.go
- tests/pkg/tests/observability_grafana_dev_test.go
- tests/pkg/tests/observability_grafana_test.go
- tests/pkg/tests/observability_manifestwork_test.go
- tests/pkg/tests/observability_metrics_test.go
- tests/pkg/tests/observability_observatorium_preserve_test.go
- tests/pkg/tests/observability_reconcile_test.go
- tests/pkg/tests/observability_retention_test.go
- tests/pkg/tests/observability_route_test.go
> fix mismatch capital in testing label.

- .github/dependabot.yml
This PR will enable the GitHub dependabot for this project.
> Enabled Github Dependabot

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Related issue: https://github.com/stolostron/backlog/issues/19141.
> Added collect rules to metrics allowlist

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- operators/multiclusterobservability/pkg/certificates/certificates.go
- operators/multiclusterobservability/pkg/config/config.go
- operators/multiclusterobservability/pkg/util/backuputil.go
Related: [#18324](https://github.com/stolostron/backlog/issues/18324)
> Add Backup labels to observability resources

- examples/dashboards/alert-dashboards/README.md
- examples/dashboards/alert-dashboards/alert-analysis.yaml
- examples/dashboards/alert-dashboards/alerts-by-cluster.yaml
- examples/dashboards/alert-dashboards/clusters-by-alert.yaml
- examples/dashboards/alert-dashboards/kustomization.yaml
Signed-off-by: Joydeep Banerjee <jbanerje@redhat.com>
Adding experimental alert dashboards that we have been using internally in the team
> adding experimental alert dashboards

- operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- operators/multiclusterobservability/config/rbac/mco_role.yaml
- operators/multiclusterobservability/main.go
- operators/multiclusterobservability/manifests/base/alertmanager/kustomization.yaml
- operators/multiclusterobservability/manifests/base/alertmanager/prometheusrule.yaml
- tests/run-in-kind/req_crds/prometheusrule-crd.yaml
https://github.com/stolostron/backlog/issues/20301
> add the PrometheusRule for remote write alert

- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
> Rename rules to recording_rules, update collect_rules schema

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
Related issue: https://github.com/stolostron/backlog/issues/19142
> Added recording rules to metrics allowlist & refactored Grafana dashboards

- collectors/metrics/cmd/metrics-collector/main.go
- collectors/metrics/pkg/collectrule/evaluator.go
- collectors/metrics/pkg/collectrule/evaluator_test.go
- collectors/metrics/pkg/forwarder/forwarder.go
https://github.com/stolostron/backlog/issues/20602
> support dynamic collect in metrics-collector

- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
Related issue: https://github.com/stolostron/backlog/issues/19142
> Added observatorium-dynamic datasource to dashboards

- collectors/metrics/pkg/forwarder/forwarder.go
- collectors/metrics/pkg/metricsclient/metricsclient.go
- examples/gen.go
- operators/endpointmetrics/controllers/observabilityendpoint/match_evaluator.go
- operators/endpointmetrics/controllers/observabilityendpoint/match_evaluator_test.go
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/pkg/config/types.go
fixe: https://github.com/stolostron/backlog/issues/20601
> support dynamic metrics collection in endpoint operator

- operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/pkg/config/config.go
> Set dynamic datasource interval to default when collect rules are empty

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
Related issue: https://github.com/stolostron/backlog/issues/19142
> Added missing recording rules

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
> update the collect rules based on resourcequota

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
> update promql to get cluster memory usage

- REMEDIATE.md
> noop to trigger build

- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
> disable metrics collection which defined in collect rule

- operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
- operators/multiclusterobservability/pkg/config/config.go
> Support SNO collect rules only

- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
Related issue: https://github.com/stolostron/backlog/issues/19142.
> Reverted to original datasource Grafana

- OWNERS
> Add additional approvers

- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
- operators/pkg/config/types.go
> update collect rules schema

- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
> set dynamic interval

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/pkg/certificates/certificates.go
- operators/multiclusterobservability/pkg/config/config.go
> add missing backup labels

- operators/multiclusterobservability/pkg/config/obj_storage_conf_test.go
- operators/multiclusterobservability/pkg/config/s3_conf.go
ref: https://github.com/stolostron/backlog/issues/20660
> Remove access_key and secret_key validation

- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
> update collect rule to use matches

- operators/pkg/util/obj_compare.go
- operators/pkg/util/obj_compare_test.go
fix: https://github.com/stolostron/backlog/issues/21127
> handle crd comparison of different api versions: v1 and v1beta1

- operators/multiclusterobservability/pkg/config/config.go
- operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
https://github.com/stolostron/backlog/issues/21045
> use absolute url for grafana link

- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-summary-by-node-ocp311.yaml
ref: https://github.com/stolostron/backlog/issues/21179
> hide nodetype selector for "summary by node" dashboard.

- collectors/metrics/pkg/collectrule/evaluator.go
- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
> update collect rule, fix collect bug

- operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- operators/multiclusterobservability/config/rbac/mco_role.yaml
- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
https://github.com/stolostron/backlog/issues/21279
> add permission for finalizers of addons

- REMEDIATE.md
> trigger build of all images for openssl fix

- tests/pkg/tests/observability_addon_test.go
- tests/pkg/tests/observability_alert_test.go
- tests/pkg/tests/observability_metrics_test.go
- tests/pkg/utils/mco_metric.go
also add more detailed info in the logs of this test case
> fix error in test case to verify metrics in allowlist

- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
https://github.com/stolostron/backlog/issues/21438
> add backup label to WriteStorage secrets

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
> removed endpoint filter from pod container recording rules

- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
- operators/multiclusterobservability/pkg/certificates/certificates.go
- operators/multiclusterobservability/pkg/util/backuputil.go
https://github.com/stolostron/backlog/issues/21587
> add backup label to cert secrets in upgrade path

- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
https://github.com/stolostron/backlog/issues/21624
> watch default allowlist, fix for 2.4

- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
https://github.com/stolostron/backlog/issues/21624
> watch default allowlist

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Signed-off-by: marcolan018 [<llan@redhat.com>](mailto:llan@redhat.com)
https://github.com/stolostron/backlog/issues/21541
> Memory metrics fix

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/pkg/config/config.go
> add backup label to image pull secret

- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-capacity-planning-ocp311.yaml
ref: https://github.com/stolostron/backlog/issues/21882
> fix duplicated time series for join in ocp311 dashboard.

- go.mod
https://github.com/stolostron/backlog/issues/21833
> upgrade github.com/hashicorp/consul

- tools/README.md
Signed-off-by: Joydeep Banerjee <jbanerje@redhat.com>
Minor updates. I tested a non-kubeadmin user to be able to assume grafana admin role - so added an explicit example
> clarifying users who can run the script

- REMEDIATE.md
Related issues: https://github.com/stolostron/backlog/issues/22206, https://github.com/stolostron/backlog/issues/22122, & https://github.com/stolostron/backlog/issues/22085
> [release-2.4] Triggering image rebuild

- REMEDIATE.md
Related issues: https://github.com/stolostron/backlog/issues/22206, https://github.com/stolostron/backlog/issues/22122, & https://github.com/stolostron/backlog/issues/22085
> [release-2.5] Triggering image rebuild

- README.md
- REMEDIATE.md
Related issue: https://github.com/stolostron/backlog/issues/22122
> [release-2.5] retrigger image build

- operators/multiclusterobservability/pkg/config/config.go
https://github.com/stolostron/backlog/issues/22470
> upgrade to use latest image for thanos-receiver-controller

- operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
https://github.com/stolostron/backlog/issues/20460
> support proxy settings in alertmanager(release-2.4)

- operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
https://github.com/stolostron/backlog/issues/22605
> update peer value in alertmanager sts to handle upgrade case(2.4)

- README.md
Related issue: https://github.com/stolostron/backlog/issues/22158
> [release-2.3] Triggering image rebuild

- operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
https://github.com/stolostron/backlog/issues/22605
> update the peer value in alertmanager sts to handle upgrade case(2.5)

- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods-ocp311.yaml
https://github.com/stolostron/backlog/issues/22676
> rename the value with correct metrics name in network panel

- operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
fix: https://github.com/stolostron/backlog/issues/22605
> update the peer value in alertmanager sts to handle upgrade case

- operators/multiclusterobservability/manifests/base/grafana/deployment.yaml
fix: https://github.com/stolostron/backlog/issues/24311
> update cookie related setting in grafana's oauth-proxy

- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
> Adopt to OCP 4.11 service account changes

- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- operators/multiclusterobservability/manifests/endpoint-observability/observability.open-cluster-management.io_observabilityaddon_crd.yaml
- operators/multiclusterobservability/manifests/endpoint-observability/observability.open-cluster-management.io_observabilityaddon_v1beta1_crd.yaml
https://github.com/stolostron/backlog/issues/23650
> inject different allowlist content based on different cluster type

- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
> release 2.5: Adopt to OCP 4.11 service account changes

- operators/pkg/util/util_test.go
Signed-off-by: siddharthrajaraman <srajaram@redhat.com>
> decode error checking

- README.md
> [release-2.7] Triggering image rebuild

- REMEDIATE.md
- collectors/metrics/README.md
- loaders/dashboards/README.md
- operators/endpointmetrics/README.md
- proxy/README.md
> [release-2.7] Triggering image rebuild (2)

- operators/pkg/deploying/deployer.go
https://github.com/stolostron/backlog/issues/25340
> handle StringData in updateSecret function

- operators/pkg/deploying/deployer.go
https://github.com/stolostron/backlog/issues/25340
> handle StringData in UpdateSecret function in main branch(release 2.7)

- tests/pkg/utils/utils.go
fix: https://github.com/stolostron/backlog/issues/25323
> wait 5 minutes for IntegrityChecking in e2e

- REMEDIATE.md
> Rebuild with new base image

- examples/dashboards/alert-dashboards/README.md
- proxy/examples/rbac/README.md
- tests/README.md
- tests/benchmark/README.md
- tools/README.md
- tools/setup-grafana-dev.sh
- tools/simulator/metrics-collector/README.md
Related issue: https://github.com/stolostron/backlog/issues/24574
> [release-2.7] Updated how to design a Grafana dashboard docs

- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
> support uwl allowlist

- operators/multiclusterobservability/pkg/servicemonitor/sm_controller.go
https://github.com/stolostron/backlog/issues/25564
> fix OnUpdate() in smController in 2.5

- operators/multiclusterobservability/pkg/servicemonitor/sm_controller.go
https://github.com/stolostron/backlog/issues/25564
> fix OnUpdate() in smController in 2.6

- README.md
Signed-off-by: Brian Smith briansmi@redhat.com
> Trigger downstream snapshot for 2.7

- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
> add namespace label for the uwl entries from custom allowlist

- collectors/metrics/pkg/forwarder/forwarder.go
- collectors/metrics/pkg/status/status.go
- collectors/metrics/pkg/status/status_test.go
https://issues.redhat.com/browse/ACM-1930
> update addon status from more than one collectors

- collectors/metrics/cmd/metrics-collector/main.go
- collectors/metrics/pkg/forwarder/forwarder.go
- collectors/metrics/pkg/forwarder/forwarder_test.go
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
https://issues.redhat.com/browse/ACM-1789
> query metrics from thanos-querier

- collectors/metrics/pkg/status/status.go
> enhancement in status report of metrics collector

- go.mod
> fix error in ds build

- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
> log mainfest size if size exceeds limit

- collectors/metrics/cmd/metrics-collector/main.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_resource.go
- operators/endpointmetrics/manifests/prometheus/prometheus-resource.yaml
- operators/endpointmetrics/pkg/rendering/renderer.go
- operators/multiclusterobservability/controllers/placementrule/hub_info_secret.go
- operators/multiclusterobservability/controllers/placementrule/hub_info_secret_test.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
- operators/multiclusterobservability/controllers/placementrule/mco_predicate.go
- operators/multiclusterobservability/controllers/placementrule/mco_predicate_test.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
- operators/multiclusterobservability/pkg/config/config.go
- operators/pkg/config/config.go
- operators/pkg/deploying/deployer.go
- operators/pkg/deploying/deployer_test.go
- tests/pkg/tests/observability_alert_test.go
> [release-2.6] ability to disable alert forwarding

- collectors/metrics/pkg/status/status.go
> enhancement on addon status display

- .gitignore
- collectors/metrics/pkg/forwarder/forwarder.go
- collectors/metrics/pkg/metricfamily/hypershift_transformer.go
- collectors/metrics/pkg/metricfamily/label.go
- collectors/metrics/pkg/metricsclient/metricsclient.go
Signed-off-by: Nathaniel Graham <ngraham@redhat.com>
> Blank labels removed and appended ones done Lexicographically

- cicd-scripts/setup-e2e-tests.sh
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_resource.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_resource_test.go
- tests/pkg/utils/utils.go
fix issue: https://issues.redhat.com/browse/ACM-2291
> update the namespace for hypershift hosted cluster's res

- proxy/cmd/main.go
- proxy/pkg/util/util.go
- proxy/pkg/util/util_test.go
Related issue: https://issues.redhat.com/browse/ACM-2460
> Fixed issue with ignorelist not properly updating in memory

- collectors/metrics/pkg/status/status.go
- operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- proxy/cmd/main.go
- proxy/pkg/util/user_project.go
- proxy/pkg/util/user_project_test.go
- proxy/pkg/util/util.go
fix https://issues.redhat.com/browse/ACM-2498, https://issues.redhat.com/browse/ACM-2544 and https://issues.redhat.com/browse/ACM-1729
> fix problems; update memory limit for mco

- operators/multiclusterobservability/pkg/config/config.go
https://issues.redhat.com/browse/ACM-1731
> add log when detecting custom mco images using annotation

- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go
- operators/endpointmetrics/controllers/status/status_controller.go
- operators/endpointmetrics/controllers/status/status_controller_test.go
- operators/endpointmetrics/main.go
- operators/endpointmetrics/pkg/util/client.go
- operators/endpointmetrics/pkg/util/client_test.go
> renew hub client to handle hub config expired/updated

- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- operators/multiclusterobservability/controllers/placementrule/predicate_func.go
- operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
Signed-off-by: Nathaniel Graham <ngraham@redhat.com>
> Do not reconcile if annotation present

- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
> fix the problem that allowlist injected more than once in 2.6.z

- collectors/metrics/pkg/forwarder/forwarder.go
> don't fail forward process if any error in recording rule format(2.7)

- go.mod
- go.sum
- operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
- operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
- operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/config/crd/bases/core.observatorium.io_observatoria.yaml
- operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
> support serviceaccountprojection in mco/observatorium cr

- operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
Related to: https://issues.redhat.com/browse/ACM-4227
> use metrics consistently for cpu and memory overestimation

- operators/multiclusterobservability/manifests/base/grafana/dash-node-rsrc-use.yaml
Updating the dashboard to provide users with the ability to select multiple nodes when viewing the node dashboard.
JIRA Issue: https://issues.redhat.com/browse/ACM-5061
> [ACM-5061] Updated "USE Method / Node" dashboard to allow multiple node selection

- operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-cluster-rsrc-use.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-apiserver.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-etcd.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-networking-cluster.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server-cluster.yaml
- operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server.yaml
JIRA Issue: https://issues.redhat.com/browse/ACM-5059
> [ACM-5059] - Update dashboards to use relative time range when drilling down

- operators/multiclusterobservability/manifests/base/grafana/dash-acm-alert-analysis.yaml
Updating the alert analysis dashboard to pass the relative time range when drilling down.
Jira Issue: https://issues.redhat.com/browse/ACM-5059
> [ACM-5059]Updated links to pass relative time in alert dashboard

- .github/workflows/go-package-dependencies-update.yml
- collectors/metrics/Dockerfile
- go.mod
- loaders/dashboards/Dockerfile
- operators/endpointmetrics/Dockerfile
- operators/multiclusterobservability/Dockerfile
- proxy/Dockerfile
- tests/Dockerfile
- tools/simulator/alert-forward/Dockerfile
* upgrade to go 1.20
* remove deprecated -i go flag
---------
> [release-2.9] upgrade to go 1.20 (#1196)

- collectors/metrics/Dockerfile
- go.mod
- loaders/dashboards/Dockerfile
- operators/endpointmetrics/Dockerfile
- operators/endpointmetrics/main.go
- operators/multiclusterobservability/Dockerfile
- operators/multiclusterobservability/main.go
- proxy/Dockerfile
- tools/simulator/alert-forward/Dockerfile
Use readable date-time format in MCO operator and endpoint-operator logs
> Fix logging

- go.mod
- operators/endpointmetrics/main.go
- operators/multiclusterobservability/main.go
specify ISO8601TimeEncoder encoder on logger
> [release-2.7] Fix logging

- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
- operators/pkg/config/config.go
* Add Watch for prometheus UWM Stateful Set
* Added another Watch and deployment deletion
* Changed prometheus uwl watch to 'true' for 'create' predicate
---------
> [release-2.7] Add Watch for prometheus UWM Stateful Set (#1192)

- Makefile
- collectors/metrics/Dockerfile
- loaders/dashboards/Dockerfile
- operators/endpointmetrics/Dockerfile
- operators/multiclusterobservability/Dockerfile
- proxy/Dockerfile
- tools/simulator/alert-forward/Dockerfile
**Changes:**  Changes the CGO_ENABLED flag to 1 / Changes TLS Version to 1.2.
> [release-2.7] Change CGO_ENABLED to 1 / Changed TLS Version to 1.2

- Makefile
- collectors/metrics/Dockerfile
- loaders/dashboards/Dockerfile
- operators/endpointmetrics/Dockerfile
- operators/multiclusterobservability/Dockerfile
- proxy/Dockerfile
- tools/simulator/alert-forward/Dockerfile
**Changes:**  Changes the CGO_ENABLED flag to 1 / Changes TLS Version to 1.2.
> [release-2.8] Change CGO_ENABLED to 1 / Changed TLS Version to 1.2

- Makefile
- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go
> [release 2.6] Support configuring alert forwarding externally

- Makefile
- cicd-scripts/run-e2e-tests.sh
- collectors/metrics/Dockerfile
- examples/minio-tls/minio-pvc.yaml
- examples/minio/minio-pvc.yaml
- loaders/dashboards/Dockerfile
- operators/endpointmetrics/Dockerfile
- operators/multiclusterobservability/Dockerfile
- proxy/Dockerfile
- tests/pkg/utils/utils.go
- tools/simulator/alert-forward/Dockerfile
**Changes:**  Changes the CGO_ENABLED flag to 1 / Changes TLS Version to 1.2.
> [release-2.6] Change CGO_ENABLED to 1 / Changed TLS Version to 1.2

- examples/export/v1beta2/custom-certs/observability.yaml
- examples/export/v1beta2/observability.yaml
- examples/mco/e2e/v1beta2/custom-certs/observability.yaml
- examples/mco/e2e/v1beta2/observability.yaml
- examples/policy/resourceQuota.yaml
- operators/multiclusterobservability/manifests/base/alertmanager/prometheusrule.yaml
- tests/pkg/tests/observability_addon_test.go
- tests/pkg/tests/observability_export_test.go
These alerts are modeled after [RHOBS compactor alerts ](https://github.com/rhobs/configuration/blob/2e740eca3d9321dc916c9d54a17526829d8dffee/resources/observability/prometheusrules/observatorium-thanos-production.prometheusrules.yaml#L79-L151)
> [ACM-7321] Configure alerts to detect acm hub compactor problems

- operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
- operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
Signed-off-by: David Luong <dluong@redhat.com>
> [ACM-7717] add tlsSecretMountPath for tlsSecretName

- go.mod
- go.sum
- tests/pkg/testdata/ignored-metric-list
Bumps client_golang, client_model and common to latest
> *: Bump prometheus client libs

- loaders/dashboards/pkg/controller/dashboard_controller.go
- loaders/dashboards/pkg/controller/dashboard_controller_test.go
This finally gets us to security rating A on sonarcloud.
> Check kubeinformer error

- operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
> [release-2.8] [ACM-3748] Set max source resolution to auto in Grafana datasource

- operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
> [release-2.7] [ACM-3748] Set max source resolution to auto in Grafana datasource

- operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
> [release-2.6] [ACM-3748] Set max source resolution to auto in Grafana datasource 

- operators/endpointmetrics/pkg/util/lease.go
- operators/multiclusterobservability/controllers/placementrule/role.go
- operators/multiclusterobservability/pkg/certificates/cert_agent.go
- operators/multiclusterobservability/pkg/config/config.go
- operators/multiclusterobservability/pkg/rendering/renderer_proxy.go
- operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
- operators/multiclusterobservability/pkg/util/managedclusteraddon.go
Cherry-picking https://github.com/stolostron/multicluster-observability-operator/pull/1275 into the 2.7 release stream.
> [release-2.7] Clear `gosec` false positives

- tests/pkg/tests/observability_alert_test.go
- tests/pkg/utils/mco_deploy.go
Mostly cherry picking #1258, without commenting code.
> [release-2.6] Skip AM test and remove slack hook url

- operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
- operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
Back port PR to service stream
> [ACM-7717] [release-2.7] add tlsSecretMountPath for tlsSecretName

- collectors/metrics/pkg/metricsclient/metricsclient.go
- collectors/metrics/pkg/metricsclient/metricsclient_test.go
From version 0.28 of Thanos, labels need to be ordered, with no duplicates and no empty labels.
This PR ports the fixes done in https://github.com/openshift/telemeter/pull/429 to metrics-collector
It also undoes the changes done in https://github.com/stolostron/multicluster-observability-operator/commit/633e18cdf8e7866f951b4a005a9dede3fe45c567 to ensure 1:1 compatibility with telemeter codebase.
Potential fix for https://issues.redhat.com/browse/ACM-6112
> [ACM-6112] Sanitize labels in metrics-collector

- operators/multiclusterobservability/manifests/base/grafana/dash-acm-hcp-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml
Adding the new HCP dashboards YAMLs to kustomization.yaml and adding a value filter to the HCP list table.
> Fix HCP dashboards

- operators/pkg/deploying/deployer.go
- operators/pkg/deploying/deployer_test.go
https://issues.redhat.com/browse/ACM-9321
> Add Ingress update function to template deployer

- operators/endpointmetrics/pkg/util/client.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- operators/multiclusterobservability/controllers/placementrule/predicate_func.go
- operators/multiclusterobservability/main.go
- operators/multiclusterobservability/pkg/config/config.go
This reverts commit 56c83ec8eab0808c8d6dd966b3810a91356c16cc, reversing changes made to e4130bd057568edcfff0a3039612ec2ce9f8beb2.
> Revert "Merge branch 'hub-metrics-collector' into main"

- cicd-scripts/run-e2e-tests.sh
- tests/pkg/tests/observability_addon_test.go
- tests/pkg/tests/observability_install_test.go
- tests/pkg/utils/client.go
- tests/pkg/utils/mco_deploy.go
- tests/pkg/utils/mco_oba.go
- tests/pkg/utils/utils.go
- logs pods events
- logs failing containers logs
- fixes some unnecessary logging like in e2e king where mco logs are dumped when oba fails...
- reduce noisy logging
- logs oba container logs when test fails
> improve ci logging

- tests/run-in-kind/router/route_crd.yaml
- tests/run-in-kind/router/router_rbac.yaml
The logs complain about the versions used here as they are deprecated. Brings them up to date with the newer KinD version.
> Bring the Route and Route RBAC up to date

- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
This change creates a Secret for the Grafana Accessor ServiceAccount if there was not previously one generated by the platform.
As per [OCP documentation](https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-legacy-service-account) - we should not rely on Secrets generated by the underlying control plane since these may go away.
This behaviour is protected with LegacyServiceAccountTokenNoAutoGeneration feature gate and hence it makes sense to ensure that we force the generation of said Secret and token which we depend on.
> Create a Secret for Grafana Accessor SA if not auto-generated

- operators/multiclusterobservability/controllers/placementrule/endpoint_metrics_operator.go
- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
Add missing resource types during create and update
https://github.com/stolostron/multicluster-observability-operator/pull/1366/files
> [ACM-10153] Ensure create/update for all resource types in hub metrics collection

- sonar-project.properties
- remove `main.go` files exclusion. I don't think we should exclude those from the analysis
- adding exclusions for `examples` and `tests` dirs
- try ignoring code check rules. Starting with the long lines one which is particularly useless and annoying
> Update sonar properties

- operators/endpointmetrics/controllers/observabilityendpoint/match_evaluator_test.go
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
https://issues.redhat.com/browse/ACM-10506
> [ACM-10506]endpointmetrics: Do not add generated resources as volumes on ocp3

- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- operators/pkg/config/config.go
This cherry picks the changes from #1386 and #1390 into the 2.10 release stream.
> [ACM-10806] [2.10] Update hub collector with the whole obs addon spec

- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
This cherry picks the fix from #1388 into the 2.11 release stream.
> Fix mco api beta2 import

- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
- operators/endpointmetrics/controllers/status/status_controller.go
- operators/endpointmetrics/main.go
- operators/endpointmetrics/pkg/util/client.go
- operators/endpointmetrics/pkg/util/client_test.go
> Proper registration of scheme for hub client

- operators/multiclusterobservability/pkg/config/config.go
Doing the retention increase in this PR.
The changes in max compaction level and and concurrency will be done through the jsonnet source, as they aren't supported in the CRDs.
> [RHOBS-987] Update Thanos Compact retention

- go.mod
- operators/multiclusterobservability/controllers/placementrule/manifestwork.go
> [ACM-10967] Stop regenerating Secrets from SA updates

- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- operators/multiclusterobservability/pkg/config/config.go
https://issues.redhat.com/browse/ACM-11071
> add watch logic for endpoint sa when deleted

- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- operators/multiclusterobservability/pkg/config/config.go
Back port to 2.10 - https://issues.redhat.com/browse/ACM-11071
> [ACM-11071] Endpoint sa watch for hub - 2.10 back port

- operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml
Fix openshift-virtualization dashboard name,
updated capital letter to lower case and
add the dashboard to kustomization.yaml.
> Fix openshift-virtualization dashboard

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
https://issues.redhat.com/browse/ACM-10647
> Ensure Obs API Route is reconciled correctly

- operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
- operators/multiclusterobservability/controllers/multiclusterobservability/grafana_test.go
Handle Updates to the Route created for Grafana during reconcile
> [ACM-9682]Add Update Route handling for Grafana Route

- operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
- operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/controllers/placementrule/hub_info_secret.go
- operators/multiclusterobservability/pkg/certificates/certificates.go
- operators/multiclusterobservability/pkg/config/config.go
- operators/multiclusterobservability/pkg/config/config_test.go
Mostly the same as #1416, but now for the alertmanager URL.
> [ACM-10706] Add support for custom alertmanager url

- scripts/install-binaries.sh
- tools/simulator/metrics-collector/clean-metrics-collector.sh
- tools/simulator/metrics-collector/generate-metrics-data.sh
- tools/simulator/metrics-collector/rb-endpoint-operator-role-crd-hostedclusters-read.yaml
- tools/simulator/metrics-collector/role-endpoint-observability-operator-crd-hostedclusters-read.yaml
- tools/simulator/metrics-collector/setup-metrics-collector.sh
This PR contains a few various fixes that was needed to run the metric collector simulator and generate new metrics for it. See details in individual commits messages.
> Add required permissions for simulated cluster & various fixes for metrics generation

- operators/endpointmetrics/manifests/prometheus/crd/kustomization.yaml
- operators/endpointmetrics/manifests/prometheus/crd/prometheus_crd_0_73_2.yaml
- operators/endpointmetrics/manifests/prometheus/prometheus-operator-deployment.yaml
Update prometheus CRD after  update to stolostron/prometheus-operator version v0.73.2
https://github.com/stolostron/prometheus-operator/pull/40
> Update prometheus operator crd after version update

- cicd-scripts/setup-e2e-tests.sh
These were missed before merging:
https://github.com/stolostron/multicluster-observability-operator/pull/1454
> Tests: remove additional test print

- operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
- operators/multiclusterobservability/controllers/placementrule/predicate_func.go
- operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
- operators/multiclusterobservability/pkg/util/managedclusteraddon.go
We want to ensure that vendor label is set on a cluster before proceeding to decide if we need to install Prometheus on a cluster
https://issues.redhat.com/browse/ACM-11673
> Wait for vendor label on managedcluster object

- proxy/pkg/util/util.go
RBAC Query proxy utils.go watches for managed clusters asynchronously, whilst also facilitating query RBAC enforcement requests that both touch the same maps. 
E.g. 
1. Change happens to `clusterA` 
2. User queries data with perms to access `clusterA` simultaneously 
Resulting in the following error: 
```
I0710 15:50:22.603117       1 util.go:97] managedcluster label names update required: false
I0710 15:50:22.685471       1 util.go:263] changed a managedcluster: namgcbswd41p 
fatal error: concurrent map iteration and map writegoroutine 14780 [running]:
github.com/stolostron/multicluster-observability-operator/proxy/pkg/util.canAccessAllClusters(...)
```
I've added a RWmutex so that reads/writes can happen concurrently without panic.
> ACM-12689: Adding rw mutexes for RBAC query proxy enforcement

- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
Organises the watch list by resource type and adds a watch and predicate for the CMO config!
> [ACM-12738]Watch CMO cluster monitoring ConfigMap for changes

- proxy/pkg/util/util.go
[Backport of #1535](https://github.com/stolostron/multicluster-observability-operator/pull/1535)
>  [ACM-12689]: Adding rw mutexes for RBAC query proxy enforcement

- cicd-scripts/setup-e2e-tests.sh
The E2E tests running on kind are currently installing the OCM core (i.e. cluster-manager, klusterlet) using the very old `release-2.4` branch from the [stolostron/registration-operator repository](/stolostron/registration-operator). This branch lacks currently newer components and in particular the `addon-manager` and in turn we cannot test successfully the following PR that incorporates MCOA in MCO:
- #1470 
cc @philipgough
> Update ocm core setup on kind tests

- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
Adds a watch and predicate for the CMO config!
> [ACM-13041]Watch CMO cluster monitoring ConfigMap for changes

- proxy/pkg/proxy/proxy.go
- proxy/pkg/proxy/proxy_test.go
This fixes a couple of compatibility issues with Grafana version 10/11:
- Do not gzip empty request (newEmptyMatrixHTTPBody) as Grafana don't seem to handle that correctly in these versions
- The proxy send a specialized reponse to `acm_label_names`. In previous versions of Grafana, this would be a POST request to api/v1/series. In Grafana 10 it's a GET request to api/v1/series and in Grafana 10 it's a GET request to /api/v1/label/label_name/. This commit handles all of the above scenarios.
Note: by default Grafana 10/11 do not forward the
`X-Forwarded-Access-Token` needed for determining access levels. This has to be manually patched in our Grafana fork for the proxy to fully work.
Note 2: this is also compatible with our current Grafana version.
ACM-12782
> rbac-query-proxy: Grafana 10/11 compatibility 

- collectors/metrics/Containerfile.operator
- collectors/metrics/Dockerfile
This is a cherry-pick of https://github.com/stolostron/multicluster-observability-operator/pull/1522
> [release-2.10] Fix dnf install to prevent interactive confirmation

- .tekton/endpoint-monitoring-operator-acm-212-pull-request.yaml
- .tekton/endpoint-monitoring-operator-acm-212-push.yaml
- .tekton/grafana-dashboard-loader-acm-212-pull-request.yaml
- .tekton/grafana-dashboard-loader-acm-212-push.yaml
- .tekton/metrics-collector-acm-212-pull-request.yaml
- .tekton/metrics-collector-acm-212-push.yaml
- .tekton/multicluster-observability-operator-acm-212-pull-request.yaml
- .tekton/multicluster-observability-operator-acm-212-push.yaml
- .tekton/rbac-query-proxy-acm-212-pull-request.yaml
- .tekton/rbac-query-proxy-acm-212-push.yaml
- collectors/metrics/Containerfile.operator
- loaders/dashboards/Containerfile.operator
- operators/endpointmetrics/Containerfile.operator
- operators/multiclusterobservability/Containerfile.operator
- operators/multiclusterobservability/Dockerfile.dev
- proxy/Containerfile.operator
Cherry-pick commits from release-2.12 which was missing from main.
> Cherry pick release-2.12 to main

- operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
- operators/pkg/util/allowlist.go
https://issues.redhat.com/browse/ACM-13738
Backport of https://github.com/stolostron/multicluster-observability-operator/pull/1618
> Fix: Backport: sort metrics args for the metrics collector

- operators/endpointmetrics/pkg/collector/metrics_collector.go
- operators/endpointmetrics/pkg/collector/metrics_collector_test.go
- operators/pkg/util/allowlist.go
https://issues.redhat.com/browse/ACM-13738
> Fix: sort metrics collector metrics arguments

- operators/multiclusterobservability/pkg/config/resources.go
- operators/multiclusterobservability/pkg/config/resources_map.go
Issue: https://issues.redhat.com/browse/ACM-13715
> mcoa: adjust resources requests & remove limits

- operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
- operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go
https://issues.redhat.com/browse/ACM-13706
> ACM-13706: Stop CMO update if not changed

- operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_management_addon.yaml
- operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_role.yaml
Related with: https://github.com/rhobs/multicluster-observability-addon/pull/59
> mcoa: update manifests to support new Intrumentation CR stanzas

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/pkg/rendering/renderer.go
- operators/multiclusterobservability/pkg/rendering/renderer_test.go
- operators/pkg/deploying/deployer.go
- operators/pkg/deploying/deployer_test.go
Tested and it works ✅ 
Capabilities off:
Capabilities on:
> mcoa: make mcoa deployment optional

- tests/pkg/utils/mco_managedcluster.go
Backport PR that identifies healthy managed clusters during test run
> fix: [release-2.11] [ACM-14189]identify healthy managed clusters

- tests/pkg/utils/mco_managedcluster.go
Backport PR that identifies healthy managed clusters during e2e test run
> fix: [release-2.10] [ACM-14189]identify healthy managed clusters

- tools/README.md
Update README doc to make the login step explicit.
> doc: clarify users must login to grafana-dev console before swithching 

- collectors/metrics/pkg/metricsclient/metricsclient.go
- collectors/metrics/pkg/metricsclient/metricsclient_test.go
- go.mod
- go.sum
Backport of https://github.com/stolostron/multicluster-observability-operator/pull/1697
> [Release 2-11] ACM-14080: update collector retry logic on forward

- go.mod
- go.sum
> Bump golang.org/x/net to 0.33.0

- .tekton/endpoint-monitoring-operator-acm-213-pull-request.yaml
- .tekton/endpoint-monitoring-operator-acm-213-push.yaml
- .tekton/grafana-dashboard-loader-acm-213-pull-request.yaml
- .tekton/grafana-dashboard-loader-acm-213-push.yaml
- .tekton/metrics-collector-acm-213-pull-request.yaml
- .tekton/metrics-collector-acm-213-push.yaml
- .tekton/multicluster-observability-operator-acm-213-pull-request.yaml
- .tekton/multicluster-observability-operator-acm-213-push.yaml
- .tekton/rbac-query-proxy-acm-213-pull-request.yaml
- .tekton/rbac-query-proxy-acm-213-push.yaml
Part of https://issues.redhat.com/browse/HYPBLD-525
[slack thread ](https://redhat-internal.slack.com/archives/C012L9Y9C79/p1736171807555589) has more details
> enable hermetic builds

- go.mod
- go.sum
- tests/pkg/tests/observability_alert_test.go
- tests/pkg/utils/kube_debug.go
- tests/pkg/utils/mco_managedcluster.go
Backport of:
- https://github.com/stolostron/multicluster-observability-operator/pull/1805
- https://github.com/stolostron/multicluster-observability-operator/pull/1820
> [Backport 2.12]: Fix e2e watchdog alert

- .tekton/endpoint-monitoring-operator-acm-213-pull-request.yaml
- .tekton/endpoint-monitoring-operator-acm-213-push.yaml
- .tekton/grafana-dashboard-loader-acm-213-pull-request.yaml
- .tekton/grafana-dashboard-loader-acm-213-push.yaml
- .tekton/metrics-collector-acm-213-pull-request.yaml
- .tekton/metrics-collector-acm-213-push.yaml
- .tekton/multicluster-observability-operator-acm-213-pull-request.yaml
- .tekton/multicluster-observability-operator-acm-213-push.yaml
- .tekton/rbac-query-proxy-acm-213-pull-request.yaml
- .tekton/rbac-query-proxy-acm-213-push.yaml
- collectors/metrics/Containerfile.operator
- go.mod
- go.sum
- loaders/dashboards/Containerfile.operator
- operators/endpointmetrics/Containerfile.operator
- operators/multiclusterobservability/Containerfile.operator
- operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
- proxy/Containerfile.operator
- renovate.json
Fix Hermetic builds and Enterprise contract violations
> Fix Hermetic builds and Enterprise contract violations

- operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
- tests/pkg/tests/observability_metrics_test.go
ref: https://issues.redhat.com/browse/ACM-17519
> Add managed cluster policy metric to allowlist

- .tekton/endpoint-monitoring-operator-acm-214-pull-request.yaml
- .tekton/endpoint-monitoring-operator-acm-214-push.yaml
- .tekton/grafana-dashboard-loader-acm-214-pull-request.yaml
- .tekton/grafana-dashboard-loader-acm-214-push.yaml
- .tekton/metrics-collector-acm-214-pull-request.yaml
- .tekton/metrics-collector-acm-214-push.yaml
- .tekton/multicluster-observability-operator-acm-214-pull-request.yaml
- .tekton/multicluster-observability-operator-acm-214-push.yaml
- .tekton/rbac-query-proxy-acm-214-pull-request.yaml
- .tekton/rbac-query-proxy-acm-214-push.yaml
Adjust Konlfux files for ACM 2.14.
> Konflux for 2.14

- .tekton/endpoint-monitoring-operator-acm-213-pull-request.yaml
- .tekton/endpoint-monitoring-operator-acm-213-push.yaml
- .tekton/grafana-dashboard-loader-acm-213-pull-request.yaml
- .tekton/grafana-dashboard-loader-acm-213-push.yaml
- .tekton/metrics-collector-acm-213-pull-request.yaml
- .tekton/metrics-collector-acm-213-push.yaml
- .tekton/multicluster-observability-operator-acm-213-pull-request.yaml
- .tekton/multicluster-observability-operator-acm-213-push.yaml
- .tekton/rbac-query-proxy-acm-213-pull-request.yaml
- .tekton/rbac-query-proxy-acm-213-push.yaml
> Konflux: make release-2.13 target release-2.13

- collectors/metrics/Containerfile.operator
- collectors/metrics/Dockerfile
- loaders/dashboards/Containerfile.operator
- loaders/dashboards/Dockerfile
- operators/endpointmetrics/Containerfile.operator
- operators/endpointmetrics/Dockerfile
- operators/multiclusterobservability/Containerfile.operator
- operators/multiclusterobservability/Dockerfile
- proxy/Containerfile.operator
- proxy/Dockerfile
- tests/Containerfile.operator
- tests/Dockerfile
- tools/simulator/alert-forward/Containerfile.operator
- tools/simulator/alert-forward/Dockerfile
- tools/simulator/metrics-collector/metrics-extractor/Containerfile.operator
- tools/simulator/metrics-collector/metrics-extractor/Dockerfile
> Update  go builder - 1.23

- operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
[ACM-17443](https://issues.redhat.com/browse/ACM-17443)
We don't need an e2e for this. We can just create/update an addondeployment config with the node selector configs and ensure that its propagated to the endpoint operator deployment when the manifestworks for the spokes are created. Testing actual node selection by the pods is not in the scope for mco testing
> [ACM-17443] Check for node selector addondeployment config in endpoint operator

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_integration_test.go
- operators/multiclusterobservability/controllers/multiclusterobservability/testdata/crd/addon.open-cluster-management.io_addondeploymentconfigs.crd.yaml
- operators/multiclusterobservability/controllers/multiclusterobservability/testdata/crd/addon.open-cluster-management.io_clustermanagementaddons.crd.yaml
- operators/multiclusterobservability/controllers/multiclusterobservability/testdata/crd/monitoring.coreos.com_prometheusrules.yaml
- operators/multiclusterobservability/controllers/multiclusterobservability/testdata/crd/monitoring.coreos.com_servicemonitors.yaml
- operators/multiclusterobservability/controllers/multiclusterobservability/testdata/crd/routes-Default.crd.yaml
Setup envtest for MCO, ensure the prometheusRule is created on the hub.
> Add envtest to verify that MCO alerts are created for CMO on the hub

- operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
- operators/endpointmetrics/main.go
Currently it logs many status update errors on the hub. With no consequence as it does not impact the reconcile loop.
> Only activate cmowatcher on spokes

- tests/pkg/tests/observability_metrics_test.go
> Tests: Don't check that ignoredMetrics is in sync

- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
- operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func.go
- operators/multiclusterobservability/pkg/config/config.go
https://issues.redhat.com/browse/ACM-15168
> cherry pick to 2.10 for ACM-15167

- operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
- operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- operators/multiclusterobservability/config/crd/patches/webhook_multiclusterobservabilities_cainjection_patch.yaml
Related to https://github.com/kubernetes/kubernetes/pull/124061
> Remove caBundle from injection patch

- operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
- operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
Wrap error messages in the main reconcile loop, remove unneeded error logs.
> Improve MultiClusterObservability debuggability

- tests/pkg/tests/observability_metrics_test.go
- tests/pkg/utils/mco_deploy.go
- Avoid failing at the uninstall step if some resources are not found
- Check early if store secret has been reset in QE jenkins env
- Simplify metrics check with a fixed list, easier to maintain as project are adding they dashboards and updating the collected metrics
> Improve some e2e

- tests/pkg/tests/observability_rbac_test.go
- tests/setup_rbac_test.sh
- Fix kube:admin login in rbac tests to work when using username/pw instead of kubecontext
- Correctly clean up rbac env from any previous tests
- Make sure we logout from any non kube:admin user after each rbac test (so not to break any future tests in case of failures)
> rbac_test: correct login to kube:admin+cleanup env

- operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-openshift-virtualization-overview.yaml
- operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-openshift-virtualization-single-cluster-view.yaml
- operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-virtual-machines-by-time-in-status.yaml
This PR fixes some broken links in
virtualization dashboards and also updates
2 queries in the Time in Status dashboard.
> Fix broken links in virtualization dashboards

- operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-virtual-machines-by-time-in-status.yaml
- operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-virtual-machines-inventory.yaml
- operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-virtual-machines-service-level.yaml
- operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-virtual-machines-utilization.yaml
This PR fixes a bug in the Status variable that
breaks 4 virtualization dashboards.
> Fix Status variable in Virtualization dashboards

- .tekton/endpoint-monitoring-operator-acm-214-pull-request.yaml
- .tekton/endpoint-monitoring-operator-acm-214-push.yaml
- .tekton/grafana-dashboard-loader-acm-214-pull-request.yaml
- .tekton/grafana-dashboard-loader-acm-214-push.yaml
- .tekton/metrics-collector-acm-214-pull-request.yaml
- .tekton/metrics-collector-acm-214-push.yaml
- .tekton/multicluster-observability-operator-acm-214-pull-request.yaml
- .tekton/multicluster-observability-operator-acm-214-push.yaml
- .tekton/rbac-query-proxy-acm-214-pull-request.yaml
- .tekton/rbac-query-proxy-acm-214-push.yaml
> Update Konflux references

- tests/pkg/tests/observability_right_sizing_test.go
PR contains functional test case for testing out right-sizing functionality.
Related Epic - https://issues.redhat.com/browse/ACM-17966
> Added functional test for the Analytics feature

- tests/pkg/tests/observability_export_test.go
Make sure to use the renamed local-cluster name in the promql query.
> ACM-22443 e2e: correctly find local-cluser name in export

- loaders/dashboards/pkg/controller/dashboard_controller.go
- operators/multiclusterobservability/manifests/base/grafana/platform/dash-acm-clusters-overview.yaml
- operators/multiclusterobservability/pkg/rendering/renderer_grafana.go
- operators/multiclusterobservability/pkg/rendering/renderer_grafana_test.go
- operators/multiclusterobservability/pkg/rendering/renderer_mcoa.go
- operators/pkg/deploying/deployer.go
Follows https://github.com/stolostron/multicluster-observability-operator/pull/2033 that was merged too quickly.
> Fix dashboard reconcile for home annotation

- .tekton/endpoint-monitoring-operator-acm-215-pull-request.yaml
- .tekton/endpoint-monitoring-operator-acm-215-push.yaml
- .tekton/grafana-dashboard-loader-acm-215-pull-request.yaml
- .tekton/grafana-dashboard-loader-acm-215-push.yaml
- .tekton/metrics-collector-acm-215-pull-request.yaml
- .tekton/metrics-collector-acm-215-push.yaml
- .tekton/multicluster-observability-operator-acm-215-pull-request.yaml
- .tekton/multicluster-observability-operator-acm-215-push.yaml
- .tekton/rbac-query-proxy-acm-215-pull-request.yaml
- .tekton/rbac-query-proxy-acm-215-push.yaml
- docs/diagrams/README.md
- docs/diagrams/architecture/observability-bootstrapping-hub.txt
- docs/diagrams/architecture/observability-bootstrapping-managed.txt
- docs/diagrams/components/metrics-collection-alert-forwarding.txt
- docs/diagrams/workflows/metrics-collection-status-propagation.txt
- docs/diagrams/workflows/observability-placement-delete-flow.txt
Add sequence diagrams that describe MCO flows.
> Add sequence diagrams for MCO flows

- operators/multiclusterobservability/controllers/analytics/rightsizing/rs-utility/policy.go
- operators/multiclusterobservability/manifests/base/grafana/analytics/dash-acm-right-sizing-virtualization-overestimation.yaml
- operators/multiclusterobservability/manifests/base/grafana/analytics/dash-acm-right-sizing-virtualization-underestimation.yaml
- operators/multiclusterobservability/manifests/base/grafana/analytics/dash-acm-right-sizing-virtualization.yaml
Fixed grafana dashboard minor issues for the virtualization right-sizing dashboard.  Also fixed Policy RemediationAction to enforced.
> fix: Virtualization Right-Sizing Dashboard Minor Issues 
