stolostron/multicluster-observability-operator

controllers/multiclusterobservability/multiclusterobservability_controller.go
main.go
pkg/util/client.go

follow up PR for: https://github.com/open-cluster-management/multicluster-observability-operator/pull/198
check placementrule CRD before apply placementrule to support hub only mode.

check placementrule CRD before apply placementrule.

---

main.go

A fix for: https://github.com/open-cluster-management/multicluster-observability-operator/pull/400
Only register placementrule reconciler when its CRD is installed.

register placementrule reconciler when its CRD is installed.

---

manifests/base/alertmanager/alert_rules.yaml
manifests/base/grafana/acm-multicluster-dash.yaml

Related: open-cluster-management/backlog#10693
Remove expensive alerting rule KubeAPIServerLatency as it is a memory hog and is preventing our ability to scale
Do not group by verb in the Grafana query for APIServer control plane health. This Improves Grafana "ACM Cluster Overview" page load performance.

Remove KubeAPIServerLatency alert, improve grafana dashboard performance

---

manifests/base/alertmanager/alert_rules.yaml
manifests/base/grafana/acm-multicluster-dash.yaml

Related: open-cluster-management/backlog#10693
Remove expensive alerting rule `KubeAPIServerLatency` as it is a memory hog and is preventing our ability to scale
Do not group by verb in the Grafana query for APIServer control plane health. This Improves Grafana `ACM Cluster Overview` page load performance.

2.2 - Remove KubeAPIServerLatency alert, improve grafana dashboard performance

---

controllers/multiclusterobservability/multiclusterobservability_controller.go

create namespace if it doesn't exist, this is useful for hub-only mode.
The permissions from namespace creation/update/delete are already in the RBAC: https://github.com/open-cluster-management/multicluster-observability-operator/blob/main/config/rbac/mco_role.yaml#L19

create namespace if it doesn't exist.

---

Dockerfile.prow

Fix prow build issue:
```
INFO[2021-04-09T07:41:53Z] ci-operator version v20210408-34d4be8        
INFO[2021-04-09T07:41:53Z] Loading configuration from https://config.ci.openshift.org for open-cluster-management/multicluster-observability-operator@main 
INFO[2021-04-09T07:41:53Z] Resolved source https://github.com/open-cluster-management/multicluster-observability-operator to main@0d69e8d2, merging: #445 a42b5a64 @morvencao 
INFO[2021-04-09T07:41:53Z] Ran for 0s                                   
ERRO[2021-04-09T07:41:53Z] Some steps failed:                           
ERRO[2021-04-09T07:41:53Z]   * could not resolve inputs: could not determine inputs for step [input:open-cluster-management_builder_go1.15-linux]: could not resolve base image: imagestreamtags.image.openshift.io …
```

fix base image not found issue.

---

controllers/placementrule/manifestwork.go
controllers/placementrule/manifestwork_test.go
controllers/placementrule/placementrule_controller.go
controllers/placementrule/placementrule_controller_test.go

https://github.com/open-cluster-management/backlog/issues/11704

use only one manifestwork in observability

---

manifests/base/alertmanager/alertmanager-statefulset.yaml
pkg/rendering/renderer_alertmanager.go

See DNS resolution issue for Alertmanager Cluster Peers:
```
level=warn ts=2021-04-27T08:11:51.795Z caller=cluster.go:461 component=cluster msg=refresh result=failure addr=alertmanager-0.alertmanager-operated.open-cluster-management-observability.svc:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-0.alertmanager-operated.open-cluster-management-observability.svc:9094: lookup alertmanager-0.alertmanager-operated.open-cluster-management-observability.svc on 172.30.0.10:53: no such host\n\n"
level=warn ts=2021-04-27T08:11:51.853Z caller=cluster.go:461 component=cluster msg=refresh result=failure addr=alertmanager-1.alertmanager-operated.open-cluster-management-observability.svc:9094 err="1 error occurred:\n\t* Failed to resolve …
```

fix dns issue for alertmanager cluster peers.

---

controllers/multiclusterobservability/observatorium.go

`--receive.replication-factor` is used to define how many times to replicate incoming write requests. it is used to in case deleted raw data. It should not be set the same value of receive replicas. We can keep as 3 replicationFactor w/o change. 
You may have a question how to ensure the thanos query can query the desired data as it has different data in receive instance. You can see that the store is configured as `--store=dnssrv+_grpc._tcp.observability-thanos-receive-default.open-cluster-management-observability.svc.cluster.local`. This configuration will instruct Thanos to discover all endpoints within the observability-thanos-receive-default service in the open-cluster-management-observability namespace and use the declared port named grpc. And query will do deduplication for the …

Update replicationFactor to 3

---

manifests/base/config/metrics_allowlist.yaml
manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml

https://github.com/open-cluster-management/backlog/issues/11970
remove metrics node_namespace_pod_container:container_memory_* from allowlist, and update dashboards to use container_memory_* 
remove metrics container_cpu_usage_seconds_total, which is not used and in dashboards node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate is used

remove the metrics which can be covered by others

---

controllers/placementrule/manifestwork.go
controllers/placementrule/manifestwork_test.go

if a metric name ending in `-`,  we will delete this metric from the default allowlist.
https://github.com/open-cluster-management/backlog/issues/12106

support metrics removal from default allowlist

---

controllers/placementrule/manifestwork.go
controllers/placementrule/manifestwork_test.go
pkg/config/config.go

- update `memcached-exporter` to v0.9.0
- To add the hyphen "-" before the metric
name. it should be easily sorted and see which metrics are removed
- https://github.com/open-cluster-management/backlog/issues/12106

add the hyphen before the metric name

---

controllers/multiclusterobservability/multiclusterobservability_controller.go
pkg/config/config.go
pkg/rendering/renderer.go
pkg/rendering/renderer_alertmanager.go
pkg/rendering/renderer_grafana.go
pkg/rendering/renderer_thanos.go

fix: https://github.com/open-cluster-management/backlog/issues/12335
- add CR label `observability.open-cluster-management.io/name` with MCO CR name value to cluster scoped resources, currently only handle **clusterrole** and **clusterrolebinding**
- then delete these cluster scoped resources by the CR label `observability.open-cluster-management.io/name` after MCO CR is deleted

remove cluster scoped resources.

---

controllers/multiclusterobservability/multiclusterobservability_controller.go

fix: https://github.com/open-cluster-management/backlog/issues/12475
Update route path for alertmanager, so that only APIs for alertmanager are exposed.

update route path for alertmanager.

---

main.go

related with https://github.com/open-cluster-management/backlog/issues/12506
use filteredcache for the watch resources to reduce the memory usage, especially in large scale env

use fitlercache for placementrule&serviceaccount

---

api/shared/multiclusterobservability_shared.go
bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
bundle/manifests/observability.open-cluster-management.io_observabilityaddons.yaml
config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml

fix: https://github.com/open-cluster-management/backlog/issues/12622

update the default interval to 60s

---

controllers/multiclusterobservability/observatorium.go

- add timeout for update failure avoid update conflict
- use byte.Equal instead reflect.DeepEqual
https://github.com/open-cluster-management/backlog/issues/12815
https://github.com/open-cluster-management/cicd-staging/issues/465

Fix observatorium can not setup thanos components

---

api/v1beta1/multiclusterobservability_conversion.go

Fix nil pointer for api conversion:
```
2021/05/27 09:44:51 http: panic serving 10.129.0.1:39600: runtime error: invalid memory address or nil pointer dereference
goroutine 13975 [running]:
net/http.(*conn).serve.func1(0xc0004f8fa0)
/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x1ac2080, 0x2c102e0)
/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/open-cluster-management/multicluster-observability-operator/api/v1beta1.(*MultiClusterObservability).ConvertFrom(0xc00000af00, 0x1fcb0e0, 0xc000c8e820, 0x1fcb0e0, 0xc000c8e820)
/workspace/api/v1beta1/multiclusterobservability_conversion.go:91 +0x42
sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*Webhook).convertObject(0xc000adc520, 0x1fa7130, 0xc000c8e820, 0x1fa7090, 0xc00000af00, 0x1fa7090, 0xc00000af00) …
```

add check for non-default field for api-conversion.

---

manifests/base/grafana/dash-k8s-apiserver.yaml

In current dashboard, the variables `cluster` and `instance` value are queried from an aggregated metrics name. In simulator, since we are not uploading aggregated data, so variables and simulator dashboard doesn't work as below. 
This fix will use a normal metrics name to query variables, the result is as below:
Signed-off-by: haoqing0110 <qhao@redhat.com>

use a non recording rule name to query variables

---

manifests/base/alertmanager/alert_rules.yaml

Currently, the OOTB alert `CriticalPolicyReport` is included in the alerting group `kubernetes-storage`. We need to separate it into its own group (i.e `policy-reports`).

added policy report alert to a separate group

---

example/minio/minio-deployment.yaml
example/minio/minio-pvc.yaml
example/minio/minio-secret.yaml
example/minio/minio-service.yaml

For OKD support, we can ask the user to apply the minio as object store to use the observability feature.

Add minio example manifests

---

Makefile.prow

Current OS detection is not correct, when make command is executed on Ubuntu, I still get error:
```
...
make: gsed: Command not found
Makefile.prow:92: recipe for target 'manifests' failed
make: *** [manifests] Error 127
```

fix os detection in makefile.

---

manifests/base/proxy/ingress.yaml

Fix https://github.com/open-cluster-management/backlog/issues/13262
Signed-off-by: haoqing0110 <qhao@redhat.com>

update ingress to use networking.k8s.io/v1

---

main.go

Disable development mode by default. You can add `- -zap-log-level=debug` to enable the debug.

Disable development mode

---

controllers/multiclusterobservability/multiclusterobservability_controller.go
controllers/placementrule/placementrule_controller.go
go.mod
go.sum
main.go
pkg/config/config.go
pkg/config/config_test.go

Original `controller-filtered-cache` doesn't support selector logic `OR` for the same watching resources, I enhanced the `controller-filtered-cache` in https://github.com/IBM/controller-filtered-cache/pull/28 and now we can build filtered cache with multiple `OR` seletors for the same watching resource. 
pre-work:
- https://github.com/open-cluster-management/multicluster-observability-operator/pull/604
- https://github.com/open-cluster-management/multicluster-observability-operator/pull/610
ref: open-cluster-management/backlog#13426

fix resources watch across multiple namespaces.

---

controllers/multiclusterobservability/multiclusterobservability_controller.go
controllers/multiclusterobservability/multiclusterobservability_controller_test.go
controllers/placementrule/placementrule_controller.go
controllers/placementrule/placementrule_controller_test.go
main.go
pkg/util/client.go

the PR:
- removes unused client(CRD client and ocpClient) for controller
- checks the CRDs existing once to avoid inconsistent check result
- fixes UT

remove unused client and fix ut.

---

main.go
pkg/config/config.go

https://github.com/open-cluster-management/backlog/issues/13812
This reverts commit 02c4714980535234fa28e0ec872407203afd815d.

Revert "wait for manifestwork crd before starting manager. (#628)"

---

operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go

This is a followup PR for https://github.com/open-cluster-management/multicluster-observability-operator/pull/633
I found the datasource setting of grafana now contains many empty(with default value) fields, we should remove these fields to clean the noise to grafana:
```
apiVersion: 1
datasources:
- access: proxy
basicAuth: false
basicAuthPassword: ""
basicAuthUser: ""
editable: false
isDefault: true
name: Observatorium
orgId: 0
type: prometheus
url: xxx:8080
version: 0
jsonData:
tlsAuth: false
tlsAuthWithCACert: false
queryTimeout: 300s
httpMethod: ""
secureJsonData: null
```

omit empty fields in grafana datasource settings.

---

controllers/multiclusterobservability/multiclusterobservability_controller.go
controllers/multiclusterobservability/placementrule.go
controllers/placementrule/endpoint_metrics_operator.go
controllers/placementrule/manifestwork.go
controllers/placementrule/manifestwork_test.go
controllers/placementrule/placementrule_controller.go
controllers/placementrule/placementrule_controller_test.go
controllers/placementrule/role.go
controllers/placementrule/role_test.go
manifests/endpoint-observability/kustomization.yaml
manifests/endpoint-observability/observability.open-cluster-management.io_observabilityaddon_v1beta1_crd.yaml
pkg/config/config.go

ref: https://github.com/open-cluster-management/backlog/issues/14284
The idea is to create a new placementrule to select only openshift 311 cluster. likes:
```
matchExpressions:
- key: observability
operator: NotIn
values:
- disabled
- key: vendor
operator: In
values:
- OpenShift
- key: openshiftVersion
operator: In
values:
- "3"
```
for 311, we need to apply `v1beta1` oba crd.

Support 311

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/config/config_test.go

ref: https://github.com/open-cluster-management/backlog/issues/14560
This PR is to fix the inconsistent operand names after MCO is upgraded from release-2.2 and then create new MCO CR.
Need to be cherry-picked to release-2.3 Z stream.

clean up the operand names map for cr deletion.

---

operators/multiclusterobservability/pkg/config/config.go

I found that there are 2 replicasets for `grafana` `rbac-query-proxy` component. One rs is using the default image, the other is using the desired image. alertmanager should have the same behaviour. It can be a root cause of https://github.com/open-cluster-management/backlog/issues/14486
so add more debug info to see what happened

Add debug information for troubleshooting

---

operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml

Here's the list of name, types, and description for the assisted metrics being added in this PR
* assisted_installer_cluster_creations (counter): Number of cluster
resources created, by version
* assisted_installer_cluster_installation_started (counter): Number of
clusters that entered “installing” state, by version
* assisted_installer_cluster_installation_second (histogram):
Histogram/sum/count of installation time for completed clusters, by
result and OCP version (1 per cluster)
* assisted_installer_cluster_host_installation_count (histogram): Number
of hosts per cluster when the installation started (1 per cluster)
* assisted_installer_host_installation_phase_seconds (histogram):
Histogram/sum/count of time for each phase, by phase, final install
result, and OCP version (Number of …

Add Assisted Installer metrics to metrics_allowlist

---

collectors/metrics/Dockerfile

ref: https://code.engineering.redhat.com/gerrit/c/metrics-collector/+/261256
cicd has a shell script to check if there has any difference between cache dockerfile with upstream dockerfile. If so, send the error for downstream build. 
the current format is different with the cached one. so update the format with correct format.

format dockerfile

---

operators/multiclusterobservability/controllers/placementrule/manifestwork.go

fix the clustername key used in hubinfo secret

---

operators/pkg/util/util.go

If you're not using the default mux you just have to register any/all of those you want with whatever mux you're using. for our case, we can simply hand off any request prefixed with /debug/ to the http.DefaultServeMux

Register debug to http.DefaultServeMux

---

operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
tests/pkg/tests/observability_addon_test.go
tests/pkg/utils/mco_namespace.go

if the managedcluster has `observability=disable`, it triggers the `deleteFunc`. so need to remove the cluster name from the map.

correct managedcluster delete process

---

controllers/multiclusterobservability/multiclusterobservability_controller.go
pkg/config/config.go
pkg/config/config_test.go

cherrypick https://github.com/open-cluster-management/multicluster-observability-operator/pull/669
/hold

cherrypick 669 to cleanup cache for mco cr deletion

---

sonar-project.properties

Updating the sonar-project.properties `name` and `key` to match the repo name. This was causing the builds to fail with sonar, since the repo was renamed.
Signed-off-by: dislbenn <lavontae.bennett@gmail.com> / dbennett@redhat.com

updated sonar-project.properties

---

loaders/dashboards/pkg/controller/dashboard_controller.go
operators/multiclusterobservability/manifests/base/grafana/deployment.yaml

ref: https://github.com/open-cluster-management/backlog/issues/13382
2 fixes for this issue:
1. pass the `POD_NAMESPACE` environment variable to grafana dashboard loader to watch this namespace configmap only
2. update the grafana dashboards if the resourceVersion is changed.
before:
```
observability-grafana-5d5f6dfffd-j77j2                     grafana-dashboard-loader    5m           220Mi
observability-grafana-5d5f6dfffd-z2f7p                     grafana-dashboard-loader    18m          115Mi
```
after
```
observability-grafana-585d8855b5-89fcq                     grafana-dashboard-loader    0m           16Mi
observability-grafana-585d8855b5-fsdk9                     grafana-dashboard-loader    0m           14Mi
```

add POD_NAMESPACE environment and check ResourceVersion

---

go.mod
go.sum
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/role.go
operators/multiclusterobservability/main.go
operators/multiclusterobservability/pkg/util/managedclusteraddon.go
operators/multiclusterobservability/pkg/util/managedclusteraddon_test.go

ref: https://github.com/open-cluster-management/backlog/issues/14774
in 2000 simulated manifestwork and 2000 simulated managedcluster env:
before:
```
NAME                                                  CPU(cores)   MEMORY(bytes)
multicluster-observability-operator-cd77d999f-xs5bc   20m           805Mi
```
After: 
```
NAME                                                   CPU(cores)   MEMORY(bytes)
multicluster-observability-operator-86755cb7b4-q7rdn   12m          562Mi
```

add filter for rbac resources and managedclusteraddon in cache.

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
operators/multiclusterobservability/controllers/placementrule/endpoint_metrics_operator.go
operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/pkg/rendering/renderer.go
operators/multiclusterobservability/pkg/rendering/renderer_test.go
operators/multiclusterobservability/pkg/rendering/templates/templates.go
operators/multiclusterobservability/pkg/rendering/templates/templates_test.go

ref: https://github.com/open-cluster-management/backlog/issues/14774
This PR tries to optimize the manifests loading with kustimize library:
- loading manifests from disk with kustomize library is an expensive operation and the load results will never change, so we just need to load once.
- some other small fixes, mainly removing unused parameters.
In simulated env of 2k manifestwork + 2k managedcluster, the highest memory usage before this change:
```
NAME                                                   CPU(cores)   MEMORY(bytes)
multicluster-observability-operator-5547d89bcc-vh2rp   7m           827Mi
```
After this change, the memory is:
```
NAME                                                   CPU(cores)   MEMORY(bytes)
multicluster-observability-operator-7d889cf999-ctgv4   5m …
```

optimize template load and render.

---

operators/multiclusterobservability/pkg/util/managedclusteraddon.go

ref: open-cluster-management/backlog#14774
This PR fixes the **update** logic for **managedclusteraddon** resource, the **update** logic should in different reconcile loop with **create** logic, otherwise we always get the following error:
```
{"level":"error","ts":1629431004.136965,"logger":"controller_placementrule","msg":"Failed to create ManagedClusterAddon","error":"managedclusteraddons.addon.open-cluster-management.io \"observability-controller\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update","stacktrace":"github.com/open-cluster-management/multicluster-observability-operator/controllers/placementrule.createManagedClusterRes\n\t/root/workspace/multicluster-observability-operator-release-23/controllers/placementrule/placementrule_controller. …
```

fix update logic for managedclusteraddon.

---

tests/pkg/tests/observability_addon_test.go

ref: https://github.com/open-cluster-management/backlog/issues/15508
`[Stable] Modifying managedcluster cr to disable observability ` is to disable oba. 
`It("[Integration] Remove disable observability label from the managed cluster"` won't be executed in canary environment.
That is why we cannot find the observability addon components in that managedcluster.

Enable observability addons

---

operators/endpointmetrics/manifests/prometheus/prometheus-statefulset.yaml
operators/endpointmetrics/pkg/rendering/renderer.go
operators/multiclusterobservability/manifests/endpoint-observability/images.yaml
operators/pkg/config/config.go

ref: https://github.com/open-cluster-management/backlog/issues/15086
follow up PR for: https://github.com/open-cluster-management/multicluster-observability-operator/pull/718

introduce config-reloader for prometheus to fix CA totation on *KS.

---

operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/pkg/config/config.go

This PR tries to reduce the loop for creating managedcluster resources.
Before the changes, if we create 10 managed cluster one by one, the `createManagedClusterRes` will be executed 1 + 2 + .... 10,
After the change,  the results will be 10.
For the change of MCO CR/configmap/secret and other resources the operator is watching, the number of `createManagedClusterRes` will be the number of managedcluster.

reduce the duplicated loop for creating managedcluster resources

---

examples/minio/minio-deployment.yaml
examples/minio/minio-pvc.yaml
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
operators/multiclusterobservability/controllers/placementrule/hub_info_secret.go
operators/multiclusterobservability/controllers/placementrule/hub_info_secret_test.go
operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
operators/multiclusterobservability/main.go
operators/multiclusterobservability/manifests/base/grafana/deployment.yaml
operators/multiclusterobservability/pkg/certificates/cert_controller.go
operators/multiclusterobservability/pkg/certificates/cert_controller_test.go
operators/multiclusterobservability/pkg/certificates/certificates.go
operators/multiclusterobservability/pkg/certificates/certificates_test.go
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/rendering/renderer_grafana.go

This PR tries to replace the openshift Route with service's DNS for testing in KinD cluster.

replace route in kind testing env.

---

operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml

ref: https://github.com/open-cluster-management/backlog/issues/15736
There is an issued mco CR that causes mco operator crashing, after investigation, the `storageConfig` was mistaken for `storageConfigObject`.
By design, in v1beta2 mco API, the `storageConfig` and `metricObjectStorage` are required fields, so in that case, the CR should be refused to applied in to the cluster.
However, unfortunately, the required fields are not in the generated MCO CRD, the reason is:
> The omitempty tag in Foo string `json:"foo,omitempty"` had more precedence than the kubebuilder marker +kubebuilder:validation:Required therefore making the resultant generated crd field to be optional.
The +kubebuilder:validation:Required marker does works as desired when omitempty is not used.
This PR remove the …

fix required fields for mco.

---

cicd-scripts/setup-e2e-tests.sh

use registration-operator release-2.3 to run mco e2e.

use release 2.3 to run e2e

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go

If the user adds new annotation (e.g.: mco-grafana-image), it will not trigger reconciler. That is because the generation is not changed.

Update to use ResourceVersion instead of Generation for MCO CR Update

---

operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go
operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/multiclusterobservability/pkg/certificates/cert_controller.go
operators/multiclusterobservability/pkg/certificates/cert_controller_test.go
operators/multiclusterobservability/pkg/servicemonitor/sm_controller.go
operators/multiclusterobservability/pkg/servicemonitor/sm_controller_test.go

1. fixed restart problem: https://github.com/open-cluster-management/backlog/issues/15493
2. fixed servicemonitor create/update issue
3. fixed problem in createmanifestwork() that install_prom's default value is reset by *KS cluster will lead to problem in Openshift cluster

avoid unnecessary restart during deployment

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go

Reverts open-cluster-management/multicluster-observability-operator#729
We need depend on MCH ready and then update images to fix this known issue:
> 1.3.3.8. Observability stateful set uses wrong images in disconnected environment. In rare cases with disconnected environments, some pods of the observability StatefulSet are stuck in the following status, ErrPullImage because the pods cannot pull the images. The images defined in those pods are different from the ones defined in the related StatefulSets. To fix this problem, you need to delete the pods that use the wrong images. The pods restart automatically and should use the correct images.

Revert "Depend on MCH loosely"

---

operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go

- remove namespace check for MCO update
- add `OR` logic for MCH resource update check: the original checks may cause upgrade issue about image replacement.
ref: https://github.com/open-cluster-management/multicluster-observability-operator/pull/754

remove mco namespace check and add mch resource update for managedcluster resources

---

controllers/placementrule/placementrule_controller.go
controllers/placementrule/placementrule_controller_test.go

ref: https://github.com/open-cluster-management/backlog/issues/15996
- add OR logic for MCH resource update check: the original checks may cause upgrade issue about image replacement.

replace image for managedcluster resource for mch update event.

---

operators/multiclusterobservability/manifests/base/alertmanager/alert_rules.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml

This is a follow up PR for: https://github.com/open-cluster-management/multicluster-observability-operator/pull/769
I found no data in CPU Overestimation Panel, because we have updated the prometheus scrape interval in managedcluster from 30s to 5m(300s) in https://github.com/open-cluster-management/multicluster-observability-operator/pull/763.
And the `rate` query need to be at least 4* `$scrape_interval` according to the https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/
What we need to do is using the `$__rate_interval` to replace the old `$__interval`

fix no data in dashboard for rate interval.

---

operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml

As you can see from panel settings, the `merge` transforms actually have no effect for single frame in panels.

remove unused merge transform from cluster overview dashboard.

---

operators/multiclusterobservability/manifests/base/alertmanager/alert_rules.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server-cluster.yaml

This PR will remove the `slo` label from the recording rule. The SLO name is already displayed within the dashboard; therefore, in this contexts, it's not needed.
Related issue: https://github.com/open-cluster-management/backlog/issues/16542

Updated SLO dashboard label and remove SLO name from recording rule

---

operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
operators/multiclusterobservability/controllers/placementrule/endpoint_metrics_operator.go
operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-statefulset.yaml
operators/multiclusterobservability/manifests/base/grafana/deployment.yaml
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/config/config_test.go
operators/multiclusterobservability/pkg/rendering/renderer.go
operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
operators/multiclusterobservability/pkg/rendering/renderer_grafana.go
operators/multiclusterobservability/pkg/rendering/renderer_proxy.go
tests/grafana-dev-test.sh
tests/pkg/tests/observability_grafana_dev_test.go
tools/generate-dashboard-configmap-yaml.sh

Update to use default snapshot for all our owned images. We pass the `mco-imageTagSuffix` in e2e test. but the grafana is still using the `quay.io/openshift/origin-grafana:4.8.0`. This PR is to define the default `DefaultImgTagSuffix` only in config.go. so we can use this default value in case cannot replace the correct images.

Use default snapshot for all our images

---

tests/pkg/utils/mco_managedcluster.go

https://github.com/open-cluster-management/backlog/issues/16823
https://github.com/open-cluster-management/backlog/issues/16230

filter out the managed clusters which not ready in e2e testing

---

operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
operators/multiclusterobservability/controllers/placementrule/manifestwork.go

ref: https://github.com/open-cluster-management/backlog/issues/17727
the root cause for the canary failure is: there are 2 metrics-collector instances running in obs-addon namespace. one is running and the other is terminating. for the terminating pod, the status.phase is running. why there are 2 metrics-collector instances exist? The reason is the endpoint-monitoring-operator does the reconciler to generate the metrics-collector deployment manifests. but the manifest can be different each time, because the map order is random. for example:
the first time for rename order:
```
- --rename="mixin_pod_workload=namespace_workload_pod:kube_pod_owner:relabel"
- --rename="namespace:kube_pod_container_resource_requests_cpu_cores:sum=namespace_cpu:kube_pod_container_resource_requests:sum"
- …
```

fixed order for map

---

manifests/base/config/metrics_allowlist.yaml

There are some metrics renamed in OCP 4.9.
ref: https://github.com/open-cluster-management/backlog/issues/17847

support ocp4.9

---

cicd-scripts/customize-mco.sh
cicd-scripts/setup-e2e-tests.sh
go.mod
go.sum
operators/endpointmetrics/manifests/prometheus/kubernetes-monitoring-alertingrules.yaml
tests/pkg/tests/observability_alert_test.go
tests/pkg/utils/mco_managedcluster.go

Add e2e case for alert forward from openshift clusters, by checking the `Watchdog` alert are forwarded to the hub, because `Watchdog` alert is always triggered, it is used to make sure the alert trigger is working. 
For *KS, add `Watchdog` alertrule to make sure the entire alerting pipeline is functional.

add e2e case for alert forward from managed clusters.

---

cicd-scripts/setup-e2e-tests.sh
tests/pkg/utils/mco_managedcluster.go

This PR addresses the issue left from: https://github.com/open-cluster-management/multicluster-observability-operator/pull/819#issuecomment-966776031
Make sure the SF core component are using latest images so that we have the addon labels for managedclusters.

fix managed cluster labels in KinD env.

---

tests/pkg/utils/utils.go

Run our e2e with GKE managedclusters. we met the following error:
```
•! Panic [30.709 seconds]
Observability:
/share/git/multicluster-observability-operator/tests/pkg/tests/observability_certrenew_test.go:17
[P1][Sev1][Observability][Integration] Should have metrics collector pod restart if cert secret re-generated (ssli/g0) [It]
/share/git/multicluster-observability-operator/tests/pkg/tests/observability_certrenew_test.go:30
Test Panicked
no Auth Provider found for name "gcp"
/share/git/multicluster-observability-operator/tests/pkg/utils/utils.go:65
Full Stack Trace
github.com/open-cluster-management/multicluster-observability-operator/tests/pkg/utils.NewKubeClient({0xc000160258, 0x15}, {0xc000160288, 0x17}, {0x0, 0x0})
```

fix gke auth error

---

operators/multiclusterobservability/pkg/certificates/cert_controller.go

https://github.com/open-cluster-management/backlog/issues/18289

add retry during cert rotation if ca secret update failed

---

controllers/multiclusterobservability/multiclusterobservability_status.go

ref: https://github.com/open-cluster-management/backlog/issues/18418
cherrypick: https://github.com/open-cluster-management/multicluster-observability-operator/pull/733 to release-2.3

[release-2.3] fix stopCheckReady receive signal hang for status update.

---

cicd-scripts/customize-mco.sh
cicd-scripts/run-e2e-tests.sh
cicd-scripts/setup-e2e-tests.sh
tests/pkg/tests/observability_metrics_test.go
tests/pkg/utils/utils.go

This PR tries to filter the `9.9.0-*` snapshot for e2e testing, they are for installer, so they may not contains the latest code.

filter wrong snapshot for e2e testing.

---

manifests/base/alertmanager/alertmanager-statefulset.yaml
manifests/base/proxy/deployment.yaml

the image `quay.io/stolostron/origin-oauth-proxy:2.0.11-SNAPSHOT-2021-04-29-18-29-17` doesn't exist, use the old to pass the e2e testings.

fix oauth-proxy image not found issue.

---

tools/generate-dashboard-configmap-yaml.sh

refer to: https://github.com/stolostron/backlog/issues/18480

Fix unsupported chars for configmap name

---

tests/pkg/tests/observability_observatorium_preserve_test.go

fixed: https://github.com/stolostron/backlog/issues/20231
the root cause is the compact pod is ready with the intermediate stage. and pass the test case `Should revert any manual changes on observatorium cr (observatorium_preserve/g0)`. But the pod will be restarted to reconcile the final state. 
<pre>
manually modify the observatorium CR   ---> revert back by MCO operator
|                                    |
|                                    |
observatorium operator reconcile        observatorium operator reconcile
this intermediate state                 the final state
</pre>

check the compact pod is restarted and ready

---

.github/dependabot.yml

Github dependabot does not require the `vendor` path when updating the go mods. Removing the path will allow for the PRs to create properly.

Removed unneeded vendor for dependabot file

---

pkg/controller/placementrule/placementrule_controller.go

ref: https://github.com/stolostron/backlog/issues/20463
We didn't add default value for observabilityaddon spec in release-2.2, so it will be nil if user doesn't specific the value.
For release-2.3 and beyond, the observabilityaddon spec and default value for EnableMetrics is true, so it will not be a problem.
Signed-off-by: morvencao [lcao@redhat.com](mailto:lcao@redhat.com)

add observabilityaddon spec nil check.

---

collectors/metrics/pkg/collectrule/evaluator.go
collectors/metrics/pkg/collectrule/evaluator_test.go

add the rule name as a label for hash, to handle the case that different rule has same label set

add the rule name as a label for hash

---

tools/simulator/metrics-collector/generate-metrics-data.sh

need to update the `rules` to `recording_rules` in metrics-collector simulator as we have changed that in https://github.com/stolostron/multicluster-observability-operator/pull/940

fix metrics collector simulator.

---

tests/pkg/utils/mco_deploy.go

This PR will replace the slack config webhook URL with the latest webhook URL created.

Updated slack config api url

---

tests/pkg/tests/observability_alert_test.go

Disabling the slack integration test until we figure out a way to securely pass slack hook

Disable alertmanager slack integration test

---

operators/multiclusterobservability/manifests/base/config/managed_cluster_label_allowlist.yaml
proxy/pkg/util/util.go

Related issue: https://issues.redhat.com/browse/ACM-2319

Fixed syntax error in managed-cluster-label-allowlist configmap yaml

---

tests/Dockerfile

Per CICD team, `oc` exists in the builder image. To be compatible across linux and arm builds, copy `oc` from the builder image instead of downloading. This also solves the issue of not having to worry about the version of `oc` to use

use oc from builder image

---

operators/multiclusterobservability/manifests/base/alertmanager/alert_rules.yaml

When thanos-store persistent volumes get full, it does not affect the query. The alert KubePersistentVolumeFillingUp  and should be treated as informational only.

change KubePersistentVolumeFillingUp severity to informational

---

proxy/pkg/config/config.go
proxy/pkg/util/util.go

Updated `rbac-query-proxy` resync to prevent adding the labels `name` and `cluster.open-cluster-management.io/clusterset` to `managedcluster` label ignore list.

[ACM-5782][release-2.8] Added resync for required managedcluster labels

---

proxy/pkg/config/config.go
proxy/pkg/util/util.go

This feature was implemented only in ACM 2.8; therefore, we need to bring it into this current release.

[release-2.9] Added resync for required managedcluster labels (#1207)

---

operators/multiclusterobservability/manifests/base/config/managed_cluster_label_allowlist.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
proxy/pkg/config/config.go
proxy/pkg/util/util.go

Updated `rbac-query-proxy` resync to prevent adding the labels `name` and `cluster.open-cluster-management.io/clusterset ` to `managedcluster` label ignore list.

[ACM-5782][release-2.7] Added resync for required managedcluster labels in allowlist

---

tests/pkg/utils/mco_oba.go

The test case was looking for a status string "Cluster metrics sent successfully". 
```
oc get managedclusteraddons observability-controller -n smeduri-m1 -o json | jq .status.conditions
[
...
{
"lastTransitionTime": "2023-08-16T16:59:28Z",
"message": "Cluster metrics sent successfully",
"reason": "Available",
"status": "True",
"type": "Available"
}
```
However, I found in my experiments that it gets set to that value for a very brief period, and quickly gets overwritten by another update when managed cluster lease is renewed as shown below.  
```
oc get managedclusteraddons observability-controller -n smeduri-m1 -o json | jq .status.conditions
[
...
{
"lastTransitionTime": "2023-08-16T14:52:41Z",
"message": "observability-controller add-on is available.",
"reason": …
```

fix testcase: observability-controller managedclusteraddon status

---

tests/pkg/tests/observability_export_test.go
tests/pkg/utils/mco_oba.go

1. Disable ManagedCluster status message check as it is not reliable
2. Increase wait time for acm_remote_write_requests_total tests from 10 min. to 20 min.

[release-2.8] fix test cases causing intermittent failures

---

tests/pkg/tests/observability_export_test.go
tests/pkg/utils/mco_oba.go

1. Disable ManagedCluster status message check as it is not reliable
2. Increase wait time for `acm_remote_write_requests_total` tests from 10 min. to 20 min.

[release-2.6] fix test cases causing intermittent failures

---

tests/pkg/tests/observability_export_test.go
tests/pkg/utils/mco_oba.go

1. Disable ManagedCluster status message check as it is not reliable
2. Increase wait time for `acm_remote_write_requests_total` tests from 10 min. to 20 min.

[release-2.7] fix test cases causing intermittent failures

---

tools/simulator/metrics-collector/README.md
tools/simulator/metrics-collector/metrics-extractor/.dockerignore
tools/simulator/metrics-collector/metrics-extractor/Dockerfile
tools/simulator/metrics-collector/metrics-extractor/README.md
tools/simulator/metrics-collector/metrics-extractor/extract-metrics-data.sh

We need customers to be able to run this process on their bastion hosts. That by nature should be considered a:
- disconnected env with no internet access
- an immutable machine where we are not allowed to install anything
- but it can run a docker container. The docker container can be copied over to the customer's internal repo/artifactory.
The changes just allows that. And uses a simpler version of the old script that was created.

modifying the metrics extraction process

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
operators/multiclusterobservability/pkg/config/config.go

PRs https://github.com/stolostron/release/pull/508, https://github.com/stolostron/release/pull/509 and https://github.com/stolostron/release/pull/510 which were done to eliminate seeming dulicatoin/overlap were in error, and removed needed keys. This probably came about because of the close naming of the prometheus_config_reloader and prometheus-config-reloader keys, which suggested they were two entries for the same image, but they were not.
1. `prometheus_config_reloader` is a key that points to an ACM-built image for a Prometneus-specific image that triggers reloading on changes to Prometheus config info.
2. `configmap_reloader` is a key that points to an external (from Openshift) image that is not specific to Prometheus and causes containers to be restarted on changes to ConfigMaps or …

Rename OpenShift configmap reloader key to configmap_reloader

---

examples/export/v1beta2/custom-certs/observability.yaml
examples/export/v1beta2/observability.yaml
examples/mco/e2e/v1beta2/custom-certs/observability.yaml
examples/mco/e2e/v1beta2/observability.yaml
examples/policy/resourceQuota.yaml
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
operators/multiclusterobservability/pkg/config/config.go
sonar-project.properties
tests/pkg/tests/observability_addon_test.go

1. backport [PR 519](https://github.com/stolostron/release/pull/519)
2. Bump receives to 3 for e2e tests to ensure quorum on newer Thnaos versions
3. increase resource quota on open-cluster-management-observability from 12Gi -> 16Gi as receive pods are getting OOMKilled in e2e tests
4. Exclude tests folders from sonar scans

[release-2.8] rename openshift configmap reloader key

---

operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml

Adding 2 key metrics for cluster service version aka operators that are added in the newer OCP. I did not check when they were added.
They are :
- csv_succeeded
- csv_abnormal. Well the number of failed can be derived from csv_succeeded, but reasons are not mentioned.
There are a few other which I did not choose. 
- csv_count can be derived from count(csv_succeeded)
- csv_upgrade_count : not sure how useful it is.
We are getting a lot of requests from customers about operator health. So makes sense to add them out of the box. Since they can be added to custom-allow-list anyway, did not work on back porting

2 key csv metrics in newer ocp

---

examples/export/v1beta2/custom-certs/observability.yaml
examples/export/v1beta2/observability.yaml
examples/mco/e2e/v1beta2/custom-certs/observability.yaml
examples/mco/e2e/v1beta2/observability.yaml
examples/policy/resourceQuota.yaml
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
operators/multiclusterobservability/pkg/config/config.go
sonar-project.properties
tests/pkg/tests/observability_addon_test.go

1. backport [PR 519](https://github.com/stolostron/release/pull/519)  
2. Bump receives to 3 for e2e tests to ensure quorum on newer Thnaos versions
3. increase resource quota on `open-cluster-management-observability` from `12Gi` -> `16Gi` as receive pods are getting OOMKilled in e2e tests
4. Exclude `tests` folders from sonar scans

[release-2.7] rename openshift configmap reloader key

---

operators/multiclusterobservability/controllers/placementrule/manifestwork.go

When MCO CR defines NodeSelectors and Tolerations they should only be applied on the hub observability components. However, the code that generates endpoint operator deployment in the ManifestWork is reused across multiple managed clusters, and is inheriting settings from local-cluser and applying them to managed clusters.
The fix addresses it by resetting NodeSelectors and Tolerations in the template before evaluating they should be set.

[ACM-6774] reset endpoint deployment node selectors and tolerations 

---

operators/multiclusterobservability/controllers/placementrule/manifestwork.go

When MCO CR defines NodeSelectors and Tolerations they should only be applied on the hub observability components. However, the code that generates endpoint operator deployment in the ManifestWork is reused across multiple managed clusters, and is inheriting settings from local-cluser and applying them to managed clusters.
The fix addresses it by resetting NodeSelectors and Tolerations in the template before evaluating they should be set.

[ACM-6774] [release-2.7] reset endpoint deployment node selectors and tolerations

---

operators/multiclusterobservability/controllers/placementrule/manifestwork.go

When MCO CR defines NodeSelectors and Tolerations they should only be applied on the hub observability components. However, the code that generates endpoint operator deployment in the ManifestWork is reused across multiple managed clusters, and is inheriting settings from local-cluser and applying them to managed clusters.
The fix addresses it by resetting NodeSelectors and Tolerations in the template before evaluating they should be set.

[ACM-6774] [release-2.8] reset endpoint deployment node selectors and tolerations

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/pkg/deploying/deployer.go

The update() call requires PrometheusRule object to have the same resourceVersion.

[ACM-7594] Set prometheusRule resource version before calling update

---

tools/simulator/metrics-collector/metrics-extractor/Dockerfile
tools/simulator/metrics-collector/metrics-extractor/extract-metrics-data.sh

Customer complained that the docker container was making curl calls to the internet. So, this enhancement cuts out the dynamic call to the allow list caching it during the docker build tIme. This is needed because lot of our customers will run this from their bastion host which does not have any connection to the internet

cutting out curl call during runtime

---

operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/multiclusterobservability/controllers/placementrule/obsaddon_test.go

When MCO CR defines `NodeSelectors` and `Tolerations` they should only be applied on the hub observability components. However, the code that generates endpoint operator deployment in the ManifestWork is reused across multiple managed clusters, and is inheriting settings from `local-cluser` and applying them to  managed clusters.
The fix addresses it by resetting NodeSelectors and Tolerations in the template before evaluating they should be set.

[ACM-7015] [release-2.6] reset endpoint deployment node selectors and tolerations

---

tests/pkg/tests/observability_alert_test.go
tests/pkg/utils/mco_deploy.go

Addresses security warning: https://sonarcloud.io/project/issues?cleanCodeAttributeCategories=RESPONSIBLE&resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&id=open-cluster-management_multicluster-observability-operator&open=AYr6ft-3o5uI1zgddFao&tab=code

Remove AM integration test function with slack hook url

---

.golangci.yml
collectors/metrics/cmd/metrics-collector/main.go
collectors/metrics/pkg/forwarder/forwarder.go
operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
operators/endpointmetrics/pkg/util/lease.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/role.go
operators/multiclusterobservability/pkg/certificates/cert_agent.go
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/rendering/renderer_proxy.go
operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
operators/multiclusterobservability/pkg/util/managedclusteraddon.go
operators/pkg/config/config.go
proxy/cmd/main.go
tests/pkg/utils/mco_dashboard.go
tests/pkg/utils/mco_deploy.go
tests/pkg/utils/mco_metric.go

Enable `gosec` as linter and resolve certain potential security issues. Should also fix sonarcloud checks.

Enable `gosec` as a linter and resolve potential security issues

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func.go
operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func_test.go
operators/multiclusterobservability/pkg/config/config.go

- set {{openshift.io/cluster-monitoring=true }}label on `open-cluster-management-observability` namespaces
- Moved the predicate functions to a new file
- Added test cases for Predicate functions
https://issues.redhat.com/browse/ACM-7631

add Cluster monitoring label 

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
operators/multiclusterobservability/manifests/base/alertmanager/prometheusrule.yaml
operators/multiclusterobservability/pkg/servicemonitor/sm_controller.go

- Remove Prometheus Rules from openshift-montioring namespace
- Remove Service Monitors from openshift-montioring namespace
- Change ns for the creation of service account
https://issues.redhat.com/browse/RHOBS-920

Remove prom rules and Service Monitor  from openshift monitoring namespace

---

collectors/metrics/pkg/metricfamily/hypershift_transformer.go
loaders/dashboards/pkg/util/grafana_util.go
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
proxy/pkg/util/util.go
tests/pkg/utils/mco_pods.go
tests/pkg/utils/utils.go

This PR addresses the following issues
1. [ACM-4384](https://issues.redhat.com/browse/ACM-4384) - defer unsafe close vulnerability
2. Adds a diagnostic message when MCO reconcile is skipped waiting for MCH CR to be ready (upgrade)
3. Miscellaneous warnings
CC: @bjoydeep @berenss - (2) should help diagnose MCO reconcile wasn't working as we saw in in ROSA HCP env

[ACM-4384] defer unsafe Close vulnerability

---

operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go

Sets `max_source_resolution=auto` in the Grafana datasource's `customQueryParameters`. This should force the underlying Thanos Query Frontend to perform additional queries for downsampled data in case of empty responses.

[ACM-3748] Set max source resolution to auto in Grafana datasource

---

operators/endpointmetrics/pkg/util/lease.go
operators/multiclusterobservability/controllers/placementrule/role.go
operators/multiclusterobservability/pkg/certificates/cert_agent.go
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/rendering/renderer_proxy.go
operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
operators/multiclusterobservability/pkg/util/managedclusteraddon.go

Mostly a cherry pick of the `gosec` false-positives skips from #1259.

Clear `gosec` false positives

---

README.md
REMEDIATE.md

This should pick up a newer version of the image-builder, with an updated `gosec`. With this new version it should properly skip a false-positive that previous versions don't ignore.

Rebuild image to fix `gosec` scan results in SonarCloud

---

collectors/metrics/Dockerfile
loaders/dashboards/Dockerfile
operators/multiclusterobservability/bundle.Dockerfile
proxy/Dockerfile
tests/Dockerfile
tools/simulator/metrics-collector/Dockerfile
tools/simulator/metrics-collector/metrics-extractor/Dockerfile

The objective is to clear out all [the security hotspots from project as reported by SonarCloud](https://sonarcloud.io/project/security_hotspots?id=open-cluster-management_multicluster-observability-operator.).

Non-root containers 

---

operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
operators/multiclusterobservability/config/rbac/mco_role.yaml
operators/multiclusterobservability/controllers/placementrule/role.go

`patch` permission is a prerequisite to upgrading add-on framework to new version in 2.8/2.7 service stream
CC: @dislbenn A new install PR similar to [PR 1169](https://github.com/stolostron/multiclusterhub-operator/pull/1169) would be required in service stream

[release-2.8] add patch permission to mco role

---

operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
operators/multiclusterobservability/config/rbac/mco_role.yaml
operators/multiclusterobservability/controllers/placementrule/role.go

patch permission is a prerequisite to upgrading add-on framework to new version in 2.8/2.7 service stream
CC: @dislbenn A new install PR similar to [PR 1169](https://github.com/stolostron/multiclusterhub-operator/pull/1169) would be required in service stream

[release-2.7] add patch permission to mco role

---

collectors/metrics/Containerfile.operator
loaders/dashboards/Containerfile.operator
operators/endpointmetrics/Containerfile.operator
operators/multiclusterobservability/Containerfile.operator
proxy/Containerfile.operator
tests/Containerfile.operator
tools/simulator/alert-forward/Containerfile.operator
tools/simulator/metrics-collector/metrics-extractor/Containerfile.operator

Required by [ACM-7181](https://issues.redhat.com/browse/ACM-7181)
change builder image to: brew.registry.redhat.io//rh-osbs/openshift-golang-builder:rhel_8_1.20

Create Containerfile.operator files in preparation to move to RHTAP

---

cicd-scripts/install-dependencies.sh
operators/endpointmetrics/config/default/kustomization.yaml
operators/multiclusterobservability/Makefile
operators/multiclusterobservability/PROJECT
operators/multiclusterobservability/bundle.Dockerfile
operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_observabilityaddons.yaml
operators/multiclusterobservability/bundle/metadata/annotations.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml
operators/multiclusterobservability/config/crd/kustomization.yaml
operators/multiclusterobservability/config/default/kustomization.yaml
operators/multiclusterobservability/config/manager/kustomization.yaml
operators/multiclusterobservability/config/manifests/bases/multicluster-observability-operator.clusterserviceversion.yaml
operators/multiclusterobservability/config/manifests/kustomization.yaml
operators/multiclusterobservability/config/webhook/kustomization.yaml

This PR upgrades operator-sdk, controller-gen, and kustomize, and changes operator-sdk config from version 3-alpha to 3.
Most changes expect Makefile and PROJECT files are automatic.
Helps run `make bundle` reliably locally.

Upgrade operator-sdk, controller-gen and kustomize with latest configs

---

cicd-scripts/install-dependencies.sh
operators/multiclusterobservability/Makefile
operators/multiclusterobservability/PROJECT
operators/multiclusterobservability/bundle.Dockerfile
operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_observabilityaddons.yaml
operators/multiclusterobservability/bundle/metadata/annotations.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml
operators/multiclusterobservability/config/manifests/bases/multicluster-observability-operator.clusterserviceversion.yaml
operators/multiclusterobservability/config/rbac/role.yaml
operators/multiclusterobservability/config/webhook/manifests.yaml

As per our conversation in https://redhat-internal.slack.com/archives/CUU609ZQC/p1702291437678999 we need to maintain older versions of these, on OpenShift 3.11 and thus support older clusters. Deferring the upgrade done in #1291 for later

Revert operator-sdk, controller-gen upgrade

---

collectors/metrics/pkg/metricsclient/metricsclient.go

While this is a 4xx statuscode, it is important to log errors, and not log "metrics pushed successfully", as the request did fail.

Ensure conflict status errors are surfaced in metrics-collector

---

collectors/metrics/Containerfile.operator
loaders/dashboards/Containerfile.operator
operators/endpointmetrics/Containerfile.operator
operators/multiclusterobservability/Containerfile.operator
proxy/Containerfile.operator
tools/simulator/alert-forward/Containerfile.operator

Required by [ACM-7181](https://issues.redhat.com/browse/ACM-7181)
The golang builder defaults to vendor. Need to set GOFLAGS to empty string for RHTAP builds.

Set GOFLAGS to empty string for RHTAP builds

---

operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
operators/multiclusterobservability/controllers/placementrule/predicate_func.go
operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
operators/multiclusterobservability/pkg/config/config.go

https://issues.redhat.com/browse/RHOBS-949
https://issues.redhat.com/browse/ACM-8312
From what I understand is that the placement controller has no logic to watch over the changes to addondeployment config. So any update to it will not be picked up by managerclusteraddon and clustermanagementaddon which are watched already but they only hold a ref to addondeploymentconfig and not the actual config.
The PR adds the watch logic in the placement controller to monitor changes in addondeployment config and sets up the request to reconcile and also apply change to all managed clusters

add watch logic for addondeployment

---

operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
operators/multiclusterobservability/controllers/placementrule/predicate_func.go
operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
operators/multiclusterobservability/pkg/config/config.go

https://issues.redhat.com/browse/ACM-8312
Back port  [PR 12890](https://github.com/stolostron/multicluster-observability-operator/pull/1289) to ACM 2.9 (cherry pick commit 7fb7465a8008f1ba0289a1d27f9f96ea36a8d15f)
* add watch logic for addondeployment
* make sonarcloud happy
* lint
* refactor predicate
* lint
* fix test case
* refactor

[release-2.9] add watch logic for addondeployment (#1289)

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_status.go

Fix race condition in mco controller StartStatusUpdate function.

[ACM-8259] fix mco status update race condition

---

OWNERS

This commit adds everyone in the team as approvers in the owners file.

Owners: Add full MultiCluster Observability Team

---

operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml

- The MCO CRDs was not re-generated correctly following an update to the API definition (doc/comment)
- The observatorium CRD was not correctly updated in the bundle.
(this is the result of running `make bundle`)

Update MCO CRDs

---

operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-hcp-overview.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-resources-hcp.yaml

This is for story https://issues.redhat.com/browse/ACM-9018 to add two new grafana dashboards.
- `ACM - Hosted Control Planes Overview` dashboard to show the cluster's capacity estimate for hosting hosted control planes and the related cluster resources.
- `ACM - Resources - Hosted Control Plan` dashboard that users can drill down from the overview page to see the resource utilizations of the selected hosted control plane.

ACM-9018: Add hosted control plane overview and resources dashboards

---

operators/multiclusterobservability/manifests/base/proxy/ingress.yaml

Per https://issues.redhat.com/browse/OCPBUGS-18537, define .spec.ingressClassName so IngressWithoutClassName alert does not fire.

[ACM-9321] Stop firing IngressWithoutClassName alert

---

operators/multiclusterobservability/manifests/base/alertmanager/prometheusrule.yaml

This is a first pass at making this alert less noisy without introducing too much change on it initially.  
An alert should be actionable but in many cases here, the response codes can be in the 4xx unrecoverable range which means the alert can fire when essentially there is no data loss or the customer cannot intervene.
https://issues.redhat.com/browse/ACM-4820

alert: make ACMRemoteWriteError less prone to flakes/flapping

---

operators/multiclusterobservability/manifests/base/grafana/dash-acm-hcp-overview.yaml

One of the queries needs to be fixed to use an instant time series value.

fix a metric query to use instant value

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go

This should make the CR's hash change. As the CR's hash is used to annotate the Observatorium API pods, these will be rolled out and pick up any new value from the configmaps or secrets.

[ACM-8543] Tag Observatorium CR with a hash of all the config it uses

---

operators/endpointmetrics/pkg/util/client.go
operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/predicate_func.go
operators/multiclusterobservability/main.go
operators/multiclusterobservability/pkg/config/config.go

* install Metrics Without Addon
* install Metrics Without Addon
* install Metrics Without Addon
* modify endpoint operator
* modify endpoint operator
---------

First drop: Hub metrics collector feature  (#1314)

---

collectors/metrics/test/integration/manifests/observatorium-api.yaml

- Follows on from https://github.com/stolostron/multicluster-observability-operator/pull/1304
- Depends on https://github.com/stolostron/observatorium/pull/78

Adjust server timeouts to align with default Grafana settings

---

operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
operators/multiclusterobservability/pkg/certificates/cert_controller.go
tests/pkg/tests/observability_certrenew_test.go
tests/pkg/utils/mco_cert_secret.go

Changes to the config hash approach:
* Gave up on hashing the secrets (mostly certs): they are already used by the embed `certcontroller` to add a label to the `observatorium-api` and its `kube-rbac-proxy` sidecar. I prefer to avoid the concurrency issue that comes with updating the Observatorium CR, which will also trigger the Observatorium pods to change. 
Ideally this mechanism should live outside of the `certcontroller`. It's already watching for **all** secrets in the operator's namespace -- not only certificates. It could also be made to watch configmaps.
* I changed such mechanism above to use an `strategicMerge` **patch** instead of full update, as it only adds a label to a list.

[ACM-8543] Fix reconciliation on Observatorium CR for update scenario

---

.gitignore
Makefile
cicd-scripts/customize-mco.sh
cicd-scripts/run-e2e-in-kind-via-prow.sh
cicd-scripts/setup-e2e-tests.sh
scripts/install-binaries.sh
scripts/test-utils.sh
tests/run-in-kind/run-e2e-in-kind.sh

Updates the KinD version and refactors some of the e2e test scripts to removing duplication.
We now fetch all test dependencies early and copy them into the ec2-users PATH.
Prior, we were duplicating the installs as the ec2-user post ssh so there was a potential to fail later in the test if those downloads failed. This change avoids that and allows us to fail the e2e tests early if the scp fails for any reason.

Kind version

---

operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/multiclusterobservability/controllers/placementrule/predicate_func.go
operators/multiclusterobservability/pkg/certificates/certificates.go

https://issues.redhat.com/browse/ACM-10153
- Toggling hubselfmanagement multiple times creates addon-observability namespace in hub cluster intermittently. This PR ensure we skip any reconcile in MCO touching local-cluster object
- Update hub metrics collections resources when modified

Update hub metrics collection resources when modified

---

operators/multiclusterobservability/controllers/placementrule/manifestwork.go

This change creates a Secret for the Grafana Accessor ServiceAccount if there was not previously one generated by the platform.
As per [OCP documentation](https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-legacy-service-account) - we should not rely on Secrets generated by the underlying control plane since these may go away.
This behaviour is protected with `LegacyServiceAccountTokenNoAutoGeneration` feature gate and hence it makes sense to ensure that we force the generation of said Secret and token which we depend on.

[ACM-10234]Create a Secret for Grafana Accessor SA if not auto-generated

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go

https://issues.redhat.com/browse/ACM-10232
https://issues.redhat.com/browse/ACM-10274
- Do not delete managedcluster addon for local-cluster
- Make sure Observability stack is not deployed when global hub is enabled

[ACM 10232, 10274] Keep managedclusteraddon for local-cluster 

---

DEVELOPMENT.md
Makefile
cicd-scripts/customize-mco.sh
cicd-scripts/run-e2e-in-kind-via-prow.sh
cicd-scripts/run-e2e-tests.sh
cicd-scripts/setup-e2e-tests.sh
operators/multiclusterobservability/Dockerfile.dev
scripts/bootstrap-kind-env.sh
scripts/test-utils.sh
tests/pkg/tests/observability_install_test.go
tests/pkg/utils/utils.go

The focus on this change which is a follow up to #1353 , #1359, #1360, #1361, #1362 is to allow running the KinD end-to-end tests in all environments and provide a sensible refactor to the underlying bash scripts.
It attempts to split the logic into the following:
1. Cluster bootstrap
2. ACM setup
3. Test run
as opposed to the previous target which setup and kicked off everything but was difficult to break down and assess during test runs.
It also adds an additional Dockerfile which does not require access to the Red Hat CI registry in order to develop on.
The following is out of scope here but will be added in follow up(s):
1. Docs explaining how to build and use local image in e2e tests
2. Targets, scripts and docs for developing the metrics collector
3. Clean up after test artifacts in …

e2e testing changes

---

operators/multiclusterobservability/controllers/placementrule/manifestwork.go

This change creates a Secret for the Grafana Accessor ServiceAccount if there was not previously one generated by the platform.
As per [OCP documentation](https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-legacy-service-account) - we should not rely on Secrets generated by the underlying control plane since these may go away.
This behaviour is protected with LegacyServiceAccountTokenNoAutoGeneration feature gate and hence it makes sense to ensure that we force the generation of said Secret and token which we depend on.

[ACM-10261] Create a Secret for Grafana Accessor SA if not auto-generated

---

operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/pkg/config/config.go

There's no other way to fetch the observability addon spec from the metrics collector in the Hub besides querying the kube API for it. 
This fixes the synchronization of the MCO's observability addon spec to the hub's collector.
Important note: with these changes, the Hub's metrics collector will abide to the `metricsEnabled` setting of the `ObservabilityAddon` spec.

[ACM-10511] Update hub collector with the whole obs addon spec

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/predicate_func.go
operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
operators/multiclusterobservability/main.go

This cherry picks #1376 into the 2.10 release stream.
Fix in the addon deployment config predicate: we should not only compare the proxy config, but the whole spec, and trigger a reconciliation if anything has changed there.
Fix in the placement rule controller: whenever starting the loop for fetching a new default addon deployment config, reassign the result var to an empty config. We only change it from empty if we find any.

[2.10] [ACM-10406] Fix handling of updates on AddOnDeploymentConfig 

---

operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/main.go

This backports #1391 into the 2.10 release stream.

[ACM-10811] [2.10] Fix lack of reconciliation of hub's metrics collector 

---

operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-overview.yaml

This PR add the "ACM - OpenShift Virtualization Overview" dashboard that shows details related to the OpenShift Virtualization operator and Virtual machines.

Add ACM - OpenShift Virtualization Overview dashboard

---

operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/predicate_func.go
operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
operators/multiclusterobservability/main.go

This backports #1389 to the 2.9 release stream.
Fix in the addon deployment config predicate: we should not only compare the proxy config, but the whole spec, and trigger a reconciliation if anything has changed there.
Fix in the placement rule controller: whenever starting the loop for fetching a new default addon deployment config, reassign the result var to an empty config. We only change it from empty if we find any.

[ACM-10809] Fix handling of updates on AddOnDeploymentConfig

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/multiclusterobservability/pkg/certificates/certificates.go

https://issues.redhat.com/browse/ACM-10342
ClientCACertificateCN is used to sign in the Certificate Signing Request to generate the Client cert (`observability-controller-open-cluster-management.io-observability-signer-client-cert`)  so when ClientCACertificateCN is deleted or updated we need to also update the client cert.

[ACM-10342]update metrics collector client cert when client CA is deleted

---

operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/main.go
operators/endpointmetrics/manifests/prometheus/prometheus-operator-role.yaml
operators/endpointmetrics/pkg/rendering/renderer.go
operators/endpointmetrics/pkg/rendering/renderer_test.go
operators/multiclusterobservability/manifests/endpoint-observability/role.yaml
operators/pkg/deploying/deployer.go

Enables the endpoint operator to deploy resources on a microshift spoke.
Changes:
- Add necessary permissions for setting finalizers on deployed resources (needs finalizer updates perm on oba which is the referenced owner)
- Sort deployed resources so that needed permissions are deployed first, then needed CRDs, etc.
- Add some other missing perm for prometheus
- Remove noisy logs from the IBM filteredcache by only watching MCO resource when on the hub
- Clean some badly formatted logs in deploy

ACM-10828: sort resources for microshift install

---

operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/config/config_test.go

This is supposed to cover cases where there is some sort of intermediate component, like but not limited to a reverse proxy, between the spokes and the Observatorium API Route in the hub.
I decided to add a new field to the MCO CR's advanced config instead of using AddOnDeploymentConfig's custom variables because that's how we customize other things in the MCO. This way the configuration stays all in one place, avoiding any possible user confusion or extra cognitive load.

[ACM-10706] Add support for custom observability hub URL

---

operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/pkg/util/status.go
operators/endpointmetrics/pkg/util/status_test.go

In some cases, while the metrics collector is well deployed in the spoke, the addon status remains in progressing state on the hub. After having modified the part that reflects the local observability addon state to the hub in https://github.com/stolostron/multicluster-observability-operator/pull/1420, this PR modifies the code that updates the local observability addon on the spoke:
- Adds retry logic in case of conflicts
- Avoids overriding the whole the status.Conditions list with the latest one
- Limits the number of status.Conditions to 10.
It also removes some weird stuff like the `reportStatus bool` function parameter in the reportStatus function 😅

[ACM-10812]: retry status update on conflict

---

examples/export/v1beta2/custom-certs/observability.yaml
examples/export/v1beta2/observability.yaml
examples/mco/e2e/v1beta2/custom-certs/observability.yaml
examples/mco/e2e/v1beta2/observability.yaml
tests/pkg/tests/observability_export_test.go

Previously the test "Should have acm_remote_write_requests_total metrics with correct labels/value" looked for the metric for both the hub cluster and any spokes. However, **per my understanding** the spokes isn't supposed to expose this metric, hence the test would always fail if any managed clusters were added to the test setup.

Tests: Don't check remote_write_requests on spokes 

---

operators/multiclusterobservability/controllers/placementrule/manifestwork.go

Adds backoff retry logic on calls updating manifest works in the hope it removes many errors we see in the mco operator logs from the placement_rule controller.
Exemple:
```
2024-05-06T09:12:01.020Z        ERROR   controller_placementrule        Failed to update monitoring-endpoint-monitoring-work work       {"error": "Operation cannot be fulfilled on manifestworks.work.open-cluster-ma
nagement.io \"miroshift-clusterbot6-observability\": the object has been modified; please apply your changes to the latest version and try again"}
```

Retry manifest work update on conflict

---

operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml

We add this metric to the allowlist as it will be used to optimize dashboard performance for the fleet wide CPU widgets.
The recording rule is already added to *ks clusters here: https://github.com/stolostron/multicluster-observability-operator/blob/7ed36704b0e67ec7b9ac9ea5213c51516475f04f/operators/endpointmetrics/manifests/prometheus/prometheusrules/kube-prometheus-node-recording.yaml#L24
The rule is slightly different from the the statistics we currently use in the dashboard. Before we counted everything except `idle` cpu as "cpu utilization", while this rule also excludes `iowait` and `streal`, this aligns with how i.e node-exporter handle things, more info in the commit message here: https://github.com/prometheus/node_exporter/commit/3e6f4ce627e588e9972e624f1f744c716e11b199

Add `cluster:node_cpu:ratio` to allowlist

---

tests/Dockerfile

The canary builds run e2e tests in a containerized env, and the user 1001 does not have access to /opt path.
Change kubeconfig path to /workspaces instead so user can access it.
Complimentary [PR 301](https://github.com/stolostron/canary-scripts/pull/301)  in canary-scripts repo that invokes the containerized image

[release-2.9] Relocate kubeconfig for non-root user access

---

tests/Containerfile.operator
tests/Dockerfile

Address the canary failure
Status: Downloaded newer image for quay.io/stolostron/observability-e2e-test:2.11.0-SNAPSHOT-2024-05-17-08-37-07
--- FAIL: TestObservabilityE2E (0.01s)
panic: error loading config file "/workspace/.kube/config": open /workspace/.kube/config: permission denied [recovered]
panic: error loading config file "/workspace/.kube/config": open /workspace/.kube/config: permission denied

Precreate and set permissions for /workspace/.kube directory

---

tests/Dockerfile

Address the canary failure
Status: Downloaded newer image for quay.io/stolostron/observability-e2e-test:2.11.0-SNAPSHOT-2024-05-17-08-37-07
--- FAIL: TestObservabilityE2E (0.01s)
panic: error loading config file "/workspace/.kube/config": open /workspace/.kube/config: permission denied [recovered]
panic: error loading config file "/workspace/.kube/config": open /workspace/.kube/config: permission denied

[release-2.9] Precreate and set permissions for workspace kube dir

---

tests/Containerfile.operator
tests/Dockerfile

The canary builds run e2e tests in a containerized env, and the user 1001 does not have access to /opt path.
Change kubeconfig path to /workspaces instead so user can access it.
Complimentary [PR 300](https://github.com/stolostron/canary-scripts/pull/300) in canary-scripts repo that invokes the containerized image

[release-2.10] Relocate kubeconfig for non-root user access

---

operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/controllers/placementrule/hub_info_secret.go
operators/multiclusterobservability/controllers/placementrule/hub_info_secret_test.go
operators/multiclusterobservability/controllers/placementrule/mco_predicate.go

Previously the URL's path was being ignored in the code that built the additional cluster monitoring configuration. 
I also made the code handle URLs without protocol as being `https://` by default. This has been the only supported protocol anyway as it was previously prepended to all the hosts when the protocol was omitted.

[ACM-11722] Add support for alertmanager path prefix and validate URL

---

operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
operators/multiclusterobservability/config/manager/manager.yaml

When the memory limit of MCO was bumped from 1Gi to 2Gi in c3e1e947854f3d711afaeccc814e0951a0158af6 it was updated only in the generated manifests, and not source used to generate said manifests. As a result, when we ran `make bundle` the limit was reverted. This was done in e97c825b579398bb68f76c114c62dbec60927ab1 (note this was later partially reverted in d74277862ebb83f14cdca85644aea486aa7b59a2 but the memory limit was not). The end result was the limit being lowered from 2Gi to 1Gi again causing problems on systems with a large number of managed clusters.
In this commit we raise the limit to 3Gi. 3Gi might seem like a high limit, however we occasionally saw OOMs with a 2Gi limit on large perfscale tests. Further, since 2.9 we no longer have any sensible ways to increase these limits …

Bump MCO memory limit to 3Gi

---

operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
operators/multiclusterobservability/controllers/placementrule/hub_info_secret.go
operators/multiclusterobservability/controllers/placementrule/hub_info_secret_test.go
operators/multiclusterobservability/pkg/certificates/certificates.go
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/config/config_test.go

When using a custom observability hub URL, the only SSL termination mode supported is **passthrough**, which means the certificates must still be signed with the Route's host in the SAN field. 
We **never** want the custom URL in any SAN.
**Implementation detail**
I separated the original code into two functions: one that gets the URL for access and another one that gets the URL for the cert's SAN field.

[ACM-11543] Do not add custom obs api url to certs SAN

---

operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
operators/multiclusterobservability/config/manager/manager.yaml

When the memory limit of MCO was bumped from 1Gi to 2Gi in c3e1e947854f3d711afaeccc814e0951a0158af6 it was updated only in the generated manifests, and not source used to generate said manifests. As a result, when we ran `make bundle` the limit was reverted. This was done in e97c825b579398bb68f76c114c62dbec60927ab1 (note this was later partially reverted in d74277862ebb83f14cdca85644aea486aa7b59a2 but the memory limit was not). The end result was the limit being lowered from 2Gi to 1Gi again causing problems on systems with a large number of managed clusters.
In this commit we raise the limit to 3Gi. 3Gi might seem like a high limit, however we occasionally saw OOMs with a 2Gi limit on large perfscale tests. Further, since 2.9 we no longer have any sensible ways to increase these limits …

2.10: Bump MCO memory limit to 3Gi

---

cicd-scripts/setup-e2e-tests.sh
operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview-optimized.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml
tests/pkg/tests/observability_dashboard_test.go

This optimized dashboard mainly lowers the cardinality of the CPU
metrics. Specifically instead of using `avg(rate(node_cpu_seconds_total`
which has a cardinality of total CPUs across all managed clusters, we
instead use `cluster:node_cpu:ratio` which has a cardinality of 1 per
cluster.
That is with 100 clusters, with 16 CPUs, the cardinality before was
100*16 = 1600, where as with this change we now only fetch 100 metrics.
This should scale quite a bit better on larger installations with many
clusters/nodes.

Add optimized grafana dashboard

---

operators/multiclusterobservability/controllers/placementrule/hub_info_secret.go

For the reverse proxy/LB support, the remote write endpoint could be under a custom path prefix (i.e. `host:port/custom-path//api/metrics/v1/default/api/v1/receive`). 
We can't hardcoded the path directly to `/api/metrics/v1/default/api/v1/receive`. So the best way forward if to append this path to the url as a string, unless it's already present, then parse it into an `url.URL`.

[ACM-11543] Check if URL already contains remote write path before appending it

---

cicd-scripts/customize-mco.sh

Previously, we tried to cleverly decide which tests to run on PRs. However this is error prone, and has recently allowed code to be checked in which broke a test for almost 4 months. This due the said test not being included in any of the Ginkgo focus tags selected.
While this will use more resources, it's less error prone, and we ensure we cannot checkin code that breaks tests.

Tests: Only set ginkgo focus in kind tests

---

cicd-scripts/customize-mco.sh
scripts/test-utils.sh

- Always use the CI images we built during tests, don't rely on trying to get a resonable snapshot from quay
- Improve our chances of getting a resonable recent snapshot on quay for images we don't build as part of MCO (like grafana).
More details in individual commits

Tests: Use CI images, and improve getting snapshot from Quay

---

operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview-optimized.yaml
operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml
tests/pkg/tests/observability_dashboard_test.go

Backports the optimized grafana dashboard to 2.10 as well. Note this doesn't include the following change to the normal (not-optimized) dashboard, to minimize any risk (albeit minimal): https://github.com/stolostron/multicluster-observability-operator/pull/1454/commits/3fec4780aef6724d83272177458292a8710b7109

[release-2.10] Backport optimized grafana dash

---

go.mod
operators/multiclusterobservability/pkg/certificates/cert_agent.go
operators/multiclusterobservability/pkg/certificates/cert_agent_test.go
operators/multiclusterobservability/pkg/certificates/cert_controller.go
operators/multiclusterobservability/pkg/certificates/test_helpers.go

This should trigger a reprocessing of the CSR whenever the CA changes.

[ACM-10269] Stamp CSR's organization units with the hash of the CA bundle

---

operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
operators/multiclusterobservability/controllers/placementrule/manifestwork.go

Everytime we create an Observatorium CR we create a new tenantID for `default` tenant and then ensure that the tenant ID is the same as the ID created the first time. Because of which the comparison in old and new spec differs and we update the spec again although nothing has changed.

Prevent unnecessary update of observatorium in MCO

---

operators/multiclusterobservability/pkg/certificates/certificates.go

If we have an intermediate component, like a load balancer, between Observatorium API and the metrics-collector, we need that component's URL to be part of the SANs.

Add Observatorium API's external host to tls certs SAN

---

operators/multiclusterobservability/Dockerfile.dev

Updating since the bump in prom versions means newer prometheus 0.51 requires go 1.21

docker: Update sha for ubi image in dev dockerfile

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func.go

`config.SetMonitoringCRName` and `config.GetMonitoringCRName` are the functions used to get and set, respectively, the global with the MCO CR name.
I noticed though the name was only set in the `CreateFunc` of the MCO predicate. This meant that if the MCO controller was not running when the MCO CR was created, nothing would set the CR name. 
I detected this because it would cause an issue in the `config.GetObsAPIExternalHost` function.
Considering that `config.GetMonitoringCRName` is used in many places throughout the code, it must be causing lots of problems.

Fix code setting global var with the MCO CR name

---

operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
operators/multiclusterobservability/controllers/placementrule/hub_info_secret.go
operators/multiclusterobservability/pkg/certificates/certificates.go
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/config/config_test.go

Basically updated `GetObsAPIExternalHost` and `GetAlertmanagerEndopint` to return a `url.URL` instead of string and updated the code accordingly.

Make URL handling safer and less wasteful

---

operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/pkg/util/status.go
operators/endpointmetrics/pkg/util/status_test.go

I previously made a change to use the conditions as an history log, but this is not possible.
This PR reverts to in-place update of status conditions for the addon on the spoke.

ACM-11985: fix addon status update

---

operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/pkg/util/obj_compare.go

Endpoint operator deployment kept getting updated despite having the same spec causing the manifestwork to update and keep reconciling and restarting the endpoint operator 
The changes to the endpoint operator spec  specific to spokes or local-cluster were getting added to a global variable `endpointMetricsOperatorDeploy` and this was causing the manifestworks to differ
https://issues.redhat.com/browse/ACM-12023
Follow up commit after -> https://github.com/stolostron/multicluster-observability-operator/pull/1477

Ensure MCO reconciles for actual updates

---

go.mod
go.sum
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
proxy/cmd/main.go
proxy/pkg/config/config.go
proxy/pkg/proxy/proxy.go
proxy/pkg/util/util.go
proxy/pkg/util/util_test.go
tech-previews/fine-grain-rbac/README.md

Forward port fine-rain-rbac dev-preview code into ACM 2.11.

[ACM-10865] fine-grain-rbac tech-preview

---

operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
operators/multiclusterobservability/pkg/util/clustermanagementaddon_test.go

Since we're currently not correctly set "supportedConfigs" and "desiredConfig->specHash" on our ManagedClusterAdddon objects, these will never get past "Progressing" in 2.11. This is because the "addon-management-controller" is now specifically looking for these fields to be set.
As a workaround we set `addon.open-cluster-management.io/lifecycle: self` to ensure this does not happen. This should mirror the current behaviour of 2.10.

ACM-11987: Add self-managed to ClusterManagementAddOn

---

collectors/metrics/pkg/forwarder/forwarder.go
collectors/metrics/pkg/status/status.go
collectors/metrics/pkg/status/status_test.go
operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go

We are still having issues with status reporting. In the latest instance, the `endpoint-operator` fails to update the `metrics-collector` deployment because of a conflict, then sets the status to degraded. And it remains in that state while the metrics are forwarded.
This PR:
- Adds retry on conflict error to the `metrics-collector` related updates.
- Changes the comparison between the found resources version and the desired ones to use `DeepDerivative`. This will reduce the number of unnecessary updates.
- Adds retry on conflict for status updates made by the `metrics-collector`.
- Sort conditions before updating the status in the `metrics-collector` to ensure it handles the most recent one.
I tried to change as few things as possible.

ACM-10812: Fix status report

---

proxy/pkg/util/util_test.go

This should fix flakyness of the test:
TestUpdateAllManagedClusterLabelNames/Add_new_labels
Which would flake due to non-deterministic order of labels. Fixed by sorting the slice in the test.
Introduced by:
448fe4881474b93b1351cc7812303abcfa744810

Tests: Fix flaky Add_new_labels test

---

collectors/metrics/pkg/forwarder/forwarder.go
collectors/metrics/pkg/status/status.go
operators/endpointmetrics/pkg/util/status.go
operators/endpointmetrics/pkg/util/status_test.go

Fixes:
- The status update on the collector does not happen if it finds an existing condition of the same type even when it is not the latest one. For example, if the most recent condition is `Progressing` but the last condition in the list is `Available`, it will not update this last condition if the new one is also `Available`, keeping the state in `Progressing`.
- Also it ensures that only one of the main conditions expected by ACM (Progressing, Available, Degraded) is set to `true`. The status display in the console seems to pick the first condition set to `true`, even if not the most recent one.

ACM-10812: fix status update on collector

---

operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview-optimized.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml

The custom all value, `.+` was meant to remove very long list of clusters in (default) queries when all cluster was selected, i.e one would see queries like these:
```
{cluster=~"(local-cluster|spoke-1|spoke-2|spoke-3|spoke-4....)"
```
Unfortunately adding this custom all value seem to have completely broken the ability to filter cluster on the dashboard, hence removing this for now.

Dashboards: Remove custom allValue for fleetwide

---

operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview-optimized.yaml

The custom all value, `.+` was meant to remove very long list of clusters in (default) queries when all cluster was selected, i.e one would see queries like these:
```
{cluster=~"(local-cluster|spoke-1|spoke-2|spoke-3|spoke-4....)"
```
Unfortunately adding this custom all value seem to have completely broken the ability to filter cluster on the dashboard, hence removing this for now.

ACM-12406 - 2.10: Remove custom allValue for optimized dash

---

operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-overview.yaml

- Updated the colors since the text didn't appear correctly when using light mode.
- Updated the number of VMs to show 0 if no VMs are running
- Added the `kubevirt_hco_system_health_status`, since it is important to indicate in cases where there is an issue in the conditions, but no alert.
Signed-of-by: Shirly Radco <sradco@redhat.com>

Update OpenShift Virtualization overview dashboard

---

collectors/metrics/Containerfile.operator
collectors/metrics/Dockerfile

This should unblock https://github.com/openshift/release/pull/53852, which gets stuck on the build process because of the interactive confirmation prompt that these `dnf install` commands were triggering.

Fix `dnf install` to prevent interactive confirmation

---

operators/multiclusterobservability/Dockerfile.dev

As the rest of the images use ubi9, this one should too.

Use ubi9 based go-toolset

---

operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go

OCP 3.x spokes do not have the ClusterVersion CRD. In such a case, the `kube-api` client returns an error of type `NoMatchError`. This error is now properly checked and results in a simple `Info` log.
I have kept the case `NotFoundError` that will also result in a simple log. Just in case we have an OCP 3 spoke with this CRD 🤷 
All other error types will return an error.
Unit tests for these OCP 3 cases have been added (`NotFound` was already tested but it is not the observed behavior which is `NoMatch`).

ACM-12773: Fix clusterVersion check for OCP3

---

operators/multiclusterobservability/pkg/config/resources_map.go

Now the Compactor's `default` t-shirt size will be matching the small one. This should help to the Compactor get access to an adequate amount of CPU time and memory by default when it ends up in an overcommitted node.

[RHOBS-1044] Bump the Compactor's default CPU and memory requests

---

operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-overview.yaml

Grafana should accept this, provided there is no clash, and the linkref will now reference a fixed dashboard URL instead of a grafana generated UID which changes per-installation.
Also fixed the query param templating for the severity and health impact.
The value of `${severity:queryparam}` already includes the query param tag in it, so the previous template would substitute the tag with `var-health_impact=$var-health_impact=All` instead of `var-health_impact=All`.

Fixing ACM-12888 by supplying a UID for fixed URL ref in the URL

---

collectors/metrics/Containerfile.operator
collectors/metrics/Dockerfile

Builds would be stuck due to waiting on the promt to accept upgraded packages:
```
[2/2] STEP 15/25: LABEL org.label-schema.vendor="Red Hat" org.label-schema.name="$IMAGE_NAME_ARCH" org.label-schema.description="$IMAGE_DESCRIPTION" org.label-schema.vcs-ref=$VCS_REF org.label-schema.vcs-url=$VCS_URL org.label-schema.license="Red Hat Advanced Cluster Management for Kubernetes EULA" org.label-schema.schema-version="1.0" name="$IMAGE_NAME" maintainer="$IMAGE_MAINTAINER" vendor="$IMAGE_VENDOR" version="$IMAGE_VERSION" release="$IMAGE_RELEASE" description="$IMAGE_DESCRIPTION" summary="$IMAGE_SUMMARY" io.k8s.display-name="$IMAGE_DISPLAY_NAME" io.k8s.description="$IMAGE_DESCRIPTION" io.openshift.tags="$IMAGE_OPENSHIFT_TAGS"
[2/2] STEP 16/25: RUN microdnf update && microdnf install ca-certificates …
```

add `-y` to `microdnf update` to unstuck builds

---

operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go

This allows rbac-query-proxy to authentication against obs-api. This is needed as Grafana no longer automatically forwards the header (and for now only does so in our patched Grafana version).

ACM-12794: forward auth header to datasource

---

operators/endpointmetrics/Containerfile.operator
operators/endpointmetrics/Dockerfile
operators/endpointmetrics/cmd/cmo-config-revert/main.go
operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go

This change creates a new binary inside the endpoint metrics operator to enable manually/programatically revert the config in the managed cluster if the Hub for some reason is not able to clean it up like https://issues.redhat.com/browse/ACM-13355.
This change is driven by a customer request in https://issues.redhat.com/browse/ACM-13149 where they are using the cleanup script https://github.com/stolostron/deploy/blob/master/hack/cleanup-managed-cluster.sh.
This change can be paired with https://github.com/stolostron/deploy/pull/276

Expose cmo config revert binary

---

loaders/dashboards/Dockerfile
operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
operators/multiclusterobservability/config/rbac/mco_role.yaml
proxy/Dockerfile

Initial commit for -> https://github.com/stolostron/multicluster-observability-operator/pull/1587 
Since Cluster role is Managed by MCH. It needs to get updated here first.  -> https://github.com/stolostron/multiclusterhub-operator/blob/main/pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-operator-clusterrole.yaml
This is to prevent the MCO operator from failing to come up due to permission
```
E0829 09:17:02.982625       1 reflector.go:158] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.31.0-alpha.2/tools/cache/reflector.go:243: Failed to watch *v1.ImageStream: failed to list *v1.ImageStream: imagestreams.image.openshift.io is forbidden: User \"system:serviceaccount:open-cluster-management:multicluster-observability-operator\" …
```

update MCO cluster role for imagestreams

---

cicd-scripts/setup-e2e-tests.sh
tests/pkg/utils/mco_managedcluster.go

The BVT tests are reporting failure because some of the managed clusters are never properly imported. However, Obs tests are also not correctly detecting and skipping these unhealthy clusters, and expecting Obs add-on to be present.
https://app.travis-ci.com/github/stolostron/canary/jobs/625626340

Fix tests for BVT testing

---

cicd-scripts/setup-e2e-tests.sh

Instead of hardcoding a specific snapshot, we just use the latest release instead.

CI/Kind: Use latest snapshot for OCM version

---

operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_integration_test.go
operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
operators/endpointmetrics/main.go
operators/pkg/config/config.go

1. Adds an integration test for merging of CMO ConfigMap with other clients
2. Adds the Delete event to the Watch for CMO ConfigMap
3. Explicitly adds the CMO ConfigMap reference to the filtered cache

[ACM-14076]: Ensure CMO ConfigMap is reconciled on any event

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_status.go
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_status_test.go
operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func.go
operators/multiclusterobservability/main.go
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/config/config_test.go
operators/multiclusterobservability/pkg/rendering/renderer_mcoa.go
operators/multiclusterobservability/pkg/rendering/renderer_mcoa_test.go

Succeeds https://github.com/stolostron/multicluster-observability-operator/pull/1564 
The following PR is an amendment/extention to https://github.com/stolostron/multicluster-observability-operator/pull/1470 to improve the user experience when a user decides to use the new capabilities spec and in turn MCOA. Currently the MCOA internal reconciliation loop depends on a set of CustomResourceDefinitions (CRD) owned by other operator dependecies (i.e. cluster-logging-operator, opentelemetrycollector-operator). The underlying implementation checks if the CRDs exist and actually serve the required CRD versions. If any is missing the MCO status shows the MCOADegradedCondition, e.g.:
```yaml
conditions:
- lastTransitionTime: "2024-08-07T09:25:01Z"
message: 'MultiCluster-Observability-Addon …
```

[release-2.12] Add MCOA status for CRD dependencies

---

operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_integration_test.go
operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
operators/endpointmetrics/main.go
operators/pkg/config/config.go

Backport of https://github.com/stolostron/multicluster-observability-operator/pull/1610
1. Adds an integration test for merging of CMO ConfigMap with other clients
1. Adds the Delete event to the Watch for CMO ConfigMap
1. Explicitly adds the CMO ConfigMap reference to the filtered cache

[ACM-14176]: Ensure CMO ConfigMap is reconciled on any event

---

operators/endpointmetrics/README.md
operators/endpointmetrics/doc/design/addon-status.md

The addon status update is currently causing issues such as:
- Flapping states
- Inconsistent states
This document aims to specify the expected behavior. It is a target for achieving a consistent management of the spoke addon status being reported to the hub.
It does not describe the current implementation. 
Main differences are:
- **Clarification of State Transitions**: The document clarifies state transitions with added restrictions. Specifically, transitions between degraded and available states are restricted to avoid flapping.
- **Progressing Status on Metrics-Collector Update**: On each metrics-collector update, the status goes back to progressing state.
- Addition of new condition types for each collector that are aggregated by the status controller.

ACM-12251: New addon status design document

---

operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
operators/endpointmetrics/main.go
operators/pkg/config/config.go

Backport of https://github.com/stolostron/multicluster-observability-operator/pull/1612
1. Adds an integration test for merging of CMO ConfigMap with other clients
1. Adds the Delete event to the Watch for CMO ConfigMap
1. Explicitly adds the CMO ConfigMap reference to the filtered cache

[ACM-14235]: Ensure CMO ConfigMap is reconciled on any event

---

operators/multiclusterobservability/manifests/base/grafana/config.yaml

Disables:
- Correlations (the page anyway just comes up with "Please contact your administrator to create new correlations.")
- Public Dashboards (users anyway doesn't have permissions for that)

Disable non-applicable Grafana features

---

examples/mco/e2e/v1beta1/observability-v1beta1-to-v1beta2-golden.yaml
examples/mco/e2e/v1beta2/custom-certs/observability.yaml
examples/mco/e2e/v1beta2/observability.yaml
operators/endpointmetrics/pkg/collector/metrics_collector.go
operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_observabilityaddons.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml

Expose the scrape size limit as a CRD option.

Expose metrics-collector scrape limit size in CRD

---

operators/multiclusterobservability/manifests/base/grafana/config.yaml

This commit disables Grafanas unified alerting feature. We do this since it is not applicable for MCO, and since the upgrade to Grafana 11.1.5, we can disable it without errors.

Grafana: Disable unified alerting

---

operators/endpointmetrics/pkg/hypershift/hypershift.go
operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-k8s-etcd.yaml

Service monitors scraping etcd and apiserver jobs for hosted clusters were missing some metrics for their respective specialized dashboards. 
I am also fixing missing data for other cases, as well as fixing some bugs in the etcd dashboard.
https://issues.redhat.com/browse/ACM-13524

Fix: fix etcd and apiserver dashboards for hypershift and more

---

tests/pkg/utils/mco_managedcluster.go

This is a test setup error.  The PR addresses two issues:
1. ~~Must exclude `local-cluster` from managed cluster list. This is because starting with ACM 2.10, observability is no longer running as a addon on the hub cluster, and always configured on the hub cluster. If a cluster is named "local-cluster" or has a label "local-cluster: true", it should be treated as a hub cluster.~~ Do not skip `local-cluster`.
2. Must exclude unhealthy clusters. From time-to-time, we have seen CICD environment with incomplete/unhealthy clusters in the hub, and the logic should skip testing Obs features on them. This is achieved by checking `ManagedClusterConditionAvailable` with `status="True"` in the managed cluster object.

fix: [ACM-14189] identify healthy managed clusters during e2e

---

collectors/metrics/Dockerfile.dev
collectors/metrics/cmd/metrics-collector/main.go
collectors/metrics/cmd/metrics-collector/main_test.go
collectors/metrics/pkg/collectrule/evaluator.go
collectors/metrics/pkg/forwarder/forwarder.go
collectors/metrics/pkg/forwarder/forwarder_test.go
collectors/metrics/pkg/metricfamily/hypershift_transformer.go
collectors/metrics/pkg/metricfamily/hypershift_transformer_test.go
collectors/metrics/pkg/metricsclient/metricsclient.go
collectors/metrics/pkg/metricsclient/metricsclient_test.go
collectors/metrics/pkg/status/status.go
collectors/metrics/pkg/status/status_test.go
examples/mco/e2e/v1beta1/observability-v1beta1-to-v1beta2-golden.yaml
examples/mco/e2e/v1beta2/custom-certs/observability.yaml
examples/mco/e2e/v1beta2/observability.yaml
operators/endpointmetrics/pkg/collector/metrics_collector.go
operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_observabilityaddons.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml

Attempting to implement federate sharding by sharding the match rules (both passed as file and flag) between a number of workers. 
If the code looks messy, that is because it is, there is a lot of unused and scattered logic throughout metrics-collector. I have tried to refactor a lot of this

Make federate sharding possible in metrics-collector by using workers

---

operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-overview.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-single-cluster-view.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-single-vm-view.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-virtual-machines-by-time-in-status.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-virtual-machines-inventory.yaml
operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml

In this PR we introduce 4 dashboards related to Virtual Machines:
1. Service Level dashboards - Virtual Machines by Time in Status
2. Inventory dashboards - Virtual Machines Inventory
3. Executive dashboards - Single Cluster View
4. Executive dashboards - Single Virtual Machine View
And update the "ACM - OpenShift Virtualization Overview"
name to "Executive dashboards - Clusters Overview"
and enriched it with additional details.
Also moved all dashboards under the "ACM / OpenShift Virtualization"
folder.

Add Virtual Machines related dashboards

---

operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
operators/multiclusterobservability/controllers/placementrule/predicate_func.go
operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go

- Make sure local-cluster is always a part of  internal `managedcluster` list and not depend on the CRUD events of the Managedcluster  resource because when `disableHubSelfManagement: true`, the resource for local-cluster will not be created. 
- Use sync.Map for thread safe read and writes
- fix unit tests to run predicate tests against managedcluster resource and not deployment

Make sure local cluster is always in the managedcluster list

---

tools/generate-dashboard-configmap-yaml.sh

Quote shell variables so strings with `$variable` are not expanded during shell `echo`

[ACM-14487] quote json variable so $variables are not expanded during shell echo

---

operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
operators/pkg/util/allowlist.go

Metrics from hypershift are federated from the uwl in-cluster prometheus by the uwl-metrics-collector. I am adding the missing ones for the dedicated etcd and apiserver dashboards.
This PR also fixes the merge or recording rules for the uwl custom metrics.

ACM-13524: Fix hypershift missing custom metrics

---

operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-overview.yaml
operators/multiclusterobservability/manifests/base/grafana/dash-acm-virtual-machines-inventory.yaml

Update Virtualization descriptions based on the docs team review.

Update Virtualization descriptions

---

operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-statefulset.yaml
operators/multiclusterobservability/manifests/base/grafana/deployment.yaml
operators/multiclusterobservability/manifests/base/proxy/deployment.yaml

During upgrade from ACM2.11->ACM2.12 for a (currently not fully understood reason) we use the proxy image from the base templates. This seem to happen only for a short while, on later reconciles we appear get the correct image from the OCP imagestream.
The image previously set in the base template were amd64 only, causing the pods to crash on any other architecture. From rbac-query-proxy and Grafana it eventually resolves, however alertmanager uses a stateful set and gets stuck due the known Kubernetes issue described here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#forced-rollback
Ideally we'd never want to use these images, but meanwhile this should at least ensure we don't crash and leave a unhealthy stateful set for alertmanager.

(2.12) Use multi-arch origin-oauth-proxy image

---

operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/controllers/observabilityendpoint/predicate_func.go
operators/endpointmetrics/pkg/collector/metrics_collector.go

Backport of https://github.com/stolostron/multicluster-observability-operator/pull/1664

[2.12 backport]: Fix flapping status

---

operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-statefulset.yaml
operators/multiclusterobservability/manifests/base/grafana/deployment.yaml
operators/multiclusterobservability/manifests/base/proxy/deployment.yaml

During upgrade from ACM2.11->ACM2.12 for a (currently not fully understood reason) we use the proxy image from the base templates. This seem to happen only for a short while, on later reconciles we appear get the correct image from the OCP imagestream.
The image previously set in the base template were amd64 only, causing the pods to crash on any other architecture. From rbac-query-proxy and Grafana it eventually resolves, however alertmanager uses a stateful set and gets stuck due the known Kubernetes issue described here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#forced-rollback
Ideally we'd never want to use these images, but meanwhile this should at least ensure we don't crash and leave a unhealthy stateful set for alertmanager.

Use multi-arch origin-oauth-proxy image

---

operators/endpointmetrics/pkg/collector/metrics_collector.go

Fixing invalid condition check for updating the status when the metrics collector deployment is updated. The isUpdated condition must be nested within the isEnabled block instead of checking for a AND condition. Because otherwise it gets into the ELSE that notifies for a disabled status.

Fix status update regression

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
operators/multiclusterobservability/pkg/rendering/renderer.go
operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
operators/multiclusterobservability/pkg/rendering/renderer_alertmanager_test.go
operators/multiclusterobservability/pkg/rendering/renderer_grafana.go
operators/multiclusterobservability/pkg/rendering/renderer_proxy.go
operators/multiclusterobservability/pkg/rendering/renderer_test.go

For some unknown reason, during upgrades from ACM 2.11, the template image is briefly used, instead of the image from the openshift imagestream. The template image is not available in disconnected environments, and as a result causes the pods be unable to come up.
This is a problem especially for alertmanager. Because of it being a statefulset when it gets into the bad state, with the wrong image, it doesn't automatically recover on the next reconcile. This requires manual intervention to fix.
Instead with this PR, we make the reconcile fail if we do not find the oauth image. This will make it retry later, when the imagestream is able to be found.

Render: fail if no oauth image is found

---

tests/pkg/tests/observability_dashboard_test.go

The retrying of adding custom dashboards lasts at least 7 minutes. So increase timeout slightly in the hopes that the success rate is of test passings are a bit higher untill we get a better solution in place.

Tests: Increase custom dashboard test timeout

---

operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/controllers/observabilityendpoint/predicate_func.go
operators/endpointmetrics/pkg/collector/metrics_collector.go

This PR:
- Introduces a new predicate for the configmap, only triggering reconciles when the data changes.
- Only updates the status if the collector deployment was actually updated.
https://issues.redhat.com/browse/ACM-15458

fix status update and cm predicate

---

operators/multiclusterobservability/pkg/rendering/renderer.go
operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
operators/multiclusterobservability/pkg/rendering/renderer_grafana.go
operators/multiclusterobservability/pkg/rendering/renderer_proxy.go

Only try to get the oauth image from the OCP imagestream, if the image.openshift.io api type is available. Otherwise, it likely means we're running a non-ocp system (for kind tests for example) and in this case we accept using the base template image.

Renderer: detect if imagestream is available

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
operators/multiclusterobservability/pkg/rendering/renderer.go
operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
operators/multiclusterobservability/pkg/rendering/renderer_alertmanager_test.go
operators/multiclusterobservability/pkg/rendering/renderer_grafana.go
operators/multiclusterobservability/pkg/rendering/renderer_proxy.go
operators/multiclusterobservability/pkg/rendering/renderer_test.go

cherry-pick of https://github.com/stolostron/multicluster-observability-operator/pull/1669 +
Renderer: detect if imagestream is available
Only try to get the oauth image from the OCP imagestream, if the
image.openshift.io api type is available. Otherwise, it likely means
we're running a non-ocp system (for kind tests for example) and in this
case we accept using the base template image.

[main] Render: fail if no oauth image is found+kind fix

---

collectors/metrics/pkg/forwarder/forwarder.go
collectors/metrics/pkg/metricsclient/metricsclient.go
collectors/metrics/pkg/metricsclient/metricsclient_test.go
go.mod
go.sum

Stop retries on permanent errors, like 409 that can often happen.
Also triggers an initial forward without waiting the interval. It also improves the status reporting which becomes available (or not) faster.

ACM-14080: update retry logic on forward

---

cicd-scripts/customize-mco.sh

This adds a new regex in the Ginkgo tests, to ensure we can filter out tests which require OCP from being run during the kind tests.
ACM-15734

Filter ocp required tests

---

operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-statefulset.yaml
operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
operators/multiclusterobservability/pkg/rendering/renderer_alertmanager_test.go

https://issues.redhat.com/browse/ACM-13481
This is a workaround/hack when AM replicas are set to 1 and are no more in HA mode. https://github.com/prometheus/alertmanager/pull/1971

[ACM-13481] - Remove HA mode when AM has one replica

---

operators/endpointmetrics/config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml
operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
operators/multiclusterobservability/controllers/placementrule/obsaddon.go
operators/multiclusterobservability/controllers/placementrule/obsaddon_test.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/manifests/endpoint-observability/observability.open-cluster-management.io_observabilityaddon_crd.yaml

Turns out there are a few issues with the behavior of the ObservabilityAddon CRD.
The CRD should operationally be doing the following,
- Have a sane default for the options, all of which it will inherit from the MCO obsAddon spec at the start
- Be per-cluster configurable, so that the user can modify the ObservabilityAddon CR in a specific spoke cluster namespace on the hub
- Get copied over onto the spoke cluster and configure endpoint-operator
- Allow user to switch back to MCO-based ObsservabilityAddon config if they wish to 
- All these changes are in sync in three places: ManifestWork on hub, spoke ns ObservabilityAddon CR on hub, ObservabilityAddon CR in the actual spoke cluster.
However it was not doing this correctly which led to a few issues and fields like the scrape limit or …

[ACM-16286]: Ensure MCO spec addon options are propagated correctly

---

operators/endpointmetrics/config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml
operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
operators/multiclusterobservability/controllers/placementrule/obsaddon.go
operators/multiclusterobservability/controllers/placementrule/obsaddon_test.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/manifests/endpoint-observability/observability.open-cluster-management.io_observabilityaddon_crd.yaml

…#1718)
* [ACM-16286]: Ensure MCO spec addon options are propagated correctly
* [ACM-16286]: Update all observabilityaddon manifests
* [ACM-16286]: Ensure hub and spoke obsaddon are synced based on spec
* [ACM-16286]: Allow customizing ObsAddon in spoke ns
* [ACM-16286]: Comments
* Add addon source annotation
* Add handling for empty map
* Add handling for nil maps
* Add annotation predicate, update in mco mode
* Fix unit test, make addon annotation constant
* Update comment
* Address comments
* Use semantic deepequal, add test for setter
* Set spoke addon correctly after comparison
---------

[ACM-16286/backport 2.12]: Ensure MCO spec addon options are propagated correctly

---

operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
operators/multiclusterobservability/controllers/placementrule/predict_func.go
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/config/config_test.go
operators/multiclusterobservability/pkg/servicemonitor/sm_controller.go

MCO and Placement Controller react to creates/updates/deletes from MCH CR . But we only specifically care about the mch-image-manifest configmap changes. So if we continuously get mch updates, the current reconcile logic always returns true after reading the image configmap even if it didnt differ from the previous version. 
The update to mch image configmap has to reflect on all spokes and in scale environment this is going to be a very expensive operation and if we dont check if an actual update is needed, then this is going to noisy in terms of logs and also unnecessary API calls

[ACM-16335] Reconcile MCO only when there is actual change in mch image manifest

---

collectors/metrics/cmd/metrics-collector/main.go
collectors/metrics/cmd/metrics-collector/main_test.go

Without this, it starts a new routine when workers are > 1 which sends requests to federate with 0 limit byte

Fix leaky goroutine on metrics-collector

---

go.mod
go.sum

[release-2.10] Bump golang.org/x/net to 0.33.0

---

collectors/metrics/cmd/metrics-collector/main.go
collectors/metrics/cmd/metrics-collector/main_test.go

* Fix leaky goroutine on metrics-collector
* Check simulated series file
* Fix test
---------

[release-2.12] Fix leaky goroutine on metrics-collector (#1733)

---

collectors/metrics/pkg/metricsclient/metricsclient.go
collectors/metrics/pkg/metricsclient/metricsclient_test.go
go.mod
go.sum
operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
operators/multiclusterobservability/controllers/placementrule/predict_func.go
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/config/config_test.go

git revert eb94214fa06367be250da9f5e824bff2280b46a5
git revert 10cfb4a1aa78c94fd9015041acff579a50f69f2c
which essentially keeps x/net and x/crypto changes for CVE-2024-45337 and CVE-2024-45338  and reverts non-CVE changes
Reinstate later with branch tmp-release-211-01082025

[release-2.11] Revert non-CVE changes

---

collectors/metrics/pkg/forwarder/forwarder.go
collectors/metrics/pkg/metricsclient/metricsclient.go
collectors/metrics/pkg/metricsclient/metricsclient_test.go

Status from the metrics collector now reports available state when receiving a 409 http error on remote write to the hub. 
This reflects more accurately the status of the addon as metrics are well ingested. The error is still logged to make it visible as this is most often the result of an invalid configuration.
Fixes https://issues.redhat.com/browse/ACM-17055

Fix: Flapping addon staus due to 409 response on remote write to the hub

---

collectors/metrics/pkg/metricsclient/metricsclient.go
collectors/metrics/pkg/metricsclient/metricsclient_test.go

All labels are deduplicated, except this one. We have a client configuration where this happens. Adding it to the deduplication process.
Fixes https://issues.redhat.com/browse/ACM-17056

Fix: Deduplicate the __name__ label in the metrics collector

---

Makefile
README.md

This is a minor update to the README link for installing kustomize and a minor update to the Makefile where the `undeploy` command does not seem to be correct.
I was also wondering if the mention of the `kustomize` goal in https://github.com/stolostron/multicluster-observability-operator/blob/main/operators/multiclusterobservability/Makefile should be removed, because it doesn't seem to be defined anywhere (and it's referenced in the `install`, `uninstall` and `deploy` goals)

minor update of README and Makefile

---

operators/endpointmetrics/pkg/collector/metrics_collector.go
operators/multiclusterobservability/manifests/base/grafana/deployment.yaml
operators/multiclusterobservability/pkg/certificates/cert_controller.go
operators/pkg/util/util.go

As per [documentation](https://www.sqlite.org/tempfiles.html#temporary_file_storage_locations), sqlite needs access to a temporary directory for some operations. As the root file system is readOnly and it picks by default the `/tmp` dir, adding a folder was failing since we upgraded Grafana.
This PR adds a tempdir env variable for sqlite that point to the same mounted directory as the database as it is writable.
This PR also includes an improvement to reduce e2e test flakiness. Previously, because `cert/time-restarted` only had minute-level accuracy, it was possible for two e2e tests to generate the same timestamp, leaving components unchanged and causing tests to fail (certrenew at least). The time accuracy is now improved, down to the second.

Fix grafana dashboards update when adding new folder

---

renovate.json

We get unnecessary Konflux  updates to branches not related to the release or work we do. Eg https://github.com/stolostron/multicluster-observability-operator/pull/1799 
https://github.com/stolostron/multicluster-observability-operator/pull/1788

Update renovate.json to pick only main and actual release branches

---

operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go

Fixes flaky unit test resulting in:
```
=== RUN   TestManifestWork
placementrule_controller_test.go:140: begin setupTest
placementrule_controller_test.go:154: Failed to create symbollink(/go/src/github.com/stolostron/multicluster-observability-operator/operators/multiclusterobservability/tests/manifests) to(/go/src/github.com/stolostron/multicluster-observability-operator/operators/multiclusterobservability/manifests) for the test manifests: (symlink /go/src/github.com/stolostron/multicluster-observability-operator/operators/multiclusterobservability/manifests /go/src/github.com/stolostron/multicluster-observability-operator/operators/multiclusterobservability/tests/manifests: file exists)
```
This PR replaces os commands with test package utilities for creating a temporary directory and …

Fix flaky symlink creation in placement unit tests

---

go.mod
go.sum
tests/pkg/tests/observability_alert_test.go
tests/pkg/utils/mco_managedcluster.go

The watchdog alert is a Prometheus alert that is always on, and automatically deployed on openshift clusters with the in-cluster stack.
The e2e alert test, verifies that the watchdog alert is well forwarded to the hub alertmanager, validating the communication links. And as this alert is deployed everywhere, it is forwarded by alertmanagers deployed on both the hub and spokes.
The test fetches the watchdog alerts received by the ACM AlertManager, and verifies that is contains the ones from all managed clusters. However, the list of managed clusters is built by fetching the ManagedCluster resources and by checking the label `feature.open-cluster-management.io/addon-observability-controller` that is added by the [addon manager](https://github.com/open-cluster-management-io/enhancements/blob/ …

Fix e2e watchdog alert test

---

collectors/metrics/pkg/forwarder/forwarder.go
collectors/metrics/pkg/forwarder/token.go
collectors/metrics/pkg/forwarder/token_test.go
collectors/metrics/pkg/http/roundtripper.go
go.mod

Introduces a new struct named TokenFile to automatically renew the token by re-reading the token file when it approaches the expiration date. The token is accessed by the RoundTripper injecting the bearer token calling the GetToken() method.

ACM-15764: fix access token renewal from the metrics collector

---

tests/grafana-dev-test.sh
tools/generate-dashboard-configmap-yaml.sh
tools/setup-grafana-dev.sh

In the PR https://github.com/stolostron/multicluster-observability-operator/pull/1726 refactoring dashboards for MCOA, there are cases where the same dashboard name can be given to two different dashboards in different Grafana folders. This makes e2e fail because it uses such a dashboard in the `grafana_dev_test`. 
This PR:
- Adds support for specifying the Grafana folder in the script `generate-dashboard-configmap-yaml.sh`
- Changes the dashboard used in the `grafana_dev_test` for a stable one between current setup and MCOA
- Improves sed command support in `setup-grafana-dev.sh` (it was failing for me using GNU sed on Darwin)
- Refactors `grafana-dev-test.sh` for better readability and improved robustness with retries on more commands (including test user creation that is flaky) and …

Add support for grafana folder in generate-dashboard-configmap-yaml script

---

tests/pkg/tests/observability_alert_test.go
tests/pkg/utils/kube_debug.go
tests/pkg/utils/mco_managedcluster.go

Removes an invalid assertion in e2e tests introduced by https://github.com/stolostron/multicluster-observability-operator/pull/1805 (see details in https://github.com/stolostron/multicluster-observability-operator/pull/1808#issuecomment-2627643353). 
And only list available ManagedClusters (this is necessary for some other environments running our e2e suite).

Fix: list of managedClusters in e2e tests for AlertManager

---

cicd-scripts/run-e2e-tests.sh

To ensure we don't miss any scripts failing to execute.

Make e2e fail on any errors

---

collectors/metrics/pkg/metricsclient/metricsclient.go
collectors/metrics/pkg/metricsclient/metricsclient_test.go
go.mod
go.sum
operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
operators/multiclusterobservability/controllers/placementrule/predict_func.go
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/config/config_test.go

Related to https://github.com/stolostron/multicluster-observability-operator/pull/1761
Restore previously reverted changes after CVE-only release.
git cherry-pick 10cfb4a
git cherry-pick eb94214f

[release-2.11] Restore non-CVE changes

---

operators/multiclusterobservability/manifests/base/alertmanager/prometheusrule.yaml

Previously this alert would fire when the per second rate of failures exceeded 10 in total (for all targets, including thanos-receive). This basically means the alert never triggede since we basically only do one remote-write request per 5 minutes/spoke/endpoint that meant you needed a huge number of spoke for this alert to fire, even if all requests fail.
Secondly, the alert made no distinction between endpoints, for example, it's possible to setup export to an external endpoint like victoriametrics, and we probably want to make sure we have different alerts for different endpoints.
Further we increase the timeframe of the rate from 5m to 10m, to make sure we actually get a sample. 5m works, and would be slightly more responsive, but the metric will then potentially jump very rapidly.

ACM-18001: Make alert ACMRemoteWriteError fire on percentages

---

cicd-scripts/run-e2e-in-kind-via-prow.sh
scripts/test-utils.sh

- Tooling changes required as we're now running later versions of ci-opertor which uses RHEL9, and the remote VM uses RHEL8 which means binaries are not compatible
- If we cannot find a snapshot for the current component version, fallback to a snapshot from the previous version.

Kind: do not copy incompatible binaries to VM & fallback to previous release if no snapshots found

---

loaders/dashboards/pkg/controller/dashboard_controller.go

Instead of using the name, as the same name was used for the MCOA equivalent.
Fixes: ACM-18355
/cherry-pick release-2.13

dashboard-loader: set home dashboard with UID

---

operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
operators/endpointmetrics/pkg/collector/metrics_collector.go
operators/endpointmetrics/pkg/collector/metrics_collector_test.go
operators/multiclusterobservability/manifests/endpoint-observability/role.yaml

To ensure that resources created by the endpoint operator are deleted, especially on the hub, a controller reference is added to them. The owner is set to:
- The observability addon resource on the spokes
- MCO on the hub
https://issues.redhat.com/browse/ACM-18474

Add controller reference on resources deployed by the endpoint-operator

---

Makefile
cicd-scripts/metrics/Makefile
cicd-scripts/metrics/cmd/rulescheck/main.go
cicd-scripts/metrics/internal/rule/rule.go
operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
operators/multiclusterobservability/manifests/base/grafana/platform-mcoa/prometheus-rule.yaml
operators/multiclusterobservability/manifests/base/grafana/platform-mcoa/scrape-config.yaml

Stop relying on [rules](https://github.com/stolostron/multicluster-observability-operator/blob/bf2118fa4a5b644a9962eb63bc9a3714d40e1da6/operators/multiclusterobservability/manifests/base/alertmanager/alert_rules.yaml#L1) computed on the Hub Thanos Ruler. They are replaced by rules pushed to the spokes and computed there.
Resulting rules are added to the scrape config.
Sort alphabetically the scrape config list of metrics.

Remove standard hub rules for MCOA

---

.github/workflows/lint.yaml
operators/multiclusterobservability/config/manager/manager.yaml

Make sure the limits of MCO resources are removed when generating the bundle instead of simply removing it from the generated files and ignoring the changes in our CI.
ref: https://github.com/stolostron/multicluster-observability-operator/pull/1824

[2.13] Correctly fix limit removal

---

.github/workflows/lint.yaml
operators/multiclusterobservability/config/manager/manager.yaml
tests/pkg/utils/utils.go

The linter complains about command injection here. There's potentially a better way of getting the user token than passing username/password to `oc login` - however for now ignoring the linter, as this is a test case and we always control the params which are injected.
----
Correctly fix limit removal
Make sure the limits of MCO resources are removed when generating the bundle instead of simply removing it from the generated files and ignoring the changes in our CI.

Linter fixes

---

operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
operators/multiclusterobservability/controllers/placementrule/endpoint_metrics_operator.go
operators/multiclusterobservability/controllers/placementrule/hub_ocp_monitoring_util.go
operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
operators/multiclusterobservability/controllers/placementrule/obsaddon.go
operators/multiclusterobservability/controllers/placementrule/obsaddon_test.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
operators/multiclusterobservability/controllers/placementrule/predicate_func.go
operators/multiclusterobservability/controllers/placementrule/role.go
operators/multiclusterobservability/controllers/placementrule/role_test.go
operators/multiclusterobservability/pkg/certificates/cert_agent.go
operators/multiclusterobservability/pkg/certificates/certificates.go
operators/multiclusterobservability/pkg/certificates/signer.go
operators/multiclusterobservability/pkg/certificates/signer_test.go
operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
operators/multiclusterobservability/pkg/util/clustermanagementaddon_test.go

When enabling the MCOA feature, we must disable the current metrics-collector related resources. However, some resources, like certificates, must be preserved/created. And eventually, they will probably be handled by MCOA directly at a later stage.
Because the necessary changes were complex to implement, I ended up refactoring the high-level logic of the placementrule_controller to improve readability and maintainability. For this part I tried to keep identical processing. 
The only breaking change is the end of OCP 3 support.
Here are some of the refactoring actions done:
- Simplify logging: remove error logs when not needed (error is returned), remove noisy doing nothing logs (only keeping high level ones in the Reconcile function), log write operations
- Wrap returned errors to provide …

Manage deployment of resources for MCOA and metrics collector

---

.tekton/endpoint-monitoring-operator-acm-214-pull-request.yaml
.tekton/endpoint-monitoring-operator-acm-214-push.yaml
.tekton/grafana-dashboard-loader-acm-214-pull-request.yaml
.tekton/grafana-dashboard-loader-acm-214-push.yaml
.tekton/metrics-collector-acm-214-pull-request.yaml
.tekton/metrics-collector-acm-214-push.yaml
.tekton/multicluster-observability-operator-acm-214-pull-request.yaml
.tekton/multicluster-observability-operator-acm-214-push.yaml
.tekton/rbac-query-proxy-acm-214-pull-request.yaml
.tekton/rbac-query-proxy-acm-214-push.yaml

The 'sast-unicode-check' and 'sast-shell-check' tasks will become required for all Konflux builds on April 1st.
This change adds them to the Konflux build pipeline definitions in this repo.
This PR was generated automatically using [this script](https://gitlab.cee.redhat.com/ynanavat/generate-bulk-tekton-prs/-/blob/main/bulk-update-repos.sh?ref_type=heads).
See also:
- [Related announcement](https://groups.google.com/a/redhat.com/g/konflux-announce/c/OEcuK1Sr7dI/m/xKwD_bMcAQAJ)
- [All task definitions](https://github.com/konflux-ci/build-definitions/tree/main/task)
- [KONFLUX-2264](https://issues.redhat.com/browse/KONFLUX-2264)
- [EC-1063](https://issues.redhat.com/browse/EC-1063)

Add new SAST tasks to Konflux pipelines

---

operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go

…ring reconcile
When a cluster detaches, it will still be listed in the managedcluster resource but it will have a DeletionTimeStamp and this causes MCO to think it needs to install Observability. Make sure the managed cluster is not a part of the managedcluster list during delete event.
https://issues.redhat.com/browse/ACM-19970

[ACM-19970] Make sure detached cluster is cleaned up

---

operators/multiclusterobservability/controllers/placementrule/status.go
operators/multiclusterobservability/controllers/placementrule/status_test.go

Cf https://issues.redhat.com/browse/ACM-19714

[Fix]: filter out non standard condition types when replicating addon status conditions

---

Jenkinsfile
tests/pkg/tests/observability-e2e-test_suite_test.go
tests/pkg/tests/observability_addon_test.go
tests/pkg/tests/observability_alert_test.go
tests/pkg/tests/observability_certrenew_test.go
tests/pkg/tests/observability_config_test.go
tests/pkg/tests/observability_dashboard_test.go
tests/pkg/tests/observability_endpoint_preserve_test.go
tests/pkg/tests/observability_export_test.go
tests/pkg/tests/observability_grafana_dev_test.go
tests/pkg/tests/observability_grafana_test.go
tests/pkg/tests/observability_manifestwork_test.go
tests/pkg/tests/observability_metrics_test.go
tests/pkg/tests/observability_observatorium_preserve_test.go
tests/pkg/tests/observability_rbac_test.go
tests/pkg/tests/observability_reconcile_test.go
tests/pkg/tests/observability_retention_test.go
tests/pkg/tests/observability_route_test.go

All output should now align with the correct format:
```
<Polarion test case ID>: <Component name>: <Test case name>
```

Tests: Make JUnit report conform to QE standard

---

proxy/pkg/proxy/proxy.go
proxy/pkg/proxy/proxy_test.go

Remove `Bearer ` from Authorization header when setting X-Forwarded-Access-Token.
This fixes #1942

Remove Bearer from authorization header when setting X-Forwarded-Access-Token

---

Jenkinsfile
tests/pkg/tests/observability-e2e-test_suite_test.go
tests/pkg/tests/observability_addon_test.go
tests/pkg/tests/observability_alert_test.go
tests/pkg/tests/observability_certrenew_test.go
tests/pkg/tests/observability_config_test.go
tests/pkg/tests/observability_dashboard_test.go
tests/pkg/tests/observability_endpoint_preserve_test.go
tests/pkg/tests/observability_export_test.go
tests/pkg/tests/observability_grafana_dev_test.go
tests/pkg/tests/observability_grafana_test.go
tests/pkg/tests/observability_manifestwork_test.go
tests/pkg/tests/observability_metrics_test.go
tests/pkg/tests/observability_observatorium_preserve_test.go
tests/pkg/tests/observability_reconcile_test.go
tests/pkg/tests/observability_retention_test.go
tests/pkg/tests/observability_route_test.go

All output should now align with the correct format:
```
<Polarion test case ID>: <Component name>: <Test case name>
```

[release-2.13] Tests: Make JUnit report conform to QE standard

---

operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_role.yaml

Related to https://github.com/stolostron/multicluster-observability-addon/pull/150

fix: add rbac permission to allow MCOA to get Subscriptions on hub

---

operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_role.yaml
operators/multiclusterobservability/pkg/rendering/renderer_mcoa.go
operators/multiclusterobservability/pkg/rendering/renderer_mcoa_test.go

Adds necessary permissions to the addon manager for updating configurations in the ClusterManagementAddon resource and removes prometheusAgent resources that were previously added here as it is now done in MCOA itself.

[MCOA]: Update default stack management

---

cicd-scripts/metrics/Makefile

Help fixing pending virt dashboar PRs. Once they rebase on it, some will be green.
These metrics exceptions are needed because the tool extracting metrics from dashboards is missing some.

Add metrics exceptions for virt dashboards

---

examples/export/victoriametrics.yaml

The `stable` image appears to be removed as well. Pin it to a specific version so the tests can pass.

Tests: pin victoria metrics image

---

cicd-scripts/metrics/Makefile

This exception is not needed for merging next kubevirt PRs

Remove exception for kubevirt PRs

---

examples/updatemcocr/advancedmcoconfig/custom-certs/kustomization.yaml
examples/updatemcocr/advancedmcoconfig/custom-certs/v1beta2-observability-custom-mco.yaml
examples/updatemcocr/advancedmcoconfig/v1beta2-observability-custom-mco.yaml
examples/updatemcocr/initialmcoconfig/custom-certs/kustomization.yaml
examples/updatemcocr/initialmcoconfig/custom-certs/v1beta2-observability-initial-mco.yaml
tests/pkg/tests/observability_config_test.go

The config tests, which applies CRs from `examples/updatemcocr` did not correctly handled the cases where the minio-tls-secret was not applied. This commit ensure have two versions of the mcoCR that handle both when the tls-secret is created and when it is not.
/cherry-pick release-2.13

Correctly handle custom-certs in config tests

---

tests/pkg/utils/mco_deploy.go

Ensures we don't get bogus secrets when re-running QE tests via Jenkins.

e2e: Do not replace object-storage secret with *

---

cicd-scripts/metrics/Makefile
cicd-scripts/metrics/cmd/rulescheck/main.go

- Adds the `--ignored-rules-missing-definition` flag to the rulescheck command.
- Adds the `cluster:health:components:map` metrics to the ignored rules as it is defined directly through COO for incident detection feature.

Fix CI metrics check

---

tests/pkg/tests/observability_alert_test.go

For *ks clusters, the watchdog alert is not installed by default. Our testcase, therefore tries to login to the managed *ks clusters and install the alert. However this depends on the login details for the *ks cluster being correctly supplied in the options.yaml file, which often is not the case.
This PR removes any *ks clusters for the expected clusters list, if we are unable to login and add the watchdog alert the the *ks clusters' prometheus instance.

Tests: Skip watchdog alert on *ks on missing login

---

tests/pkg/tests/observability_addon_test.go

This test depends on the managed cluster being correctly added to the testoptions. Therefore we skip the test completetly, if this is not the case.

Tests: skip RHACM4K-7518 if no managed cluster

---

.tekton/endpoint-monitoring-operator-acm-213-pull-request.yaml
.tekton/endpoint-monitoring-operator-acm-213-push.yaml
.tekton/grafana-dashboard-loader-acm-213-pull-request.yaml
.tekton/grafana-dashboard-loader-acm-213-push.yaml
.tekton/metrics-collector-acm-213-pull-request.yaml
.tekton/metrics-collector-acm-213-push.yaml
.tekton/multicluster-observability-operator-acm-213-pull-request.yaml
.tekton/multicluster-observability-operator-acm-213-push.yaml
.tekton/rbac-query-proxy-acm-213-pull-request.yaml
.tekton/rbac-query-proxy-acm-213-push.yaml
examples/updatemcocr/advancedmcoconfig/custom-certs/kustomization.yaml
examples/updatemcocr/advancedmcoconfig/custom-certs/v1beta2-observability-custom-mco.yaml
examples/updatemcocr/advancedmcoconfig/v1beta2-observability-custom-mco.yaml
examples/updatemcocr/initialmcoconfig/custom-certs/kustomization.yaml
examples/updatemcocr/initialmcoconfig/custom-certs/v1beta2-observability-initial-mco.yaml
loaders/dashboards/Dockerfile
tests/pkg/tests/observability_addon_test.go
tests/pkg/tests/observability_alert_test.go
tests/pkg/tests/observability_config_test.go
tests/pkg/tests/observability_metrics_test.go
tests/pkg/utils/mco_deploy.go

Cherry-picks some changes from the release-2.14 branch, that were missing on 2.13 and caused automation failures and flakes:
https://github.com/stolostron/multicluster-observability-operator/pull/2009
https://github.com/stolostron/multicluster-observability-operator/pull/2015
https://github.com/stolostron/multicluster-observability-operator/pull/2014
https://github.com/stolostron/multicluster-observability-operator/pull/2021
https://github.com/stolostron/multicluster-observability-operator/pull/2022

e2e fixes for 2.13

---

operators/multiclusterobservability/controllers/placementrule/manifestwork.go
operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/predict_func.go
operators/multiclusterobservability/controllers/placementrule/predict_func_test.go
operators/multiclusterobservability/controllers/placementrule/status.go
operators/multiclusterobservability/controllers/placementrule/status_test.go
operators/multiclusterobservability/main.go
operators/multiclusterobservability/pkg/config/config.go
operators/multiclusterobservability/pkg/util/managedclusteraddon.go
operators/multiclusterobservability/pkg/util/managedclusteraddon_test.go

- Fixes a reconcile loop triggered by invalid resources cleaning in the placement rule controller for the hub
- Improves multi error handling
- Retry status update on conflict
- Improve conditions update

ACM-21373: fix addon status update

---

.tekton/endpoint-monitoring-operator-acm-215-pull-request.yaml
.tekton/endpoint-monitoring-operator-acm-215-push.yaml
.tekton/grafana-dashboard-loader-acm-215-pull-request.yaml
.tekton/grafana-dashboard-loader-acm-215-push.yaml
.tekton/metrics-collector-acm-215-pull-request.yaml
.tekton/metrics-collector-acm-215-push.yaml
.tekton/multicluster-observability-operator-acm-215-pull-request.yaml
.tekton/multicluster-observability-operator-acm-215-push.yaml
.tekton/rbac-query-proxy-acm-215-pull-request.yaml
.tekton/rbac-query-proxy-acm-215-push.yaml

This commit applies the changes that came from the automatic new pipeline configurations for 2.15, while adding the following changes that we had from before:
- `main` as target branch
- multi-arch build on push
- hermetic builds
- correctly pre-fetching golang deps
- build source image

Konflux: apply changes from new template

---

tests/pkg/tests/observability_alert_test.go
tests/pkg/tests/observability_config_test.go
tests/pkg/tests/observability_dashboard_test.go
tests/pkg/tests/observability_export_test.go
tests/pkg/tests/observability_install_test.go
tests/pkg/tests/observability_metrics_test.go
tests/pkg/utils/utils.go

Ensures that we retry on conflicts to ensure tests (especially the install) doesn't get stuck.

e2e: retry on conflicts when apply

---

.github/workflows/konflux-rebuild-bot.sh
.github/workflows/konflux-rebuild-bot.yaml

We need Konflux builds on a regular basis. However Konflux doesn't support regular/daily builds at the moment.
This commit adds a new GitHub workflow, which on a schedule, comments on the latest commit with a build command, in all of the relevant branches. This should ensure we get regular builds, even when there have been no activity for a while.
Since we migrated to the ACM common build pipeline for the konflux tasks, we will likely have various release branches with very low activity, necessitating this workflow.

Add Konflux rebuild bot

---

operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go

Related to [ACM-21697](https://issues.redhat.com/browse/ACM-21697) 
Clean up/revert user-workload-monitoring-config configmap when user disables userWorkloadMonitoring on a managed cluster.

fix: Clean up user-workload-monitoring-config configmap properly

---

operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go

Related to [ACM-24087](https://issues.redhat.com/browse/ACM-24087)
Backport https://github.com/stolostron/multicluster-observability-operator/pull/2191

[release-2.13] Update hubInfoSecret when custom ingress cert is updated

---

collectors/metrics/cmd/metrics-collector/main.go

When creating different workers, we would pass on the same URL object to each worker. These worker would, in parallel, manipulate this object, causing a race condition.
In most cases, the effect of this, was that multiple workers would hit the same federate endpoint (which has the metrics to federate in the URL as GET parameters), and as a result we would send some metrics multiple times, and other metrics we would not send at all, causing loss of data.

metrics-collector: copy URL to avoid racecondition
